# coding: utf-8

"""
    Sipher — Privacy-as-a-Skill API

    REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

    The version of the OpenAPI document: 0.1.0
    Contact: hello@sip-protocol.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sipher_client.models.create_admin_key201_response_data import CreateAdminKey201ResponseData

class TestCreateAdminKey201ResponseData(unittest.TestCase):
    """CreateAdminKey201ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateAdminKey201ResponseData:
        """Test CreateAdminKey201ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateAdminKey201ResponseData`
        """
        model = CreateAdminKey201ResponseData()
        if include_optional:
            return CreateAdminKey201ResponseData(
                id = '',
                key = '',
                tier = '',
                name = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                limits = sipher_client.models.token_info.token_info(),
                notice = ''
            )
        else:
            return CreateAdminKey201ResponseData(
        )
        """

    def testCreateAdminKey201ResponseData(self):
        """Test CreateAdminKey201ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
