# coding: utf-8

"""
    Sipher — Privacy-as-a-Skill API

    REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

    The version of the OpenAPI document: 0.1.0
    Contact: hello@sip-protocol.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sipher_client.models.scan_assets200_response_data_assets_inner import ScanAssets200ResponseDataAssetsInner

class TestScanAssets200ResponseDataAssetsInner(unittest.TestCase):
    """ScanAssets200ResponseDataAssetsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScanAssets200ResponseDataAssetsInner:
        """Test ScanAssets200ResponseDataAssetsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScanAssets200ResponseDataAssetsInner`
        """
        model = ScanAssets200ResponseDataAssetsInner()
        if include_optional:
            return ScanAssets200ResponseDataAssetsInner(
                id = '',
                interface = '',
                token_info = None,
                ownership = None
            )
        else:
            return ScanAssets200ResponseDataAssetsInner(
        )
        """

    def testScanAssets200ResponseDataAssetsInner(self):
        """Test ScanAssets200ResponseDataAssetsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
