# coding: utf-8

"""
    Sipher — Privacy-as-a-Skill API

    REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

    The version of the OpenAPI document: 0.1.0
    Contact: hello@sip-protocol.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sipher_client.models.submit_ballot200_response import SubmitBallot200Response

class TestSubmitBallot200Response(unittest.TestCase):
    """SubmitBallot200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubmitBallot200Response:
        """Test SubmitBallot200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubmitBallot200Response`
        """
        model = SubmitBallot200Response()
        if include_optional:
            return SubmitBallot200Response(
                success = True,
                beta = True,
                warning = '',
                data = sipher_client.models.submit_ballot_200_response_data.submitBallot_200_response_data(
                    proposal_id = '', 
                    nullifier = '', 
                    accepted = True, 
                    total_ballots = 56, )
            )
        else:
            return SubmitBallot200Response(
        )
        """

    def testSubmitBallot200Response(self):
        """Test SubmitBallot200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
