# coding: utf-8

"""
    Sipher — Privacy-as-a-Skill API

    REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

    The version of the OpenAPI document: 0.1.0
    Contact: hello@sip-protocol.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sipher_client.models.get_session200_response_data import GetSession200ResponseData

class TestGetSession200ResponseData(unittest.TestCase):
    """GetSession200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetSession200ResponseData:
        """Test GetSession200ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetSession200ResponseData`
        """
        model = GetSession200ResponseData()
        if include_optional:
            return GetSession200ResponseData(
                session_id = '',
                defaults = sipher_client.models.token_info.token_info(),
                created_at = 56,
                expires_at = 56,
                last_accessed_at = 56
            )
        else:
            return GetSession200ResponseData(
        )
        """

    def testGetSession200ResponseData(self):
        """Test GetSession200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
