# coding: utf-8

"""
    Sipher — Privacy-as-a-Skill API

    REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

    The version of the OpenAPI document: 0.1.0
    Contact: hello@sip-protocol.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sipher_client.models.get_tally200_response import GetTally200Response

class TestGetTally200Response(unittest.TestCase):
    """GetTally200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetTally200Response:
        """Test GetTally200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetTally200Response`
        """
        model = GetTally200Response()
        if include_optional:
            return GetTally200Response(
                success = True,
                beta = True,
                warning = '',
                data = sipher_client.models.get_tally_200_response_data.getTally_200_response_data(
                    tally_id = '', 
                    proposal_id = '', 
                    total_votes = 56, 
                    yes_votes = 56, 
                    no_votes = 56, 
                    abstain_votes = 56, 
                    tally_commitment = '', 
                    tally_blinding = '', 
                    verification_hash = '', 
                    verified = True, 
                    tallied_at = 56, )
            )
        else:
            return GetTally200Response(
        )
        """

    def testGetTally200Response(self):
        """Test GetTally200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
