# coding: utf-8

"""
    Sipher — Privacy-as-a-Skill API

    REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

    The version of the OpenAPI document: 0.1.0
    Contact: hello@sip-protocol.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sipher_client.models.get_session200_response import GetSession200Response

class TestGetSession200Response(unittest.TestCase):
    """GetSession200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetSession200Response:
        """Test GetSession200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetSession200Response`
        """
        model = GetSession200Response()
        if include_optional:
            return GetSession200Response(
                success = True,
                data = sipher_client.models.get_session_200_response_data.getSession_200_response_data(
                    session_id = '', 
                    defaults = sipher_client.models.token_info.token_info(), 
                    created_at = 56, 
                    expires_at = 56, 
                    last_accessed_at = 56, )
            )
        else:
            return GetSession200Response(
        )
        """

    def testGetSession200Response(self):
        """Test GetSession200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
