# coding: utf-8

"""
    Sipher — Privacy-as-a-Skill API

    REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

    The version of the OpenAPI document: 0.1.0
    Contact: hello@sip-protocol.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sipher_client.models.scan_assets200_response_data import ScanAssets200ResponseData

class TestScanAssets200ResponseData(unittest.TestCase):
    """ScanAssets200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScanAssets200ResponseData:
        """Test ScanAssets200ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScanAssets200ResponseData`
        """
        model = ScanAssets200ResponseData()
        if include_optional:
            return ScanAssets200ResponseData(
                assets = [
                    sipher_client.models.scan_assets_200_response_data_assets_inner.scanAssets_200_response_data_assets_inner(
                        id = '', 
                        interface = '', 
                        token_info = sipher_client.models.token_info.token_info(), 
                        ownership = sipher_client.models.token_info.token_info(), )
                    ],
                total = 56,
                page = 56,
                limit = 56,
                provider = 'helius-das'
            )
        else:
            return ScanAssets200ResponseData(
        )
        """

    def testScanAssets200ResponseData(self):
        """Test ScanAssets200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
