# coding: utf-8

"""
    Sipher — Privacy-as-a-Skill API

    REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

    The version of the OpenAPI document: 0.1.0
    Contact: hello@sip-protocol.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sipher_client.models.transfer_shield200_response_data import TransferShield200ResponseData

class TestTransferShield200ResponseData(unittest.TestCase):
    """TransferShield200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransferShield200ResponseData:
        """Test TransferShield200ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransferShield200ResponseData`
        """
        model = TransferShield200ResponseData()
        if include_optional:
            return TransferShield200ResponseData(
                transaction = '',
                stealth_address = '',
                ephemeral_public_key = '0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef',
                view_tag = 56,
                commitment = '0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef',
                blinding_factor = '0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef',
                viewing_key_hash = '0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef',
                shared_secret = '0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef',
                program_id = '',
                note_id = '',
                instruction_type = 'anchor',
                encrypted_amount = ''
            )
        else:
            return TransferShield200ResponseData(
        )
        """

    def testTransferShield200ResponseData(self):
        """Test TransferShield200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
