# coding: utf-8

"""
    Sipher — Privacy-as-a-Skill API

    REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

    The version of the OpenAPI document: 0.1.0
    Contact: hello@sip-protocol.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sipher_client.models.get_compliance_report200_response import GetComplianceReport200Response

class TestGetComplianceReport200Response(unittest.TestCase):
    """GetComplianceReport200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetComplianceReport200Response:
        """Test GetComplianceReport200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetComplianceReport200Response`
        """
        model = GetComplianceReport200Response()
        if include_optional:
            return GetComplianceReport200Response(
                success = True,
                data = sipher_client.models.get_compliance_report_200_response_data.getComplianceReport_200_response_data(
                    report_id = '', 
                    status = '', 
                    generated_at = 56, 
                    expires_at = 56, 
                    summary = sipher_client.models.token_info.token_info(), 
                    encrypted_report = '', 
                    report_hash = '', )
            )
        else:
            return GetComplianceReport200Response(
        )
        """

    def testGetComplianceReport200Response(self):
        """Test GetComplianceReport200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
