/*
 * Sipher — Privacy-as-a-Skill API
 *
 * REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateSessionRequestDefaults {
    #[serde(rename = "chain", skip_serializing_if = "Option::is_none")]
    pub chain: Option<Chain>,
    #[serde(rename = "privacyLevel", skip_serializing_if = "Option::is_none")]
    pub privacy_level: Option<PrivacyLevel>,
    #[serde(rename = "rpcProvider", skip_serializing_if = "Option::is_none")]
    pub rpc_provider: Option<RpcProvider>,
    #[serde(rename = "backend", skip_serializing_if = "Option::is_none")]
    pub backend: Option<Backend>,
    #[serde(rename = "defaultViewingKey", skip_serializing_if = "Option::is_none")]
    pub default_viewing_key: Option<String>,
}

impl CreateSessionRequestDefaults {
    pub fn new() -> CreateSessionRequestDefaults {
        CreateSessionRequestDefaults {
            chain: None,
            privacy_level: None,
            rpc_provider: None,
            backend: None,
            default_viewing_key: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Chain {
    #[serde(rename = "solana")]
    Solana,
    #[serde(rename = "ethereum")]
    Ethereum,
    #[serde(rename = "polygon")]
    Polygon,
    #[serde(rename = "arbitrum")]
    Arbitrum,
    #[serde(rename = "optimism")]
    Optimism,
    #[serde(rename = "base")]
    Base,
    #[serde(rename = "near")]
    Near,
    #[serde(rename = "aptos")]
    Aptos,
    #[serde(rename = "sui")]
    Sui,
    #[serde(rename = "cosmos")]
    Cosmos,
    #[serde(rename = "osmosis")]
    Osmosis,
    #[serde(rename = "injective")]
    Injective,
    #[serde(rename = "celestia")]
    Celestia,
    #[serde(rename = "sei")]
    Sei,
    #[serde(rename = "dydx")]
    Dydx,
    #[serde(rename = "bitcoin")]
    Bitcoin,
    #[serde(rename = "zcash")]
    Zcash,
}

impl Default for Chain {
    fn default() -> Chain {
        Self::Solana
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PrivacyLevel {
    #[serde(rename = "standard")]
    Standard,
    #[serde(rename = "shielded")]
    Shielded,
    #[serde(rename = "maximum")]
    Maximum,
}

impl Default for PrivacyLevel {
    fn default() -> PrivacyLevel {
        Self::Standard
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RpcProvider {
    #[serde(rename = "helius")]
    Helius,
    #[serde(rename = "quicknode")]
    Quicknode,
    #[serde(rename = "triton")]
    Triton,
    #[serde(rename = "generic")]
    Generic,
}

impl Default for RpcProvider {
    fn default() -> RpcProvider {
        Self::Helius
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Backend {
    #[serde(rename = "sip-native")]
    SipNative,
}

impl Default for Backend {
    fn default() -> Backend {
        Self::SipNative
    }
}

