/*
 * Sipher — Privacy-as-a-Skill API
 *
 * REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScanAssets200ResponseDataAssetsInner {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "interface", skip_serializing_if = "Option::is_none")]
    pub interface: Option<String>,
    #[serde(rename = "token_info", skip_serializing_if = "Option::is_none")]
    pub token_info: Option<serde_json::Value>,
    #[serde(rename = "ownership", skip_serializing_if = "Option::is_none")]
    pub ownership: Option<serde_json::Value>,
}

impl ScanAssets200ResponseDataAssetsInner {
    pub fn new() -> ScanAssets200ResponseDataAssetsInner {
        ScanAssets200ResponseDataAssetsInner {
            id: None,
            interface: None,
            token_info: None,
            ownership: None,
        }
    }
}

