/*
 * Sipher — Privacy-as-a-Skill API
 *
 * REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StealthCheckRequest {
    #[serde(rename = "stealthAddress")]
    pub stealth_address: Box<models::StealthAddress>,
    /// 0x-prefixed 32-byte hex string
    #[serde(rename = "viewingPrivateKey")]
    pub viewing_private_key: String,
    /// 0x-prefixed 32-byte hex string
    #[serde(rename = "spendingPublicKey")]
    pub spending_public_key: String,
}

impl StealthCheckRequest {
    pub fn new(stealth_address: models::StealthAddress, viewing_private_key: String, spending_public_key: String) -> StealthCheckRequest {
        StealthCheckRequest {
            stealth_address: Box::new(stealth_address),
            viewing_private_key,
            spending_public_key,
        }
    }
}

