/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
)

// checks if the ProofsRangeGenerate200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProofsRangeGenerate200Response{}

// ProofsRangeGenerate200Response struct for ProofsRangeGenerate200Response
type ProofsRangeGenerate200Response struct {
	Success *bool `json:"success,omitempty"`
	Beta *bool `json:"beta,omitempty"`
	Warning *string `json:"warning,omitempty"`
	Data *ProofsRangeGenerate200ResponseData `json:"data,omitempty"`
}

// NewProofsRangeGenerate200Response instantiates a new ProofsRangeGenerate200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProofsRangeGenerate200Response() *ProofsRangeGenerate200Response {
	this := ProofsRangeGenerate200Response{}
	return &this
}

// NewProofsRangeGenerate200ResponseWithDefaults instantiates a new ProofsRangeGenerate200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProofsRangeGenerate200ResponseWithDefaults() *ProofsRangeGenerate200Response {
	this := ProofsRangeGenerate200Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *ProofsRangeGenerate200Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProofsRangeGenerate200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *ProofsRangeGenerate200Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *ProofsRangeGenerate200Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetBeta returns the Beta field value if set, zero value otherwise.
func (o *ProofsRangeGenerate200Response) GetBeta() bool {
	if o == nil || IsNil(o.Beta) {
		var ret bool
		return ret
	}
	return *o.Beta
}

// GetBetaOk returns a tuple with the Beta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProofsRangeGenerate200Response) GetBetaOk() (*bool, bool) {
	if o == nil || IsNil(o.Beta) {
		return nil, false
	}
	return o.Beta, true
}

// HasBeta returns a boolean if a field has been set.
func (o *ProofsRangeGenerate200Response) HasBeta() bool {
	if o != nil && !IsNil(o.Beta) {
		return true
	}

	return false
}

// SetBeta gets a reference to the given bool and assigns it to the Beta field.
func (o *ProofsRangeGenerate200Response) SetBeta(v bool) {
	o.Beta = &v
}

// GetWarning returns the Warning field value if set, zero value otherwise.
func (o *ProofsRangeGenerate200Response) GetWarning() string {
	if o == nil || IsNil(o.Warning) {
		var ret string
		return ret
	}
	return *o.Warning
}

// GetWarningOk returns a tuple with the Warning field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProofsRangeGenerate200Response) GetWarningOk() (*string, bool) {
	if o == nil || IsNil(o.Warning) {
		return nil, false
	}
	return o.Warning, true
}

// HasWarning returns a boolean if a field has been set.
func (o *ProofsRangeGenerate200Response) HasWarning() bool {
	if o != nil && !IsNil(o.Warning) {
		return true
	}

	return false
}

// SetWarning gets a reference to the given string and assigns it to the Warning field.
func (o *ProofsRangeGenerate200Response) SetWarning(v string) {
	o.Warning = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ProofsRangeGenerate200Response) GetData() ProofsRangeGenerate200ResponseData {
	if o == nil || IsNil(o.Data) {
		var ret ProofsRangeGenerate200ResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProofsRangeGenerate200Response) GetDataOk() (*ProofsRangeGenerate200ResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ProofsRangeGenerate200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given ProofsRangeGenerate200ResponseData and assigns it to the Data field.
func (o *ProofsRangeGenerate200Response) SetData(v ProofsRangeGenerate200ResponseData) {
	o.Data = &v
}

func (o ProofsRangeGenerate200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProofsRangeGenerate200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Beta) {
		toSerialize["beta"] = o.Beta
	}
	if !IsNil(o.Warning) {
		toSerialize["warning"] = o.Warning
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableProofsRangeGenerate200Response struct {
	value *ProofsRangeGenerate200Response
	isSet bool
}

func (v NullableProofsRangeGenerate200Response) Get() *ProofsRangeGenerate200Response {
	return v.value
}

func (v *NullableProofsRangeGenerate200Response) Set(val *ProofsRangeGenerate200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableProofsRangeGenerate200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableProofsRangeGenerate200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProofsRangeGenerate200Response(val *ProofsRangeGenerate200Response) *NullableProofsRangeGenerate200Response {
	return &NullableProofsRangeGenerate200Response{value: val, isSet: true}
}

func (v NullableProofsRangeGenerate200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProofsRangeGenerate200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


