/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ComputeIncoCiphertextsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComputeIncoCiphertextsRequest{}

// ComputeIncoCiphertextsRequest struct for ComputeIncoCiphertextsRequest
type ComputeIncoCiphertextsRequest struct {
	// Homomorphic operation
	Operation string `json:"operation"`
	// Ciphertexts to operate on
	Ciphertexts []string `json:"ciphertexts"`
	Scheme *string `json:"scheme,omitempty"`
}

type _ComputeIncoCiphertextsRequest ComputeIncoCiphertextsRequest

// NewComputeIncoCiphertextsRequest instantiates a new ComputeIncoCiphertextsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComputeIncoCiphertextsRequest(operation string, ciphertexts []string) *ComputeIncoCiphertextsRequest {
	this := ComputeIncoCiphertextsRequest{}
	this.Operation = operation
	this.Ciphertexts = ciphertexts
	var scheme string = "tfhe"
	this.Scheme = &scheme
	return &this
}

// NewComputeIncoCiphertextsRequestWithDefaults instantiates a new ComputeIncoCiphertextsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComputeIncoCiphertextsRequestWithDefaults() *ComputeIncoCiphertextsRequest {
	this := ComputeIncoCiphertextsRequest{}
	var scheme string = "tfhe"
	this.Scheme = &scheme
	return &this
}

// GetOperation returns the Operation field value
func (o *ComputeIncoCiphertextsRequest) GetOperation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Operation
}

// GetOperationOk returns a tuple with the Operation field value
// and a boolean to check if the value has been set.
func (o *ComputeIncoCiphertextsRequest) GetOperationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Operation, true
}

// SetOperation sets field value
func (o *ComputeIncoCiphertextsRequest) SetOperation(v string) {
	o.Operation = v
}

// GetCiphertexts returns the Ciphertexts field value
func (o *ComputeIncoCiphertextsRequest) GetCiphertexts() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Ciphertexts
}

// GetCiphertextsOk returns a tuple with the Ciphertexts field value
// and a boolean to check if the value has been set.
func (o *ComputeIncoCiphertextsRequest) GetCiphertextsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Ciphertexts, true
}

// SetCiphertexts sets field value
func (o *ComputeIncoCiphertextsRequest) SetCiphertexts(v []string) {
	o.Ciphertexts = v
}

// GetScheme returns the Scheme field value if set, zero value otherwise.
func (o *ComputeIncoCiphertextsRequest) GetScheme() string {
	if o == nil || IsNil(o.Scheme) {
		var ret string
		return ret
	}
	return *o.Scheme
}

// GetSchemeOk returns a tuple with the Scheme field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComputeIncoCiphertextsRequest) GetSchemeOk() (*string, bool) {
	if o == nil || IsNil(o.Scheme) {
		return nil, false
	}
	return o.Scheme, true
}

// HasScheme returns a boolean if a field has been set.
func (o *ComputeIncoCiphertextsRequest) HasScheme() bool {
	if o != nil && !IsNil(o.Scheme) {
		return true
	}

	return false
}

// SetScheme gets a reference to the given string and assigns it to the Scheme field.
func (o *ComputeIncoCiphertextsRequest) SetScheme(v string) {
	o.Scheme = &v
}

func (o ComputeIncoCiphertextsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComputeIncoCiphertextsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["operation"] = o.Operation
	toSerialize["ciphertexts"] = o.Ciphertexts
	if !IsNil(o.Scheme) {
		toSerialize["scheme"] = o.Scheme
	}
	return toSerialize, nil
}

func (o *ComputeIncoCiphertextsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"operation",
		"ciphertexts",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varComputeIncoCiphertextsRequest := _ComputeIncoCiphertextsRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varComputeIncoCiphertextsRequest)

	if err != nil {
		return err
	}

	*o = ComputeIncoCiphertextsRequest(varComputeIncoCiphertextsRequest)

	return err
}

type NullableComputeIncoCiphertextsRequest struct {
	value *ComputeIncoCiphertextsRequest
	isSet bool
}

func (v NullableComputeIncoCiphertextsRequest) Get() *ComputeIncoCiphertextsRequest {
	return v.value
}

func (v *NullableComputeIncoCiphertextsRequest) Set(val *ComputeIncoCiphertextsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableComputeIncoCiphertextsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableComputeIncoCiphertextsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComputeIncoCiphertextsRequest(val *ComputeIncoCiphertextsRequest) *NullableComputeIncoCiphertextsRequest {
	return &NullableComputeIncoCiphertextsRequest{value: val, isSet: true}
}

func (v NullableComputeIncoCiphertextsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComputeIncoCiphertextsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


