/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
)

// checks if the ProofsValidityGenerate200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProofsValidityGenerate200ResponseData{}

// ProofsValidityGenerate200ResponseData struct for ProofsValidityGenerate200ResponseData
type ProofsValidityGenerate200ResponseData struct {
	Proof *ProofsValidityGenerate200ResponseDataProof `json:"proof,omitempty"`
	PublicInputs []string `json:"publicInputs,omitempty"`
}

// NewProofsValidityGenerate200ResponseData instantiates a new ProofsValidityGenerate200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProofsValidityGenerate200ResponseData() *ProofsValidityGenerate200ResponseData {
	this := ProofsValidityGenerate200ResponseData{}
	return &this
}

// NewProofsValidityGenerate200ResponseDataWithDefaults instantiates a new ProofsValidityGenerate200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProofsValidityGenerate200ResponseDataWithDefaults() *ProofsValidityGenerate200ResponseData {
	this := ProofsValidityGenerate200ResponseData{}
	return &this
}

// GetProof returns the Proof field value if set, zero value otherwise.
func (o *ProofsValidityGenerate200ResponseData) GetProof() ProofsValidityGenerate200ResponseDataProof {
	if o == nil || IsNil(o.Proof) {
		var ret ProofsValidityGenerate200ResponseDataProof
		return ret
	}
	return *o.Proof
}

// GetProofOk returns a tuple with the Proof field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProofsValidityGenerate200ResponseData) GetProofOk() (*ProofsValidityGenerate200ResponseDataProof, bool) {
	if o == nil || IsNil(o.Proof) {
		return nil, false
	}
	return o.Proof, true
}

// HasProof returns a boolean if a field has been set.
func (o *ProofsValidityGenerate200ResponseData) HasProof() bool {
	if o != nil && !IsNil(o.Proof) {
		return true
	}

	return false
}

// SetProof gets a reference to the given ProofsValidityGenerate200ResponseDataProof and assigns it to the Proof field.
func (o *ProofsValidityGenerate200ResponseData) SetProof(v ProofsValidityGenerate200ResponseDataProof) {
	o.Proof = &v
}

// GetPublicInputs returns the PublicInputs field value if set, zero value otherwise.
func (o *ProofsValidityGenerate200ResponseData) GetPublicInputs() []string {
	if o == nil || IsNil(o.PublicInputs) {
		var ret []string
		return ret
	}
	return o.PublicInputs
}

// GetPublicInputsOk returns a tuple with the PublicInputs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProofsValidityGenerate200ResponseData) GetPublicInputsOk() ([]string, bool) {
	if o == nil || IsNil(o.PublicInputs) {
		return nil, false
	}
	return o.PublicInputs, true
}

// HasPublicInputs returns a boolean if a field has been set.
func (o *ProofsValidityGenerate200ResponseData) HasPublicInputs() bool {
	if o != nil && !IsNil(o.PublicInputs) {
		return true
	}

	return false
}

// SetPublicInputs gets a reference to the given []string and assigns it to the PublicInputs field.
func (o *ProofsValidityGenerate200ResponseData) SetPublicInputs(v []string) {
	o.PublicInputs = v
}

func (o ProofsValidityGenerate200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProofsValidityGenerate200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Proof) {
		toSerialize["proof"] = o.Proof
	}
	if !IsNil(o.PublicInputs) {
		toSerialize["publicInputs"] = o.PublicInputs
	}
	return toSerialize, nil
}

type NullableProofsValidityGenerate200ResponseData struct {
	value *ProofsValidityGenerate200ResponseData
	isSet bool
}

func (v NullableProofsValidityGenerate200ResponseData) Get() *ProofsValidityGenerate200ResponseData {
	return v.value
}

func (v *NullableProofsValidityGenerate200ResponseData) Set(val *ProofsValidityGenerate200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableProofsValidityGenerate200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableProofsValidityGenerate200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProofsValidityGenerate200ResponseData(val *ProofsValidityGenerate200ResponseData) *NullableProofsValidityGenerate200ResponseData {
	return &NullableProofsValidityGenerate200ResponseData{value: val, isSet: true}
}

func (v NullableProofsValidityGenerate200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProofsValidityGenerate200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


