/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
)

// checks if the GetHealth200ResponseDataSolana type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetHealth200ResponseDataSolana{}

// GetHealth200ResponseDataSolana struct for GetHealth200ResponseDataSolana
type GetHealth200ResponseDataSolana struct {
	Connected *bool `json:"connected,omitempty"`
	Cluster *string `json:"cluster,omitempty"`
	Slot *int32 `json:"slot,omitempty"`
	LatencyMs *int32 `json:"latencyMs,omitempty"`
}

// NewGetHealth200ResponseDataSolana instantiates a new GetHealth200ResponseDataSolana object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetHealth200ResponseDataSolana() *GetHealth200ResponseDataSolana {
	this := GetHealth200ResponseDataSolana{}
	return &this
}

// NewGetHealth200ResponseDataSolanaWithDefaults instantiates a new GetHealth200ResponseDataSolana object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetHealth200ResponseDataSolanaWithDefaults() *GetHealth200ResponseDataSolana {
	this := GetHealth200ResponseDataSolana{}
	return &this
}

// GetConnected returns the Connected field value if set, zero value otherwise.
func (o *GetHealth200ResponseDataSolana) GetConnected() bool {
	if o == nil || IsNil(o.Connected) {
		var ret bool
		return ret
	}
	return *o.Connected
}

// GetConnectedOk returns a tuple with the Connected field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetHealth200ResponseDataSolana) GetConnectedOk() (*bool, bool) {
	if o == nil || IsNil(o.Connected) {
		return nil, false
	}
	return o.Connected, true
}

// HasConnected returns a boolean if a field has been set.
func (o *GetHealth200ResponseDataSolana) HasConnected() bool {
	if o != nil && !IsNil(o.Connected) {
		return true
	}

	return false
}

// SetConnected gets a reference to the given bool and assigns it to the Connected field.
func (o *GetHealth200ResponseDataSolana) SetConnected(v bool) {
	o.Connected = &v
}

// GetCluster returns the Cluster field value if set, zero value otherwise.
func (o *GetHealth200ResponseDataSolana) GetCluster() string {
	if o == nil || IsNil(o.Cluster) {
		var ret string
		return ret
	}
	return *o.Cluster
}

// GetClusterOk returns a tuple with the Cluster field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetHealth200ResponseDataSolana) GetClusterOk() (*string, bool) {
	if o == nil || IsNil(o.Cluster) {
		return nil, false
	}
	return o.Cluster, true
}

// HasCluster returns a boolean if a field has been set.
func (o *GetHealth200ResponseDataSolana) HasCluster() bool {
	if o != nil && !IsNil(o.Cluster) {
		return true
	}

	return false
}

// SetCluster gets a reference to the given string and assigns it to the Cluster field.
func (o *GetHealth200ResponseDataSolana) SetCluster(v string) {
	o.Cluster = &v
}

// GetSlot returns the Slot field value if set, zero value otherwise.
func (o *GetHealth200ResponseDataSolana) GetSlot() int32 {
	if o == nil || IsNil(o.Slot) {
		var ret int32
		return ret
	}
	return *o.Slot
}

// GetSlotOk returns a tuple with the Slot field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetHealth200ResponseDataSolana) GetSlotOk() (*int32, bool) {
	if o == nil || IsNil(o.Slot) {
		return nil, false
	}
	return o.Slot, true
}

// HasSlot returns a boolean if a field has been set.
func (o *GetHealth200ResponseDataSolana) HasSlot() bool {
	if o != nil && !IsNil(o.Slot) {
		return true
	}

	return false
}

// SetSlot gets a reference to the given int32 and assigns it to the Slot field.
func (o *GetHealth200ResponseDataSolana) SetSlot(v int32) {
	o.Slot = &v
}

// GetLatencyMs returns the LatencyMs field value if set, zero value otherwise.
func (o *GetHealth200ResponseDataSolana) GetLatencyMs() int32 {
	if o == nil || IsNil(o.LatencyMs) {
		var ret int32
		return ret
	}
	return *o.LatencyMs
}

// GetLatencyMsOk returns a tuple with the LatencyMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetHealth200ResponseDataSolana) GetLatencyMsOk() (*int32, bool) {
	if o == nil || IsNil(o.LatencyMs) {
		return nil, false
	}
	return o.LatencyMs, true
}

// HasLatencyMs returns a boolean if a field has been set.
func (o *GetHealth200ResponseDataSolana) HasLatencyMs() bool {
	if o != nil && !IsNil(o.LatencyMs) {
		return true
	}

	return false
}

// SetLatencyMs gets a reference to the given int32 and assigns it to the LatencyMs field.
func (o *GetHealth200ResponseDataSolana) SetLatencyMs(v int32) {
	o.LatencyMs = &v
}

func (o GetHealth200ResponseDataSolana) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetHealth200ResponseDataSolana) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Connected) {
		toSerialize["connected"] = o.Connected
	}
	if !IsNil(o.Cluster) {
		toSerialize["cluster"] = o.Cluster
	}
	if !IsNil(o.Slot) {
		toSerialize["slot"] = o.Slot
	}
	if !IsNil(o.LatencyMs) {
		toSerialize["latencyMs"] = o.LatencyMs
	}
	return toSerialize, nil
}

type NullableGetHealth200ResponseDataSolana struct {
	value *GetHealth200ResponseDataSolana
	isSet bool
}

func (v NullableGetHealth200ResponseDataSolana) Get() *GetHealth200ResponseDataSolana {
	return v.value
}

func (v *NullableGetHealth200ResponseDataSolana) Set(val *GetHealth200ResponseDataSolana) {
	v.value = val
	v.isSet = true
}

func (v NullableGetHealth200ResponseDataSolana) IsSet() bool {
	return v.isSet
}

func (v *NullableGetHealth200ResponseDataSolana) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetHealth200ResponseDataSolana(val *GetHealth200ResponseDataSolana) *NullableGetHealth200ResponseDataSolana {
	return &NullableGetHealth200ResponseDataSolana{value: val, isSet: true}
}

func (v NullableGetHealth200ResponseDataSolana) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetHealth200ResponseDataSolana) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


