/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
)

// checks if the TransferPrivate200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransferPrivate200ResponseData{}

// TransferPrivate200ResponseData struct for TransferPrivate200ResponseData
type TransferPrivate200ResponseData struct {
	Chain *string `json:"chain,omitempty"`
	Curve *string `json:"curve,omitempty"`
	// Chain-native stealth address
	StealthAddress *string `json:"stealthAddress,omitempty"`
	// 0x-prefixed 32-byte hex string
	EphemeralPublicKey *string `json:"ephemeralPublicKey,omitempty" validate:"regexp=^0x[0-9a-fA-F]{64}$"`
	ViewTag *int32 `json:"viewTag,omitempty"`
	Commitment *string `json:"commitment,omitempty"`
	// 0x-prefixed 32-byte hex string
	BlindingFactor *string `json:"blindingFactor,omitempty" validate:"regexp=^0x[0-9a-fA-F]{64}$"`
	// 0x-prefixed 32-byte hex string
	ViewingKeyHash *string `json:"viewingKeyHash,omitempty" validate:"regexp=^0x[0-9a-fA-F]{64}$"`
	// 0x-prefixed 32-byte hex string
	SharedSecret *string `json:"sharedSecret,omitempty" validate:"regexp=^0x[0-9a-fA-F]{64}$"`
	ChainData *TransferPrivate200ResponseDataChainData `json:"chainData,omitempty"`
}

// NewTransferPrivate200ResponseData instantiates a new TransferPrivate200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransferPrivate200ResponseData() *TransferPrivate200ResponseData {
	this := TransferPrivate200ResponseData{}
	return &this
}

// NewTransferPrivate200ResponseDataWithDefaults instantiates a new TransferPrivate200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransferPrivate200ResponseDataWithDefaults() *TransferPrivate200ResponseData {
	this := TransferPrivate200ResponseData{}
	return &this
}

// GetChain returns the Chain field value if set, zero value otherwise.
func (o *TransferPrivate200ResponseData) GetChain() string {
	if o == nil || IsNil(o.Chain) {
		var ret string
		return ret
	}
	return *o.Chain
}

// GetChainOk returns a tuple with the Chain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransferPrivate200ResponseData) GetChainOk() (*string, bool) {
	if o == nil || IsNil(o.Chain) {
		return nil, false
	}
	return o.Chain, true
}

// HasChain returns a boolean if a field has been set.
func (o *TransferPrivate200ResponseData) HasChain() bool {
	if o != nil && !IsNil(o.Chain) {
		return true
	}

	return false
}

// SetChain gets a reference to the given string and assigns it to the Chain field.
func (o *TransferPrivate200ResponseData) SetChain(v string) {
	o.Chain = &v
}

// GetCurve returns the Curve field value if set, zero value otherwise.
func (o *TransferPrivate200ResponseData) GetCurve() string {
	if o == nil || IsNil(o.Curve) {
		var ret string
		return ret
	}
	return *o.Curve
}

// GetCurveOk returns a tuple with the Curve field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransferPrivate200ResponseData) GetCurveOk() (*string, bool) {
	if o == nil || IsNil(o.Curve) {
		return nil, false
	}
	return o.Curve, true
}

// HasCurve returns a boolean if a field has been set.
func (o *TransferPrivate200ResponseData) HasCurve() bool {
	if o != nil && !IsNil(o.Curve) {
		return true
	}

	return false
}

// SetCurve gets a reference to the given string and assigns it to the Curve field.
func (o *TransferPrivate200ResponseData) SetCurve(v string) {
	o.Curve = &v
}

// GetStealthAddress returns the StealthAddress field value if set, zero value otherwise.
func (o *TransferPrivate200ResponseData) GetStealthAddress() string {
	if o == nil || IsNil(o.StealthAddress) {
		var ret string
		return ret
	}
	return *o.StealthAddress
}

// GetStealthAddressOk returns a tuple with the StealthAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransferPrivate200ResponseData) GetStealthAddressOk() (*string, bool) {
	if o == nil || IsNil(o.StealthAddress) {
		return nil, false
	}
	return o.StealthAddress, true
}

// HasStealthAddress returns a boolean if a field has been set.
func (o *TransferPrivate200ResponseData) HasStealthAddress() bool {
	if o != nil && !IsNil(o.StealthAddress) {
		return true
	}

	return false
}

// SetStealthAddress gets a reference to the given string and assigns it to the StealthAddress field.
func (o *TransferPrivate200ResponseData) SetStealthAddress(v string) {
	o.StealthAddress = &v
}

// GetEphemeralPublicKey returns the EphemeralPublicKey field value if set, zero value otherwise.
func (o *TransferPrivate200ResponseData) GetEphemeralPublicKey() string {
	if o == nil || IsNil(o.EphemeralPublicKey) {
		var ret string
		return ret
	}
	return *o.EphemeralPublicKey
}

// GetEphemeralPublicKeyOk returns a tuple with the EphemeralPublicKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransferPrivate200ResponseData) GetEphemeralPublicKeyOk() (*string, bool) {
	if o == nil || IsNil(o.EphemeralPublicKey) {
		return nil, false
	}
	return o.EphemeralPublicKey, true
}

// HasEphemeralPublicKey returns a boolean if a field has been set.
func (o *TransferPrivate200ResponseData) HasEphemeralPublicKey() bool {
	if o != nil && !IsNil(o.EphemeralPublicKey) {
		return true
	}

	return false
}

// SetEphemeralPublicKey gets a reference to the given string and assigns it to the EphemeralPublicKey field.
func (o *TransferPrivate200ResponseData) SetEphemeralPublicKey(v string) {
	o.EphemeralPublicKey = &v
}

// GetViewTag returns the ViewTag field value if set, zero value otherwise.
func (o *TransferPrivate200ResponseData) GetViewTag() int32 {
	if o == nil || IsNil(o.ViewTag) {
		var ret int32
		return ret
	}
	return *o.ViewTag
}

// GetViewTagOk returns a tuple with the ViewTag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransferPrivate200ResponseData) GetViewTagOk() (*int32, bool) {
	if o == nil || IsNil(o.ViewTag) {
		return nil, false
	}
	return o.ViewTag, true
}

// HasViewTag returns a boolean if a field has been set.
func (o *TransferPrivate200ResponseData) HasViewTag() bool {
	if o != nil && !IsNil(o.ViewTag) {
		return true
	}

	return false
}

// SetViewTag gets a reference to the given int32 and assigns it to the ViewTag field.
func (o *TransferPrivate200ResponseData) SetViewTag(v int32) {
	o.ViewTag = &v
}

// GetCommitment returns the Commitment field value if set, zero value otherwise.
func (o *TransferPrivate200ResponseData) GetCommitment() string {
	if o == nil || IsNil(o.Commitment) {
		var ret string
		return ret
	}
	return *o.Commitment
}

// GetCommitmentOk returns a tuple with the Commitment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransferPrivate200ResponseData) GetCommitmentOk() (*string, bool) {
	if o == nil || IsNil(o.Commitment) {
		return nil, false
	}
	return o.Commitment, true
}

// HasCommitment returns a boolean if a field has been set.
func (o *TransferPrivate200ResponseData) HasCommitment() bool {
	if o != nil && !IsNil(o.Commitment) {
		return true
	}

	return false
}

// SetCommitment gets a reference to the given string and assigns it to the Commitment field.
func (o *TransferPrivate200ResponseData) SetCommitment(v string) {
	o.Commitment = &v
}

// GetBlindingFactor returns the BlindingFactor field value if set, zero value otherwise.
func (o *TransferPrivate200ResponseData) GetBlindingFactor() string {
	if o == nil || IsNil(o.BlindingFactor) {
		var ret string
		return ret
	}
	return *o.BlindingFactor
}

// GetBlindingFactorOk returns a tuple with the BlindingFactor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransferPrivate200ResponseData) GetBlindingFactorOk() (*string, bool) {
	if o == nil || IsNil(o.BlindingFactor) {
		return nil, false
	}
	return o.BlindingFactor, true
}

// HasBlindingFactor returns a boolean if a field has been set.
func (o *TransferPrivate200ResponseData) HasBlindingFactor() bool {
	if o != nil && !IsNil(o.BlindingFactor) {
		return true
	}

	return false
}

// SetBlindingFactor gets a reference to the given string and assigns it to the BlindingFactor field.
func (o *TransferPrivate200ResponseData) SetBlindingFactor(v string) {
	o.BlindingFactor = &v
}

// GetViewingKeyHash returns the ViewingKeyHash field value if set, zero value otherwise.
func (o *TransferPrivate200ResponseData) GetViewingKeyHash() string {
	if o == nil || IsNil(o.ViewingKeyHash) {
		var ret string
		return ret
	}
	return *o.ViewingKeyHash
}

// GetViewingKeyHashOk returns a tuple with the ViewingKeyHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransferPrivate200ResponseData) GetViewingKeyHashOk() (*string, bool) {
	if o == nil || IsNil(o.ViewingKeyHash) {
		return nil, false
	}
	return o.ViewingKeyHash, true
}

// HasViewingKeyHash returns a boolean if a field has been set.
func (o *TransferPrivate200ResponseData) HasViewingKeyHash() bool {
	if o != nil && !IsNil(o.ViewingKeyHash) {
		return true
	}

	return false
}

// SetViewingKeyHash gets a reference to the given string and assigns it to the ViewingKeyHash field.
func (o *TransferPrivate200ResponseData) SetViewingKeyHash(v string) {
	o.ViewingKeyHash = &v
}

// GetSharedSecret returns the SharedSecret field value if set, zero value otherwise.
func (o *TransferPrivate200ResponseData) GetSharedSecret() string {
	if o == nil || IsNil(o.SharedSecret) {
		var ret string
		return ret
	}
	return *o.SharedSecret
}

// GetSharedSecretOk returns a tuple with the SharedSecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransferPrivate200ResponseData) GetSharedSecretOk() (*string, bool) {
	if o == nil || IsNil(o.SharedSecret) {
		return nil, false
	}
	return o.SharedSecret, true
}

// HasSharedSecret returns a boolean if a field has been set.
func (o *TransferPrivate200ResponseData) HasSharedSecret() bool {
	if o != nil && !IsNil(o.SharedSecret) {
		return true
	}

	return false
}

// SetSharedSecret gets a reference to the given string and assigns it to the SharedSecret field.
func (o *TransferPrivate200ResponseData) SetSharedSecret(v string) {
	o.SharedSecret = &v
}

// GetChainData returns the ChainData field value if set, zero value otherwise.
func (o *TransferPrivate200ResponseData) GetChainData() TransferPrivate200ResponseDataChainData {
	if o == nil || IsNil(o.ChainData) {
		var ret TransferPrivate200ResponseDataChainData
		return ret
	}
	return *o.ChainData
}

// GetChainDataOk returns a tuple with the ChainData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransferPrivate200ResponseData) GetChainDataOk() (*TransferPrivate200ResponseDataChainData, bool) {
	if o == nil || IsNil(o.ChainData) {
		return nil, false
	}
	return o.ChainData, true
}

// HasChainData returns a boolean if a field has been set.
func (o *TransferPrivate200ResponseData) HasChainData() bool {
	if o != nil && !IsNil(o.ChainData) {
		return true
	}

	return false
}

// SetChainData gets a reference to the given TransferPrivate200ResponseDataChainData and assigns it to the ChainData field.
func (o *TransferPrivate200ResponseData) SetChainData(v TransferPrivate200ResponseDataChainData) {
	o.ChainData = &v
}

func (o TransferPrivate200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransferPrivate200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Chain) {
		toSerialize["chain"] = o.Chain
	}
	if !IsNil(o.Curve) {
		toSerialize["curve"] = o.Curve
	}
	if !IsNil(o.StealthAddress) {
		toSerialize["stealthAddress"] = o.StealthAddress
	}
	if !IsNil(o.EphemeralPublicKey) {
		toSerialize["ephemeralPublicKey"] = o.EphemeralPublicKey
	}
	if !IsNil(o.ViewTag) {
		toSerialize["viewTag"] = o.ViewTag
	}
	if !IsNil(o.Commitment) {
		toSerialize["commitment"] = o.Commitment
	}
	if !IsNil(o.BlindingFactor) {
		toSerialize["blindingFactor"] = o.BlindingFactor
	}
	if !IsNil(o.ViewingKeyHash) {
		toSerialize["viewingKeyHash"] = o.ViewingKeyHash
	}
	if !IsNil(o.SharedSecret) {
		toSerialize["sharedSecret"] = o.SharedSecret
	}
	if !IsNil(o.ChainData) {
		toSerialize["chainData"] = o.ChainData
	}
	return toSerialize, nil
}

type NullableTransferPrivate200ResponseData struct {
	value *TransferPrivate200ResponseData
	isSet bool
}

func (v NullableTransferPrivate200ResponseData) Get() *TransferPrivate200ResponseData {
	return v.value
}

func (v *NullableTransferPrivate200ResponseData) Set(val *TransferPrivate200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableTransferPrivate200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableTransferPrivate200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransferPrivate200ResponseData(val *TransferPrivate200ResponseData) *NullableTransferPrivate200ResponseData {
	return &NullableTransferPrivate200ResponseData{value: val, isSet: true}
}

func (v NullableTransferPrivate200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransferPrivate200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


