/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
)

// checks if the ProofsFulfillmentGenerate200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProofsFulfillmentGenerate200ResponseData{}

// ProofsFulfillmentGenerate200ResponseData struct for ProofsFulfillmentGenerate200ResponseData
type ProofsFulfillmentGenerate200ResponseData struct {
	Proof *ProofsFulfillmentGenerate200ResponseDataProof `json:"proof,omitempty"`
	PublicInputs []string `json:"publicInputs,omitempty"`
}

// NewProofsFulfillmentGenerate200ResponseData instantiates a new ProofsFulfillmentGenerate200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProofsFulfillmentGenerate200ResponseData() *ProofsFulfillmentGenerate200ResponseData {
	this := ProofsFulfillmentGenerate200ResponseData{}
	return &this
}

// NewProofsFulfillmentGenerate200ResponseDataWithDefaults instantiates a new ProofsFulfillmentGenerate200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProofsFulfillmentGenerate200ResponseDataWithDefaults() *ProofsFulfillmentGenerate200ResponseData {
	this := ProofsFulfillmentGenerate200ResponseData{}
	return &this
}

// GetProof returns the Proof field value if set, zero value otherwise.
func (o *ProofsFulfillmentGenerate200ResponseData) GetProof() ProofsFulfillmentGenerate200ResponseDataProof {
	if o == nil || IsNil(o.Proof) {
		var ret ProofsFulfillmentGenerate200ResponseDataProof
		return ret
	}
	return *o.Proof
}

// GetProofOk returns a tuple with the Proof field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProofsFulfillmentGenerate200ResponseData) GetProofOk() (*ProofsFulfillmentGenerate200ResponseDataProof, bool) {
	if o == nil || IsNil(o.Proof) {
		return nil, false
	}
	return o.Proof, true
}

// HasProof returns a boolean if a field has been set.
func (o *ProofsFulfillmentGenerate200ResponseData) HasProof() bool {
	if o != nil && !IsNil(o.Proof) {
		return true
	}

	return false
}

// SetProof gets a reference to the given ProofsFulfillmentGenerate200ResponseDataProof and assigns it to the Proof field.
func (o *ProofsFulfillmentGenerate200ResponseData) SetProof(v ProofsFulfillmentGenerate200ResponseDataProof) {
	o.Proof = &v
}

// GetPublicInputs returns the PublicInputs field value if set, zero value otherwise.
func (o *ProofsFulfillmentGenerate200ResponseData) GetPublicInputs() []string {
	if o == nil || IsNil(o.PublicInputs) {
		var ret []string
		return ret
	}
	return o.PublicInputs
}

// GetPublicInputsOk returns a tuple with the PublicInputs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProofsFulfillmentGenerate200ResponseData) GetPublicInputsOk() ([]string, bool) {
	if o == nil || IsNil(o.PublicInputs) {
		return nil, false
	}
	return o.PublicInputs, true
}

// HasPublicInputs returns a boolean if a field has been set.
func (o *ProofsFulfillmentGenerate200ResponseData) HasPublicInputs() bool {
	if o != nil && !IsNil(o.PublicInputs) {
		return true
	}

	return false
}

// SetPublicInputs gets a reference to the given []string and assigns it to the PublicInputs field.
func (o *ProofsFulfillmentGenerate200ResponseData) SetPublicInputs(v []string) {
	o.PublicInputs = v
}

func (o ProofsFulfillmentGenerate200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProofsFulfillmentGenerate200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Proof) {
		toSerialize["proof"] = o.Proof
	}
	if !IsNil(o.PublicInputs) {
		toSerialize["publicInputs"] = o.PublicInputs
	}
	return toSerialize, nil
}

type NullableProofsFulfillmentGenerate200ResponseData struct {
	value *ProofsFulfillmentGenerate200ResponseData
	isSet bool
}

func (v NullableProofsFulfillmentGenerate200ResponseData) Get() *ProofsFulfillmentGenerate200ResponseData {
	return v.value
}

func (v *NullableProofsFulfillmentGenerate200ResponseData) Set(val *ProofsFulfillmentGenerate200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableProofsFulfillmentGenerate200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableProofsFulfillmentGenerate200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProofsFulfillmentGenerate200ResponseData(val *ProofsFulfillmentGenerate200ResponseData) *NullableProofsFulfillmentGenerate200ResponseData {
	return &NullableProofsFulfillmentGenerate200ResponseData{value: val, isSet: true}
}

func (v NullableProofsFulfillmentGenerate200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProofsFulfillmentGenerate200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


