/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
)

// checks if the BackendsCompare200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BackendsCompare200ResponseData{}

// BackendsCompare200ResponseData struct for BackendsCompare200ResponseData
type BackendsCompare200ResponseData struct {
	Operation *string `json:"operation,omitempty"`
	Chain *string `json:"chain,omitempty"`
	Comparisons []BackendsCompare200ResponseDataComparisonsInner `json:"comparisons,omitempty"`
	Recommendation *BackendsCompare200ResponseDataRecommendation `json:"recommendation,omitempty"`
}

// NewBackendsCompare200ResponseData instantiates a new BackendsCompare200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBackendsCompare200ResponseData() *BackendsCompare200ResponseData {
	this := BackendsCompare200ResponseData{}
	return &this
}

// NewBackendsCompare200ResponseDataWithDefaults instantiates a new BackendsCompare200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBackendsCompare200ResponseDataWithDefaults() *BackendsCompare200ResponseData {
	this := BackendsCompare200ResponseData{}
	return &this
}

// GetOperation returns the Operation field value if set, zero value otherwise.
func (o *BackendsCompare200ResponseData) GetOperation() string {
	if o == nil || IsNil(o.Operation) {
		var ret string
		return ret
	}
	return *o.Operation
}

// GetOperationOk returns a tuple with the Operation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackendsCompare200ResponseData) GetOperationOk() (*string, bool) {
	if o == nil || IsNil(o.Operation) {
		return nil, false
	}
	return o.Operation, true
}

// HasOperation returns a boolean if a field has been set.
func (o *BackendsCompare200ResponseData) HasOperation() bool {
	if o != nil && !IsNil(o.Operation) {
		return true
	}

	return false
}

// SetOperation gets a reference to the given string and assigns it to the Operation field.
func (o *BackendsCompare200ResponseData) SetOperation(v string) {
	o.Operation = &v
}

// GetChain returns the Chain field value if set, zero value otherwise.
func (o *BackendsCompare200ResponseData) GetChain() string {
	if o == nil || IsNil(o.Chain) {
		var ret string
		return ret
	}
	return *o.Chain
}

// GetChainOk returns a tuple with the Chain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackendsCompare200ResponseData) GetChainOk() (*string, bool) {
	if o == nil || IsNil(o.Chain) {
		return nil, false
	}
	return o.Chain, true
}

// HasChain returns a boolean if a field has been set.
func (o *BackendsCompare200ResponseData) HasChain() bool {
	if o != nil && !IsNil(o.Chain) {
		return true
	}

	return false
}

// SetChain gets a reference to the given string and assigns it to the Chain field.
func (o *BackendsCompare200ResponseData) SetChain(v string) {
	o.Chain = &v
}

// GetComparisons returns the Comparisons field value if set, zero value otherwise.
func (o *BackendsCompare200ResponseData) GetComparisons() []BackendsCompare200ResponseDataComparisonsInner {
	if o == nil || IsNil(o.Comparisons) {
		var ret []BackendsCompare200ResponseDataComparisonsInner
		return ret
	}
	return o.Comparisons
}

// GetComparisonsOk returns a tuple with the Comparisons field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackendsCompare200ResponseData) GetComparisonsOk() ([]BackendsCompare200ResponseDataComparisonsInner, bool) {
	if o == nil || IsNil(o.Comparisons) {
		return nil, false
	}
	return o.Comparisons, true
}

// HasComparisons returns a boolean if a field has been set.
func (o *BackendsCompare200ResponseData) HasComparisons() bool {
	if o != nil && !IsNil(o.Comparisons) {
		return true
	}

	return false
}

// SetComparisons gets a reference to the given []BackendsCompare200ResponseDataComparisonsInner and assigns it to the Comparisons field.
func (o *BackendsCompare200ResponseData) SetComparisons(v []BackendsCompare200ResponseDataComparisonsInner) {
	o.Comparisons = v
}

// GetRecommendation returns the Recommendation field value if set, zero value otherwise.
func (o *BackendsCompare200ResponseData) GetRecommendation() BackendsCompare200ResponseDataRecommendation {
	if o == nil || IsNil(o.Recommendation) {
		var ret BackendsCompare200ResponseDataRecommendation
		return ret
	}
	return *o.Recommendation
}

// GetRecommendationOk returns a tuple with the Recommendation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackendsCompare200ResponseData) GetRecommendationOk() (*BackendsCompare200ResponseDataRecommendation, bool) {
	if o == nil || IsNil(o.Recommendation) {
		return nil, false
	}
	return o.Recommendation, true
}

// HasRecommendation returns a boolean if a field has been set.
func (o *BackendsCompare200ResponseData) HasRecommendation() bool {
	if o != nil && !IsNil(o.Recommendation) {
		return true
	}

	return false
}

// SetRecommendation gets a reference to the given BackendsCompare200ResponseDataRecommendation and assigns it to the Recommendation field.
func (o *BackendsCompare200ResponseData) SetRecommendation(v BackendsCompare200ResponseDataRecommendation) {
	o.Recommendation = &v
}

func (o BackendsCompare200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BackendsCompare200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Operation) {
		toSerialize["operation"] = o.Operation
	}
	if !IsNil(o.Chain) {
		toSerialize["chain"] = o.Chain
	}
	if !IsNil(o.Comparisons) {
		toSerialize["comparisons"] = o.Comparisons
	}
	if !IsNil(o.Recommendation) {
		toSerialize["recommendation"] = o.Recommendation
	}
	return toSerialize, nil
}

type NullableBackendsCompare200ResponseData struct {
	value *BackendsCompare200ResponseData
	isSet bool
}

func (v NullableBackendsCompare200ResponseData) Get() *BackendsCompare200ResponseData {
	return v.value
}

func (v *NullableBackendsCompare200ResponseData) Set(val *BackendsCompare200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableBackendsCompare200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableBackendsCompare200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBackendsCompare200ResponseData(val *BackendsCompare200ResponseData) *NullableBackendsCompare200ResponseData {
	return &NullableBackendsCompare200ResponseData{value: val, isSet: true}
}

func (v NullableBackendsCompare200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBackendsCompare200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


