/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
)

// checks if the ProofsRangeGenerate200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProofsRangeGenerate200ResponseData{}

// ProofsRangeGenerate200ResponseData struct for ProofsRangeGenerate200ResponseData
type ProofsRangeGenerate200ResponseData struct {
	Proof *ProofsRangeGenerate200ResponseDataProof `json:"proof,omitempty"`
	// Pedersen commitment hex
	Commitment *string `json:"commitment,omitempty"`
	Metadata *ProofsRangeGenerate200ResponseDataMetadata `json:"metadata,omitempty"`
}

// NewProofsRangeGenerate200ResponseData instantiates a new ProofsRangeGenerate200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProofsRangeGenerate200ResponseData() *ProofsRangeGenerate200ResponseData {
	this := ProofsRangeGenerate200ResponseData{}
	return &this
}

// NewProofsRangeGenerate200ResponseDataWithDefaults instantiates a new ProofsRangeGenerate200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProofsRangeGenerate200ResponseDataWithDefaults() *ProofsRangeGenerate200ResponseData {
	this := ProofsRangeGenerate200ResponseData{}
	return &this
}

// GetProof returns the Proof field value if set, zero value otherwise.
func (o *ProofsRangeGenerate200ResponseData) GetProof() ProofsRangeGenerate200ResponseDataProof {
	if o == nil || IsNil(o.Proof) {
		var ret ProofsRangeGenerate200ResponseDataProof
		return ret
	}
	return *o.Proof
}

// GetProofOk returns a tuple with the Proof field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProofsRangeGenerate200ResponseData) GetProofOk() (*ProofsRangeGenerate200ResponseDataProof, bool) {
	if o == nil || IsNil(o.Proof) {
		return nil, false
	}
	return o.Proof, true
}

// HasProof returns a boolean if a field has been set.
func (o *ProofsRangeGenerate200ResponseData) HasProof() bool {
	if o != nil && !IsNil(o.Proof) {
		return true
	}

	return false
}

// SetProof gets a reference to the given ProofsRangeGenerate200ResponseDataProof and assigns it to the Proof field.
func (o *ProofsRangeGenerate200ResponseData) SetProof(v ProofsRangeGenerate200ResponseDataProof) {
	o.Proof = &v
}

// GetCommitment returns the Commitment field value if set, zero value otherwise.
func (o *ProofsRangeGenerate200ResponseData) GetCommitment() string {
	if o == nil || IsNil(o.Commitment) {
		var ret string
		return ret
	}
	return *o.Commitment
}

// GetCommitmentOk returns a tuple with the Commitment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProofsRangeGenerate200ResponseData) GetCommitmentOk() (*string, bool) {
	if o == nil || IsNil(o.Commitment) {
		return nil, false
	}
	return o.Commitment, true
}

// HasCommitment returns a boolean if a field has been set.
func (o *ProofsRangeGenerate200ResponseData) HasCommitment() bool {
	if o != nil && !IsNil(o.Commitment) {
		return true
	}

	return false
}

// SetCommitment gets a reference to the given string and assigns it to the Commitment field.
func (o *ProofsRangeGenerate200ResponseData) SetCommitment(v string) {
	o.Commitment = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *ProofsRangeGenerate200ResponseData) GetMetadata() ProofsRangeGenerate200ResponseDataMetadata {
	if o == nil || IsNil(o.Metadata) {
		var ret ProofsRangeGenerate200ResponseDataMetadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProofsRangeGenerate200ResponseData) GetMetadataOk() (*ProofsRangeGenerate200ResponseDataMetadata, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *ProofsRangeGenerate200ResponseData) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given ProofsRangeGenerate200ResponseDataMetadata and assigns it to the Metadata field.
func (o *ProofsRangeGenerate200ResponseData) SetMetadata(v ProofsRangeGenerate200ResponseDataMetadata) {
	o.Metadata = &v
}

func (o ProofsRangeGenerate200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProofsRangeGenerate200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Proof) {
		toSerialize["proof"] = o.Proof
	}
	if !IsNil(o.Commitment) {
		toSerialize["commitment"] = o.Commitment
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

type NullableProofsRangeGenerate200ResponseData struct {
	value *ProofsRangeGenerate200ResponseData
	isSet bool
}

func (v NullableProofsRangeGenerate200ResponseData) Get() *ProofsRangeGenerate200ResponseData {
	return v.value
}

func (v *NullableProofsRangeGenerate200ResponseData) Set(val *ProofsRangeGenerate200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableProofsRangeGenerate200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableProofsRangeGenerate200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProofsRangeGenerate200ResponseData(val *ProofsRangeGenerate200ResponseData) *NullableProofsRangeGenerate200ResponseData {
	return &NullableProofsRangeGenerate200ResponseData{value: val, isSet: true}
}

func (v NullableProofsRangeGenerate200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProofsRangeGenerate200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


