/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
)

// checks if the ViewingKeyDecrypt200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ViewingKeyDecrypt200ResponseData{}

// ViewingKeyDecrypt200ResponseData struct for ViewingKeyDecrypt200ResponseData
type ViewingKeyDecrypt200ResponseData struct {
	Sender *string `json:"sender,omitempty"`
	Recipient *string `json:"recipient,omitempty"`
	Amount *string `json:"amount,omitempty"`
	Timestamp *int32 `json:"timestamp,omitempty"`
}

// NewViewingKeyDecrypt200ResponseData instantiates a new ViewingKeyDecrypt200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewViewingKeyDecrypt200ResponseData() *ViewingKeyDecrypt200ResponseData {
	this := ViewingKeyDecrypt200ResponseData{}
	return &this
}

// NewViewingKeyDecrypt200ResponseDataWithDefaults instantiates a new ViewingKeyDecrypt200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewViewingKeyDecrypt200ResponseDataWithDefaults() *ViewingKeyDecrypt200ResponseData {
	this := ViewingKeyDecrypt200ResponseData{}
	return &this
}

// GetSender returns the Sender field value if set, zero value otherwise.
func (o *ViewingKeyDecrypt200ResponseData) GetSender() string {
	if o == nil || IsNil(o.Sender) {
		var ret string
		return ret
	}
	return *o.Sender
}

// GetSenderOk returns a tuple with the Sender field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewingKeyDecrypt200ResponseData) GetSenderOk() (*string, bool) {
	if o == nil || IsNil(o.Sender) {
		return nil, false
	}
	return o.Sender, true
}

// HasSender returns a boolean if a field has been set.
func (o *ViewingKeyDecrypt200ResponseData) HasSender() bool {
	if o != nil && !IsNil(o.Sender) {
		return true
	}

	return false
}

// SetSender gets a reference to the given string and assigns it to the Sender field.
func (o *ViewingKeyDecrypt200ResponseData) SetSender(v string) {
	o.Sender = &v
}

// GetRecipient returns the Recipient field value if set, zero value otherwise.
func (o *ViewingKeyDecrypt200ResponseData) GetRecipient() string {
	if o == nil || IsNil(o.Recipient) {
		var ret string
		return ret
	}
	return *o.Recipient
}

// GetRecipientOk returns a tuple with the Recipient field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewingKeyDecrypt200ResponseData) GetRecipientOk() (*string, bool) {
	if o == nil || IsNil(o.Recipient) {
		return nil, false
	}
	return o.Recipient, true
}

// HasRecipient returns a boolean if a field has been set.
func (o *ViewingKeyDecrypt200ResponseData) HasRecipient() bool {
	if o != nil && !IsNil(o.Recipient) {
		return true
	}

	return false
}

// SetRecipient gets a reference to the given string and assigns it to the Recipient field.
func (o *ViewingKeyDecrypt200ResponseData) SetRecipient(v string) {
	o.Recipient = &v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *ViewingKeyDecrypt200ResponseData) GetAmount() string {
	if o == nil || IsNil(o.Amount) {
		var ret string
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewingKeyDecrypt200ResponseData) GetAmountOk() (*string, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *ViewingKeyDecrypt200ResponseData) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given string and assigns it to the Amount field.
func (o *ViewingKeyDecrypt200ResponseData) SetAmount(v string) {
	o.Amount = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *ViewingKeyDecrypt200ResponseData) GetTimestamp() int32 {
	if o == nil || IsNil(o.Timestamp) {
		var ret int32
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewingKeyDecrypt200ResponseData) GetTimestampOk() (*int32, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *ViewingKeyDecrypt200ResponseData) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given int32 and assigns it to the Timestamp field.
func (o *ViewingKeyDecrypt200ResponseData) SetTimestamp(v int32) {
	o.Timestamp = &v
}

func (o ViewingKeyDecrypt200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ViewingKeyDecrypt200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Sender) {
		toSerialize["sender"] = o.Sender
	}
	if !IsNil(o.Recipient) {
		toSerialize["recipient"] = o.Recipient
	}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	return toSerialize, nil
}

type NullableViewingKeyDecrypt200ResponseData struct {
	value *ViewingKeyDecrypt200ResponseData
	isSet bool
}

func (v NullableViewingKeyDecrypt200ResponseData) Get() *ViewingKeyDecrypt200ResponseData {
	return v.value
}

func (v *NullableViewingKeyDecrypt200ResponseData) Set(val *ViewingKeyDecrypt200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableViewingKeyDecrypt200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableViewingKeyDecrypt200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableViewingKeyDecrypt200ResponseData(val *ViewingKeyDecrypt200ResponseData) *NullableViewingKeyDecrypt200ResponseData {
	return &NullableViewingKeyDecrypt200ResponseData{value: val, isSet: true}
}

func (v NullableViewingKeyDecrypt200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableViewingKeyDecrypt200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


