/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ComplianceDiscloseRequestAuditorVerification type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComplianceDiscloseRequestAuditorVerification{}

// ComplianceDiscloseRequestAuditorVerification struct for ComplianceDiscloseRequestAuditorVerification
type ComplianceDiscloseRequestAuditorVerification struct {
	AuditorKeyHash string `json:"auditorKeyHash" validate:"regexp=^0x[0-9a-fA-F]+$"`
	Nonce string `json:"nonce" validate:"regexp=^0x[0-9a-fA-F]+$"`
}

type _ComplianceDiscloseRequestAuditorVerification ComplianceDiscloseRequestAuditorVerification

// NewComplianceDiscloseRequestAuditorVerification instantiates a new ComplianceDiscloseRequestAuditorVerification object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComplianceDiscloseRequestAuditorVerification(auditorKeyHash string, nonce string) *ComplianceDiscloseRequestAuditorVerification {
	this := ComplianceDiscloseRequestAuditorVerification{}
	this.AuditorKeyHash = auditorKeyHash
	this.Nonce = nonce
	return &this
}

// NewComplianceDiscloseRequestAuditorVerificationWithDefaults instantiates a new ComplianceDiscloseRequestAuditorVerification object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComplianceDiscloseRequestAuditorVerificationWithDefaults() *ComplianceDiscloseRequestAuditorVerification {
	this := ComplianceDiscloseRequestAuditorVerification{}
	return &this
}

// GetAuditorKeyHash returns the AuditorKeyHash field value
func (o *ComplianceDiscloseRequestAuditorVerification) GetAuditorKeyHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuditorKeyHash
}

// GetAuditorKeyHashOk returns a tuple with the AuditorKeyHash field value
// and a boolean to check if the value has been set.
func (o *ComplianceDiscloseRequestAuditorVerification) GetAuditorKeyHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuditorKeyHash, true
}

// SetAuditorKeyHash sets field value
func (o *ComplianceDiscloseRequestAuditorVerification) SetAuditorKeyHash(v string) {
	o.AuditorKeyHash = v
}

// GetNonce returns the Nonce field value
func (o *ComplianceDiscloseRequestAuditorVerification) GetNonce() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Nonce
}

// GetNonceOk returns a tuple with the Nonce field value
// and a boolean to check if the value has been set.
func (o *ComplianceDiscloseRequestAuditorVerification) GetNonceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Nonce, true
}

// SetNonce sets field value
func (o *ComplianceDiscloseRequestAuditorVerification) SetNonce(v string) {
	o.Nonce = v
}

func (o ComplianceDiscloseRequestAuditorVerification) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComplianceDiscloseRequestAuditorVerification) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["auditorKeyHash"] = o.AuditorKeyHash
	toSerialize["nonce"] = o.Nonce
	return toSerialize, nil
}

func (o *ComplianceDiscloseRequestAuditorVerification) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"auditorKeyHash",
		"nonce",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varComplianceDiscloseRequestAuditorVerification := _ComplianceDiscloseRequestAuditorVerification{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varComplianceDiscloseRequestAuditorVerification)

	if err != nil {
		return err
	}

	*o = ComplianceDiscloseRequestAuditorVerification(varComplianceDiscloseRequestAuditorVerification)

	return err
}

type NullableComplianceDiscloseRequestAuditorVerification struct {
	value *ComplianceDiscloseRequestAuditorVerification
	isSet bool
}

func (v NullableComplianceDiscloseRequestAuditorVerification) Get() *ComplianceDiscloseRequestAuditorVerification {
	return v.value
}

func (v *NullableComplianceDiscloseRequestAuditorVerification) Set(val *ComplianceDiscloseRequestAuditorVerification) {
	v.value = val
	v.isSet = true
}

func (v NullableComplianceDiscloseRequestAuditorVerification) IsSet() bool {
	return v.isSet
}

func (v *NullableComplianceDiscloseRequestAuditorVerification) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComplianceDiscloseRequestAuditorVerification(val *ComplianceDiscloseRequestAuditorVerification) *NullableComplianceDiscloseRequestAuditorVerification {
	return &NullableComplianceDiscloseRequestAuditorVerification{value: val, isSet: true}
}

func (v NullableComplianceDiscloseRequestAuditorVerification) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComplianceDiscloseRequestAuditorVerification) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


