/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
)

// checks if the BackendsSelect200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BackendsSelect200ResponseData{}

// BackendsSelect200ResponseData struct for BackendsSelect200ResponseData
type BackendsSelect200ResponseData struct {
	KeyId *string `json:"keyId,omitempty"`
	PreferredBackend *string `json:"preferredBackend,omitempty"`
}

// NewBackendsSelect200ResponseData instantiates a new BackendsSelect200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBackendsSelect200ResponseData() *BackendsSelect200ResponseData {
	this := BackendsSelect200ResponseData{}
	return &this
}

// NewBackendsSelect200ResponseDataWithDefaults instantiates a new BackendsSelect200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBackendsSelect200ResponseDataWithDefaults() *BackendsSelect200ResponseData {
	this := BackendsSelect200ResponseData{}
	return &this
}

// GetKeyId returns the KeyId field value if set, zero value otherwise.
func (o *BackendsSelect200ResponseData) GetKeyId() string {
	if o == nil || IsNil(o.KeyId) {
		var ret string
		return ret
	}
	return *o.KeyId
}

// GetKeyIdOk returns a tuple with the KeyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackendsSelect200ResponseData) GetKeyIdOk() (*string, bool) {
	if o == nil || IsNil(o.KeyId) {
		return nil, false
	}
	return o.KeyId, true
}

// HasKeyId returns a boolean if a field has been set.
func (o *BackendsSelect200ResponseData) HasKeyId() bool {
	if o != nil && !IsNil(o.KeyId) {
		return true
	}

	return false
}

// SetKeyId gets a reference to the given string and assigns it to the KeyId field.
func (o *BackendsSelect200ResponseData) SetKeyId(v string) {
	o.KeyId = &v
}

// GetPreferredBackend returns the PreferredBackend field value if set, zero value otherwise.
func (o *BackendsSelect200ResponseData) GetPreferredBackend() string {
	if o == nil || IsNil(o.PreferredBackend) {
		var ret string
		return ret
	}
	return *o.PreferredBackend
}

// GetPreferredBackendOk returns a tuple with the PreferredBackend field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackendsSelect200ResponseData) GetPreferredBackendOk() (*string, bool) {
	if o == nil || IsNil(o.PreferredBackend) {
		return nil, false
	}
	return o.PreferredBackend, true
}

// HasPreferredBackend returns a boolean if a field has been set.
func (o *BackendsSelect200ResponseData) HasPreferredBackend() bool {
	if o != nil && !IsNil(o.PreferredBackend) {
		return true
	}

	return false
}

// SetPreferredBackend gets a reference to the given string and assigns it to the PreferredBackend field.
func (o *BackendsSelect200ResponseData) SetPreferredBackend(v string) {
	o.PreferredBackend = &v
}

func (o BackendsSelect200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BackendsSelect200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.KeyId) {
		toSerialize["keyId"] = o.KeyId
	}
	if !IsNil(o.PreferredBackend) {
		toSerialize["preferredBackend"] = o.PreferredBackend
	}
	return toSerialize, nil
}

type NullableBackendsSelect200ResponseData struct {
	value *BackendsSelect200ResponseData
	isSet bool
}

func (v NullableBackendsSelect200ResponseData) Get() *BackendsSelect200ResponseData {
	return v.value
}

func (v *NullableBackendsSelect200ResponseData) Set(val *BackendsSelect200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableBackendsSelect200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableBackendsSelect200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBackendsSelect200ResponseData(val *BackendsSelect200ResponseData) *NullableBackendsSelect200ResponseData {
	return &NullableBackendsSelect200ResponseData{value: val, isSet: true}
}

func (v NullableBackendsSelect200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBackendsSelect200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


