/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
)

// checks if the TransferPrivate422Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransferPrivate422Response{}

// TransferPrivate422Response struct for TransferPrivate422Response
type TransferPrivate422Response struct {
	Success *bool `json:"success,omitempty"`
	Error *TransferPrivate422ResponseError `json:"error,omitempty"`
}

// NewTransferPrivate422Response instantiates a new TransferPrivate422Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransferPrivate422Response() *TransferPrivate422Response {
	this := TransferPrivate422Response{}
	return &this
}

// NewTransferPrivate422ResponseWithDefaults instantiates a new TransferPrivate422Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransferPrivate422ResponseWithDefaults() *TransferPrivate422Response {
	this := TransferPrivate422Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *TransferPrivate422Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransferPrivate422Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *TransferPrivate422Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *TransferPrivate422Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *TransferPrivate422Response) GetError() TransferPrivate422ResponseError {
	if o == nil || IsNil(o.Error) {
		var ret TransferPrivate422ResponseError
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransferPrivate422Response) GetErrorOk() (*TransferPrivate422ResponseError, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *TransferPrivate422Response) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given TransferPrivate422ResponseError and assigns it to the Error field.
func (o *TransferPrivate422Response) SetError(v TransferPrivate422ResponseError) {
	o.Error = &v
}

func (o TransferPrivate422Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransferPrivate422Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableTransferPrivate422Response struct {
	value *TransferPrivate422Response
	isSet bool
}

func (v NullableTransferPrivate422Response) Get() *TransferPrivate422Response {
	return v.value
}

func (v *NullableTransferPrivate422Response) Set(val *TransferPrivate422Response) {
	v.value = val
	v.isSet = true
}

func (v NullableTransferPrivate422Response) IsSet() bool {
	return v.isSet
}

func (v *NullableTransferPrivate422Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransferPrivate422Response(val *TransferPrivate422Response) *NullableTransferPrivate422Response {
	return &NullableTransferPrivate422Response{value: val, isSet: true}
}

func (v NullableTransferPrivate422Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransferPrivate422Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


