/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CommitmentVerifyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommitmentVerifyRequest{}

// CommitmentVerifyRequest struct for CommitmentVerifyRequest
type CommitmentVerifyRequest struct {
	Commitment string `json:"commitment" validate:"regexp=^0x[0-9a-fA-F]+$"`
	Value string `json:"value" validate:"regexp=^[0-9]+$"`
	// 0x-prefixed 32-byte hex string
	BlindingFactor string `json:"blindingFactor" validate:"regexp=^0x[0-9a-fA-F]{64}$"`
}

type _CommitmentVerifyRequest CommitmentVerifyRequest

// NewCommitmentVerifyRequest instantiates a new CommitmentVerifyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommitmentVerifyRequest(commitment string, value string, blindingFactor string) *CommitmentVerifyRequest {
	this := CommitmentVerifyRequest{}
	this.Commitment = commitment
	this.Value = value
	this.BlindingFactor = blindingFactor
	return &this
}

// NewCommitmentVerifyRequestWithDefaults instantiates a new CommitmentVerifyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommitmentVerifyRequestWithDefaults() *CommitmentVerifyRequest {
	this := CommitmentVerifyRequest{}
	return &this
}

// GetCommitment returns the Commitment field value
func (o *CommitmentVerifyRequest) GetCommitment() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Commitment
}

// GetCommitmentOk returns a tuple with the Commitment field value
// and a boolean to check if the value has been set.
func (o *CommitmentVerifyRequest) GetCommitmentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Commitment, true
}

// SetCommitment sets field value
func (o *CommitmentVerifyRequest) SetCommitment(v string) {
	o.Commitment = v
}

// GetValue returns the Value field value
func (o *CommitmentVerifyRequest) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *CommitmentVerifyRequest) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *CommitmentVerifyRequest) SetValue(v string) {
	o.Value = v
}

// GetBlindingFactor returns the BlindingFactor field value
func (o *CommitmentVerifyRequest) GetBlindingFactor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BlindingFactor
}

// GetBlindingFactorOk returns a tuple with the BlindingFactor field value
// and a boolean to check if the value has been set.
func (o *CommitmentVerifyRequest) GetBlindingFactorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BlindingFactor, true
}

// SetBlindingFactor sets field value
func (o *CommitmentVerifyRequest) SetBlindingFactor(v string) {
	o.BlindingFactor = v
}

func (o CommitmentVerifyRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommitmentVerifyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["commitment"] = o.Commitment
	toSerialize["value"] = o.Value
	toSerialize["blindingFactor"] = o.BlindingFactor
	return toSerialize, nil
}

func (o *CommitmentVerifyRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"commitment",
		"value",
		"blindingFactor",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCommitmentVerifyRequest := _CommitmentVerifyRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCommitmentVerifyRequest)

	if err != nil {
		return err
	}

	*o = CommitmentVerifyRequest(varCommitmentVerifyRequest)

	return err
}

type NullableCommitmentVerifyRequest struct {
	value *CommitmentVerifyRequest
	isSet bool
}

func (v NullableCommitmentVerifyRequest) Get() *CommitmentVerifyRequest {
	return v.value
}

func (v *NullableCommitmentVerifyRequest) Set(val *CommitmentVerifyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCommitmentVerifyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCommitmentVerifyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommitmentVerifyRequest(val *CommitmentVerifyRequest) *NullableCommitmentVerifyRequest {
	return &NullableCommitmentVerifyRequest{value: val, isSet: true}
}

func (v NullableCommitmentVerifyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommitmentVerifyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


