/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProofsFundingGenerateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProofsFundingGenerateRequest{}

// ProofsFundingGenerateRequest struct for ProofsFundingGenerateRequest
type ProofsFundingGenerateRequest struct {
	// User balance (private)
	Balance string `json:"balance" validate:"regexp=^[0-9]+$"`
	// Minimum required amount (public)
	MinimumRequired string `json:"minimumRequired" validate:"regexp=^[0-9]+$"`
	// 0x-prefixed 32-byte hex string
	BlindingFactor string `json:"blindingFactor" validate:"regexp=^0x[0-9a-fA-F]{64}$"`
	// Asset identifier (e.g., SOL)
	AssetId string `json:"assetId"`
	// User address for ownership proof
	UserAddress string `json:"userAddress"`
	// Signature proving address ownership
	OwnershipSignature string `json:"ownershipSignature" validate:"regexp=^0x[0-9a-fA-F]+$"`
}

type _ProofsFundingGenerateRequest ProofsFundingGenerateRequest

// NewProofsFundingGenerateRequest instantiates a new ProofsFundingGenerateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProofsFundingGenerateRequest(balance string, minimumRequired string, blindingFactor string, assetId string, userAddress string, ownershipSignature string) *ProofsFundingGenerateRequest {
	this := ProofsFundingGenerateRequest{}
	this.Balance = balance
	this.MinimumRequired = minimumRequired
	this.BlindingFactor = blindingFactor
	this.AssetId = assetId
	this.UserAddress = userAddress
	this.OwnershipSignature = ownershipSignature
	return &this
}

// NewProofsFundingGenerateRequestWithDefaults instantiates a new ProofsFundingGenerateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProofsFundingGenerateRequestWithDefaults() *ProofsFundingGenerateRequest {
	this := ProofsFundingGenerateRequest{}
	return &this
}

// GetBalance returns the Balance field value
func (o *ProofsFundingGenerateRequest) GetBalance() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Balance
}

// GetBalanceOk returns a tuple with the Balance field value
// and a boolean to check if the value has been set.
func (o *ProofsFundingGenerateRequest) GetBalanceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Balance, true
}

// SetBalance sets field value
func (o *ProofsFundingGenerateRequest) SetBalance(v string) {
	o.Balance = v
}

// GetMinimumRequired returns the MinimumRequired field value
func (o *ProofsFundingGenerateRequest) GetMinimumRequired() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MinimumRequired
}

// GetMinimumRequiredOk returns a tuple with the MinimumRequired field value
// and a boolean to check if the value has been set.
func (o *ProofsFundingGenerateRequest) GetMinimumRequiredOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MinimumRequired, true
}

// SetMinimumRequired sets field value
func (o *ProofsFundingGenerateRequest) SetMinimumRequired(v string) {
	o.MinimumRequired = v
}

// GetBlindingFactor returns the BlindingFactor field value
func (o *ProofsFundingGenerateRequest) GetBlindingFactor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BlindingFactor
}

// GetBlindingFactorOk returns a tuple with the BlindingFactor field value
// and a boolean to check if the value has been set.
func (o *ProofsFundingGenerateRequest) GetBlindingFactorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BlindingFactor, true
}

// SetBlindingFactor sets field value
func (o *ProofsFundingGenerateRequest) SetBlindingFactor(v string) {
	o.BlindingFactor = v
}

// GetAssetId returns the AssetId field value
func (o *ProofsFundingGenerateRequest) GetAssetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AssetId
}

// GetAssetIdOk returns a tuple with the AssetId field value
// and a boolean to check if the value has been set.
func (o *ProofsFundingGenerateRequest) GetAssetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssetId, true
}

// SetAssetId sets field value
func (o *ProofsFundingGenerateRequest) SetAssetId(v string) {
	o.AssetId = v
}

// GetUserAddress returns the UserAddress field value
func (o *ProofsFundingGenerateRequest) GetUserAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserAddress
}

// GetUserAddressOk returns a tuple with the UserAddress field value
// and a boolean to check if the value has been set.
func (o *ProofsFundingGenerateRequest) GetUserAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserAddress, true
}

// SetUserAddress sets field value
func (o *ProofsFundingGenerateRequest) SetUserAddress(v string) {
	o.UserAddress = v
}

// GetOwnershipSignature returns the OwnershipSignature field value
func (o *ProofsFundingGenerateRequest) GetOwnershipSignature() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OwnershipSignature
}

// GetOwnershipSignatureOk returns a tuple with the OwnershipSignature field value
// and a boolean to check if the value has been set.
func (o *ProofsFundingGenerateRequest) GetOwnershipSignatureOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OwnershipSignature, true
}

// SetOwnershipSignature sets field value
func (o *ProofsFundingGenerateRequest) SetOwnershipSignature(v string) {
	o.OwnershipSignature = v
}

func (o ProofsFundingGenerateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProofsFundingGenerateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["balance"] = o.Balance
	toSerialize["minimumRequired"] = o.MinimumRequired
	toSerialize["blindingFactor"] = o.BlindingFactor
	toSerialize["assetId"] = o.AssetId
	toSerialize["userAddress"] = o.UserAddress
	toSerialize["ownershipSignature"] = o.OwnershipSignature
	return toSerialize, nil
}

func (o *ProofsFundingGenerateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"balance",
		"minimumRequired",
		"blindingFactor",
		"assetId",
		"userAddress",
		"ownershipSignature",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProofsFundingGenerateRequest := _ProofsFundingGenerateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProofsFundingGenerateRequest)

	if err != nil {
		return err
	}

	*o = ProofsFundingGenerateRequest(varProofsFundingGenerateRequest)

	return err
}

type NullableProofsFundingGenerateRequest struct {
	value *ProofsFundingGenerateRequest
	isSet bool
}

func (v NullableProofsFundingGenerateRequest) Get() *ProofsFundingGenerateRequest {
	return v.value
}

func (v *NullableProofsFundingGenerateRequest) Set(val *ProofsFundingGenerateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableProofsFundingGenerateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableProofsFundingGenerateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProofsFundingGenerateRequest(val *ProofsFundingGenerateRequest) *NullableProofsFundingGenerateRequest {
	return &NullableProofsFundingGenerateRequest{value: val, isSet: true}
}

func (v NullableProofsFundingGenerateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProofsFundingGenerateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


