/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
)

// checks if the TransferPrivate422ResponseError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransferPrivate422ResponseError{}

// TransferPrivate422ResponseError struct for TransferPrivate422ResponseError
type TransferPrivate422ResponseError struct {
	Code *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	SupportedChains []string `json:"supportedChains,omitempty"`
}

// NewTransferPrivate422ResponseError instantiates a new TransferPrivate422ResponseError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransferPrivate422ResponseError() *TransferPrivate422ResponseError {
	this := TransferPrivate422ResponseError{}
	return &this
}

// NewTransferPrivate422ResponseErrorWithDefaults instantiates a new TransferPrivate422ResponseError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransferPrivate422ResponseErrorWithDefaults() *TransferPrivate422ResponseError {
	this := TransferPrivate422ResponseError{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *TransferPrivate422ResponseError) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransferPrivate422ResponseError) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *TransferPrivate422ResponseError) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *TransferPrivate422ResponseError) SetCode(v string) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *TransferPrivate422ResponseError) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransferPrivate422ResponseError) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *TransferPrivate422ResponseError) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *TransferPrivate422ResponseError) SetMessage(v string) {
	o.Message = &v
}

// GetSupportedChains returns the SupportedChains field value if set, zero value otherwise.
func (o *TransferPrivate422ResponseError) GetSupportedChains() []string {
	if o == nil || IsNil(o.SupportedChains) {
		var ret []string
		return ret
	}
	return o.SupportedChains
}

// GetSupportedChainsOk returns a tuple with the SupportedChains field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransferPrivate422ResponseError) GetSupportedChainsOk() ([]string, bool) {
	if o == nil || IsNil(o.SupportedChains) {
		return nil, false
	}
	return o.SupportedChains, true
}

// HasSupportedChains returns a boolean if a field has been set.
func (o *TransferPrivate422ResponseError) HasSupportedChains() bool {
	if o != nil && !IsNil(o.SupportedChains) {
		return true
	}

	return false
}

// SetSupportedChains gets a reference to the given []string and assigns it to the SupportedChains field.
func (o *TransferPrivate422ResponseError) SetSupportedChains(v []string) {
	o.SupportedChains = v
}

func (o TransferPrivate422ResponseError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransferPrivate422ResponseError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.SupportedChains) {
		toSerialize["supportedChains"] = o.SupportedChains
	}
	return toSerialize, nil
}

type NullableTransferPrivate422ResponseError struct {
	value *TransferPrivate422ResponseError
	isSet bool
}

func (v NullableTransferPrivate422ResponseError) Get() *TransferPrivate422ResponseError {
	return v.value
}

func (v *NullableTransferPrivate422ResponseError) Set(val *TransferPrivate422ResponseError) {
	v.value = val
	v.isSet = true
}

func (v NullableTransferPrivate422ResponseError) IsSet() bool {
	return v.isSet
}

func (v *NullableTransferPrivate422ResponseError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransferPrivate422ResponseError(val *TransferPrivate422ResponseError) *NullableTransferPrivate422ResponseError {
	return &NullableTransferPrivate422ResponseError{value: val, isSet: true}
}

func (v NullableTransferPrivate422ResponseError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransferPrivate422ResponseError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


