/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BackendsSelectRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BackendsSelectRequest{}

// BackendsSelectRequest struct for BackendsSelectRequest
type BackendsSelectRequest struct {
	// Backend name to prefer
	Backend string `json:"backend"`
}

type _BackendsSelectRequest BackendsSelectRequest

// NewBackendsSelectRequest instantiates a new BackendsSelectRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBackendsSelectRequest(backend string) *BackendsSelectRequest {
	this := BackendsSelectRequest{}
	this.Backend = backend
	return &this
}

// NewBackendsSelectRequestWithDefaults instantiates a new BackendsSelectRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBackendsSelectRequestWithDefaults() *BackendsSelectRequest {
	this := BackendsSelectRequest{}
	return &this
}

// GetBackend returns the Backend field value
func (o *BackendsSelectRequest) GetBackend() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Backend
}

// GetBackendOk returns a tuple with the Backend field value
// and a boolean to check if the value has been set.
func (o *BackendsSelectRequest) GetBackendOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Backend, true
}

// SetBackend sets field value
func (o *BackendsSelectRequest) SetBackend(v string) {
	o.Backend = v
}

func (o BackendsSelectRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BackendsSelectRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["backend"] = o.Backend
	return toSerialize, nil
}

func (o *BackendsSelectRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"backend",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBackendsSelectRequest := _BackendsSelectRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBackendsSelectRequest)

	if err != nil {
		return err
	}

	*o = BackendsSelectRequest(varBackendsSelectRequest)

	return err
}

type NullableBackendsSelectRequest struct {
	value *BackendsSelectRequest
	isSet bool
}

func (v NullableBackendsSelectRequest) Get() *BackendsSelectRequest {
	return v.value
}

func (v *NullableBackendsSelectRequest) Set(val *BackendsSelectRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBackendsSelectRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBackendsSelectRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBackendsSelectRequest(val *BackendsSelectRequest) *NullableBackendsSelectRequest {
	return &NullableBackendsSelectRequest{value: val, isSet: true}
}

func (v NullableBackendsSelectRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBackendsSelectRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


