/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProofsRangeGenerateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProofsRangeGenerateRequest{}

// ProofsRangeGenerateRequest struct for ProofsRangeGenerateRequest
type ProofsRangeGenerateRequest struct {
	// Value to prove (private, not revealed)
	Value string `json:"value" validate:"regexp=^[0-9]+$"`
	// Minimum threshold (public)
	Threshold string `json:"threshold" validate:"regexp=^[0-9]+$"`
	// 0x-prefixed 32-byte hex string
	BlindingFactor string `json:"blindingFactor" validate:"regexp=^0x[0-9a-fA-F]{64}$"`
	// Optional existing Pedersen commitment. If omitted, one is created from value + blindingFactor.
	Commitment *string `json:"commitment,omitempty" validate:"regexp=^0x[0-9a-fA-F]+$"`
}

type _ProofsRangeGenerateRequest ProofsRangeGenerateRequest

// NewProofsRangeGenerateRequest instantiates a new ProofsRangeGenerateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProofsRangeGenerateRequest(value string, threshold string, blindingFactor string) *ProofsRangeGenerateRequest {
	this := ProofsRangeGenerateRequest{}
	this.Value = value
	this.Threshold = threshold
	this.BlindingFactor = blindingFactor
	return &this
}

// NewProofsRangeGenerateRequestWithDefaults instantiates a new ProofsRangeGenerateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProofsRangeGenerateRequestWithDefaults() *ProofsRangeGenerateRequest {
	this := ProofsRangeGenerateRequest{}
	return &this
}

// GetValue returns the Value field value
func (o *ProofsRangeGenerateRequest) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *ProofsRangeGenerateRequest) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *ProofsRangeGenerateRequest) SetValue(v string) {
	o.Value = v
}

// GetThreshold returns the Threshold field value
func (o *ProofsRangeGenerateRequest) GetThreshold() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Threshold
}

// GetThresholdOk returns a tuple with the Threshold field value
// and a boolean to check if the value has been set.
func (o *ProofsRangeGenerateRequest) GetThresholdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Threshold, true
}

// SetThreshold sets field value
func (o *ProofsRangeGenerateRequest) SetThreshold(v string) {
	o.Threshold = v
}

// GetBlindingFactor returns the BlindingFactor field value
func (o *ProofsRangeGenerateRequest) GetBlindingFactor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BlindingFactor
}

// GetBlindingFactorOk returns a tuple with the BlindingFactor field value
// and a boolean to check if the value has been set.
func (o *ProofsRangeGenerateRequest) GetBlindingFactorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BlindingFactor, true
}

// SetBlindingFactor sets field value
func (o *ProofsRangeGenerateRequest) SetBlindingFactor(v string) {
	o.BlindingFactor = v
}

// GetCommitment returns the Commitment field value if set, zero value otherwise.
func (o *ProofsRangeGenerateRequest) GetCommitment() string {
	if o == nil || IsNil(o.Commitment) {
		var ret string
		return ret
	}
	return *o.Commitment
}

// GetCommitmentOk returns a tuple with the Commitment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProofsRangeGenerateRequest) GetCommitmentOk() (*string, bool) {
	if o == nil || IsNil(o.Commitment) {
		return nil, false
	}
	return o.Commitment, true
}

// HasCommitment returns a boolean if a field has been set.
func (o *ProofsRangeGenerateRequest) HasCommitment() bool {
	if o != nil && !IsNil(o.Commitment) {
		return true
	}

	return false
}

// SetCommitment gets a reference to the given string and assigns it to the Commitment field.
func (o *ProofsRangeGenerateRequest) SetCommitment(v string) {
	o.Commitment = &v
}

func (o ProofsRangeGenerateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProofsRangeGenerateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["value"] = o.Value
	toSerialize["threshold"] = o.Threshold
	toSerialize["blindingFactor"] = o.BlindingFactor
	if !IsNil(o.Commitment) {
		toSerialize["commitment"] = o.Commitment
	}
	return toSerialize, nil
}

func (o *ProofsRangeGenerateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"value",
		"threshold",
		"blindingFactor",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProofsRangeGenerateRequest := _ProofsRangeGenerateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProofsRangeGenerateRequest)

	if err != nil {
		return err
	}

	*o = ProofsRangeGenerateRequest(varProofsRangeGenerateRequest)

	return err
}

type NullableProofsRangeGenerateRequest struct {
	value *ProofsRangeGenerateRequest
	isSet bool
}

func (v NullableProofsRangeGenerateRequest) Get() *ProofsRangeGenerateRequest {
	return v.value
}

func (v *NullableProofsRangeGenerateRequest) Set(val *ProofsRangeGenerateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableProofsRangeGenerateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableProofsRangeGenerateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProofsRangeGenerateRequest(val *ProofsRangeGenerateRequest) *NullableProofsRangeGenerateRequest {
	return &NullableProofsRangeGenerateRequest{value: val, isSet: true}
}

func (v NullableProofsRangeGenerateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProofsRangeGenerateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


