/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
)

// checks if the StealthGenerateBatch200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StealthGenerateBatch200ResponseData{}

// StealthGenerateBatch200ResponseData struct for StealthGenerateBatch200ResponseData
type StealthGenerateBatch200ResponseData struct {
	Results []StealthGenerateBatch200ResponseDataResultsInner `json:"results,omitempty"`
	Summary *StealthGenerateBatch200ResponseDataSummary `json:"summary,omitempty"`
}

// NewStealthGenerateBatch200ResponseData instantiates a new StealthGenerateBatch200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStealthGenerateBatch200ResponseData() *StealthGenerateBatch200ResponseData {
	this := StealthGenerateBatch200ResponseData{}
	return &this
}

// NewStealthGenerateBatch200ResponseDataWithDefaults instantiates a new StealthGenerateBatch200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStealthGenerateBatch200ResponseDataWithDefaults() *StealthGenerateBatch200ResponseData {
	this := StealthGenerateBatch200ResponseData{}
	return &this
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *StealthGenerateBatch200ResponseData) GetResults() []StealthGenerateBatch200ResponseDataResultsInner {
	if o == nil || IsNil(o.Results) {
		var ret []StealthGenerateBatch200ResponseDataResultsInner
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StealthGenerateBatch200ResponseData) GetResultsOk() ([]StealthGenerateBatch200ResponseDataResultsInner, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *StealthGenerateBatch200ResponseData) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []StealthGenerateBatch200ResponseDataResultsInner and assigns it to the Results field.
func (o *StealthGenerateBatch200ResponseData) SetResults(v []StealthGenerateBatch200ResponseDataResultsInner) {
	o.Results = v
}

// GetSummary returns the Summary field value if set, zero value otherwise.
func (o *StealthGenerateBatch200ResponseData) GetSummary() StealthGenerateBatch200ResponseDataSummary {
	if o == nil || IsNil(o.Summary) {
		var ret StealthGenerateBatch200ResponseDataSummary
		return ret
	}
	return *o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StealthGenerateBatch200ResponseData) GetSummaryOk() (*StealthGenerateBatch200ResponseDataSummary, bool) {
	if o == nil || IsNil(o.Summary) {
		return nil, false
	}
	return o.Summary, true
}

// HasSummary returns a boolean if a field has been set.
func (o *StealthGenerateBatch200ResponseData) HasSummary() bool {
	if o != nil && !IsNil(o.Summary) {
		return true
	}

	return false
}

// SetSummary gets a reference to the given StealthGenerateBatch200ResponseDataSummary and assigns it to the Summary field.
func (o *StealthGenerateBatch200ResponseData) SetSummary(v StealthGenerateBatch200ResponseDataSummary) {
	o.Summary = &v
}

func (o StealthGenerateBatch200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StealthGenerateBatch200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	if !IsNil(o.Summary) {
		toSerialize["summary"] = o.Summary
	}
	return toSerialize, nil
}

type NullableStealthGenerateBatch200ResponseData struct {
	value *StealthGenerateBatch200ResponseData
	isSet bool
}

func (v NullableStealthGenerateBatch200ResponseData) Get() *StealthGenerateBatch200ResponseData {
	return v.value
}

func (v *NullableStealthGenerateBatch200ResponseData) Set(val *StealthGenerateBatch200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableStealthGenerateBatch200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableStealthGenerateBatch200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStealthGenerateBatch200ResponseData(val *StealthGenerateBatch200ResponseData) *NullableStealthGenerateBatch200ResponseData {
	return &NullableStealthGenerateBatch200ResponseData{value: val, isSet: true}
}

func (v NullableStealthGenerateBatch200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStealthGenerateBatch200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


