/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
)

// checks if the GetRpcProviders200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRpcProviders200ResponseData{}

// GetRpcProviders200ResponseData struct for GetRpcProviders200ResponseData
type GetRpcProviders200ResponseData struct {
	Active *GetRpcProviders200ResponseDataActive `json:"active,omitempty"`
	Supported []GetRpcProviders200ResponseDataSupportedInner `json:"supported,omitempty"`
}

// NewGetRpcProviders200ResponseData instantiates a new GetRpcProviders200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRpcProviders200ResponseData() *GetRpcProviders200ResponseData {
	this := GetRpcProviders200ResponseData{}
	return &this
}

// NewGetRpcProviders200ResponseDataWithDefaults instantiates a new GetRpcProviders200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRpcProviders200ResponseDataWithDefaults() *GetRpcProviders200ResponseData {
	this := GetRpcProviders200ResponseData{}
	return &this
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *GetRpcProviders200ResponseData) GetActive() GetRpcProviders200ResponseDataActive {
	if o == nil || IsNil(o.Active) {
		var ret GetRpcProviders200ResponseDataActive
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRpcProviders200ResponseData) GetActiveOk() (*GetRpcProviders200ResponseDataActive, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *GetRpcProviders200ResponseData) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given GetRpcProviders200ResponseDataActive and assigns it to the Active field.
func (o *GetRpcProviders200ResponseData) SetActive(v GetRpcProviders200ResponseDataActive) {
	o.Active = &v
}

// GetSupported returns the Supported field value if set, zero value otherwise.
func (o *GetRpcProviders200ResponseData) GetSupported() []GetRpcProviders200ResponseDataSupportedInner {
	if o == nil || IsNil(o.Supported) {
		var ret []GetRpcProviders200ResponseDataSupportedInner
		return ret
	}
	return o.Supported
}

// GetSupportedOk returns a tuple with the Supported field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRpcProviders200ResponseData) GetSupportedOk() ([]GetRpcProviders200ResponseDataSupportedInner, bool) {
	if o == nil || IsNil(o.Supported) {
		return nil, false
	}
	return o.Supported, true
}

// HasSupported returns a boolean if a field has been set.
func (o *GetRpcProviders200ResponseData) HasSupported() bool {
	if o != nil && !IsNil(o.Supported) {
		return true
	}

	return false
}

// SetSupported gets a reference to the given []GetRpcProviders200ResponseDataSupportedInner and assigns it to the Supported field.
func (o *GetRpcProviders200ResponseData) SetSupported(v []GetRpcProviders200ResponseDataSupportedInner) {
	o.Supported = v
}

func (o GetRpcProviders200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetRpcProviders200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	if !IsNil(o.Supported) {
		toSerialize["supported"] = o.Supported
	}
	return toSerialize, nil
}

type NullableGetRpcProviders200ResponseData struct {
	value *GetRpcProviders200ResponseData
	isSet bool
}

func (v NullableGetRpcProviders200ResponseData) Get() *GetRpcProviders200ResponseData {
	return v.value
}

func (v *NullableGetRpcProviders200ResponseData) Set(val *GetRpcProviders200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRpcProviders200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRpcProviders200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRpcProviders200ResponseData(val *GetRpcProviders200ResponseData) *NullableGetRpcProviders200ResponseData {
	return &NullableGetRpcProviders200ResponseData{value: val, isSet: true}
}

func (v NullableGetRpcProviders200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRpcProviders200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


