/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
)

// checks if the ProofsRangeGenerate200ResponseDataMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProofsRangeGenerate200ResponseDataMetadata{}

// ProofsRangeGenerate200ResponseDataMetadata struct for ProofsRangeGenerate200ResponseDataMetadata
type ProofsRangeGenerate200ResponseDataMetadata struct {
	Prover *string `json:"prover,omitempty"`
	Decomposition *string `json:"decomposition,omitempty"`
	LimbCount *int32 `json:"limbCount,omitempty"`
	Security *string `json:"security,omitempty"`
}

// NewProofsRangeGenerate200ResponseDataMetadata instantiates a new ProofsRangeGenerate200ResponseDataMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProofsRangeGenerate200ResponseDataMetadata() *ProofsRangeGenerate200ResponseDataMetadata {
	this := ProofsRangeGenerate200ResponseDataMetadata{}
	return &this
}

// NewProofsRangeGenerate200ResponseDataMetadataWithDefaults instantiates a new ProofsRangeGenerate200ResponseDataMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProofsRangeGenerate200ResponseDataMetadataWithDefaults() *ProofsRangeGenerate200ResponseDataMetadata {
	this := ProofsRangeGenerate200ResponseDataMetadata{}
	return &this
}

// GetProver returns the Prover field value if set, zero value otherwise.
func (o *ProofsRangeGenerate200ResponseDataMetadata) GetProver() string {
	if o == nil || IsNil(o.Prover) {
		var ret string
		return ret
	}
	return *o.Prover
}

// GetProverOk returns a tuple with the Prover field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProofsRangeGenerate200ResponseDataMetadata) GetProverOk() (*string, bool) {
	if o == nil || IsNil(o.Prover) {
		return nil, false
	}
	return o.Prover, true
}

// HasProver returns a boolean if a field has been set.
func (o *ProofsRangeGenerate200ResponseDataMetadata) HasProver() bool {
	if o != nil && !IsNil(o.Prover) {
		return true
	}

	return false
}

// SetProver gets a reference to the given string and assigns it to the Prover field.
func (o *ProofsRangeGenerate200ResponseDataMetadata) SetProver(v string) {
	o.Prover = &v
}

// GetDecomposition returns the Decomposition field value if set, zero value otherwise.
func (o *ProofsRangeGenerate200ResponseDataMetadata) GetDecomposition() string {
	if o == nil || IsNil(o.Decomposition) {
		var ret string
		return ret
	}
	return *o.Decomposition
}

// GetDecompositionOk returns a tuple with the Decomposition field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProofsRangeGenerate200ResponseDataMetadata) GetDecompositionOk() (*string, bool) {
	if o == nil || IsNil(o.Decomposition) {
		return nil, false
	}
	return o.Decomposition, true
}

// HasDecomposition returns a boolean if a field has been set.
func (o *ProofsRangeGenerate200ResponseDataMetadata) HasDecomposition() bool {
	if o != nil && !IsNil(o.Decomposition) {
		return true
	}

	return false
}

// SetDecomposition gets a reference to the given string and assigns it to the Decomposition field.
func (o *ProofsRangeGenerate200ResponseDataMetadata) SetDecomposition(v string) {
	o.Decomposition = &v
}

// GetLimbCount returns the LimbCount field value if set, zero value otherwise.
func (o *ProofsRangeGenerate200ResponseDataMetadata) GetLimbCount() int32 {
	if o == nil || IsNil(o.LimbCount) {
		var ret int32
		return ret
	}
	return *o.LimbCount
}

// GetLimbCountOk returns a tuple with the LimbCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProofsRangeGenerate200ResponseDataMetadata) GetLimbCountOk() (*int32, bool) {
	if o == nil || IsNil(o.LimbCount) {
		return nil, false
	}
	return o.LimbCount, true
}

// HasLimbCount returns a boolean if a field has been set.
func (o *ProofsRangeGenerate200ResponseDataMetadata) HasLimbCount() bool {
	if o != nil && !IsNil(o.LimbCount) {
		return true
	}

	return false
}

// SetLimbCount gets a reference to the given int32 and assigns it to the LimbCount field.
func (o *ProofsRangeGenerate200ResponseDataMetadata) SetLimbCount(v int32) {
	o.LimbCount = &v
}

// GetSecurity returns the Security field value if set, zero value otherwise.
func (o *ProofsRangeGenerate200ResponseDataMetadata) GetSecurity() string {
	if o == nil || IsNil(o.Security) {
		var ret string
		return ret
	}
	return *o.Security
}

// GetSecurityOk returns a tuple with the Security field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProofsRangeGenerate200ResponseDataMetadata) GetSecurityOk() (*string, bool) {
	if o == nil || IsNil(o.Security) {
		return nil, false
	}
	return o.Security, true
}

// HasSecurity returns a boolean if a field has been set.
func (o *ProofsRangeGenerate200ResponseDataMetadata) HasSecurity() bool {
	if o != nil && !IsNil(o.Security) {
		return true
	}

	return false
}

// SetSecurity gets a reference to the given string and assigns it to the Security field.
func (o *ProofsRangeGenerate200ResponseDataMetadata) SetSecurity(v string) {
	o.Security = &v
}

func (o ProofsRangeGenerate200ResponseDataMetadata) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProofsRangeGenerate200ResponseDataMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Prover) {
		toSerialize["prover"] = o.Prover
	}
	if !IsNil(o.Decomposition) {
		toSerialize["decomposition"] = o.Decomposition
	}
	if !IsNil(o.LimbCount) {
		toSerialize["limbCount"] = o.LimbCount
	}
	if !IsNil(o.Security) {
		toSerialize["security"] = o.Security
	}
	return toSerialize, nil
}

type NullableProofsRangeGenerate200ResponseDataMetadata struct {
	value *ProofsRangeGenerate200ResponseDataMetadata
	isSet bool
}

func (v NullableProofsRangeGenerate200ResponseDataMetadata) Get() *ProofsRangeGenerate200ResponseDataMetadata {
	return v.value
}

func (v *NullableProofsRangeGenerate200ResponseDataMetadata) Set(val *ProofsRangeGenerate200ResponseDataMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableProofsRangeGenerate200ResponseDataMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableProofsRangeGenerate200ResponseDataMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProofsRangeGenerate200ResponseDataMetadata(val *ProofsRangeGenerate200ResponseDataMetadata) *NullableProofsRangeGenerate200ResponseDataMetadata {
	return &NullableProofsRangeGenerate200ResponseDataMetadata{value: val, isSet: true}
}

func (v NullableProofsRangeGenerate200ResponseDataMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProofsRangeGenerate200ResponseDataMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


