/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
)

// checks if the CsplWrap200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CsplWrap200Response{}

// CsplWrap200Response struct for CsplWrap200Response
type CsplWrap200Response struct {
	Success *bool `json:"success,omitempty"`
	Data *CsplWrap200ResponseData `json:"data,omitempty"`
}

// NewCsplWrap200Response instantiates a new CsplWrap200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCsplWrap200Response() *CsplWrap200Response {
	this := CsplWrap200Response{}
	return &this
}

// NewCsplWrap200ResponseWithDefaults instantiates a new CsplWrap200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCsplWrap200ResponseWithDefaults() *CsplWrap200Response {
	this := CsplWrap200Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *CsplWrap200Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CsplWrap200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *CsplWrap200Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *CsplWrap200Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CsplWrap200Response) GetData() CsplWrap200ResponseData {
	if o == nil || IsNil(o.Data) {
		var ret CsplWrap200ResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CsplWrap200Response) GetDataOk() (*CsplWrap200ResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CsplWrap200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given CsplWrap200ResponseData and assigns it to the Data field.
func (o *CsplWrap200Response) SetData(v CsplWrap200ResponseData) {
	o.Data = &v
}

func (o CsplWrap200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CsplWrap200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableCsplWrap200Response struct {
	value *CsplWrap200Response
	isSet bool
}

func (v NullableCsplWrap200Response) Get() *CsplWrap200Response {
	return v.value
}

func (v *NullableCsplWrap200Response) Set(val *CsplWrap200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCsplWrap200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCsplWrap200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCsplWrap200Response(val *CsplWrap200Response) *NullableCsplWrap200Response {
	return &NullableCsplWrap200Response{value: val, isSet: true}
}

func (v NullableCsplWrap200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCsplWrap200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


