/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ViewingKeyVerifyHierarchyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ViewingKeyVerifyHierarchyRequest{}

// ViewingKeyVerifyHierarchyRequest struct for ViewingKeyVerifyHierarchyRequest
type ViewingKeyVerifyHierarchyRequest struct {
	ParentKey ViewingKey `json:"parentKey"`
	ChildKey ViewingKey `json:"childKey"`
	ChildPath string `json:"childPath"`
}

type _ViewingKeyVerifyHierarchyRequest ViewingKeyVerifyHierarchyRequest

// NewViewingKeyVerifyHierarchyRequest instantiates a new ViewingKeyVerifyHierarchyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewViewingKeyVerifyHierarchyRequest(parentKey ViewingKey, childKey ViewingKey, childPath string) *ViewingKeyVerifyHierarchyRequest {
	this := ViewingKeyVerifyHierarchyRequest{}
	this.ParentKey = parentKey
	this.ChildKey = childKey
	this.ChildPath = childPath
	return &this
}

// NewViewingKeyVerifyHierarchyRequestWithDefaults instantiates a new ViewingKeyVerifyHierarchyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewViewingKeyVerifyHierarchyRequestWithDefaults() *ViewingKeyVerifyHierarchyRequest {
	this := ViewingKeyVerifyHierarchyRequest{}
	return &this
}

// GetParentKey returns the ParentKey field value
func (o *ViewingKeyVerifyHierarchyRequest) GetParentKey() ViewingKey {
	if o == nil {
		var ret ViewingKey
		return ret
	}

	return o.ParentKey
}

// GetParentKeyOk returns a tuple with the ParentKey field value
// and a boolean to check if the value has been set.
func (o *ViewingKeyVerifyHierarchyRequest) GetParentKeyOk() (*ViewingKey, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ParentKey, true
}

// SetParentKey sets field value
func (o *ViewingKeyVerifyHierarchyRequest) SetParentKey(v ViewingKey) {
	o.ParentKey = v
}

// GetChildKey returns the ChildKey field value
func (o *ViewingKeyVerifyHierarchyRequest) GetChildKey() ViewingKey {
	if o == nil {
		var ret ViewingKey
		return ret
	}

	return o.ChildKey
}

// GetChildKeyOk returns a tuple with the ChildKey field value
// and a boolean to check if the value has been set.
func (o *ViewingKeyVerifyHierarchyRequest) GetChildKeyOk() (*ViewingKey, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChildKey, true
}

// SetChildKey sets field value
func (o *ViewingKeyVerifyHierarchyRequest) SetChildKey(v ViewingKey) {
	o.ChildKey = v
}

// GetChildPath returns the ChildPath field value
func (o *ViewingKeyVerifyHierarchyRequest) GetChildPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChildPath
}

// GetChildPathOk returns a tuple with the ChildPath field value
// and a boolean to check if the value has been set.
func (o *ViewingKeyVerifyHierarchyRequest) GetChildPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChildPath, true
}

// SetChildPath sets field value
func (o *ViewingKeyVerifyHierarchyRequest) SetChildPath(v string) {
	o.ChildPath = v
}

func (o ViewingKeyVerifyHierarchyRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ViewingKeyVerifyHierarchyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["parentKey"] = o.ParentKey
	toSerialize["childKey"] = o.ChildKey
	toSerialize["childPath"] = o.ChildPath
	return toSerialize, nil
}

func (o *ViewingKeyVerifyHierarchyRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"parentKey",
		"childKey",
		"childPath",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varViewingKeyVerifyHierarchyRequest := _ViewingKeyVerifyHierarchyRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varViewingKeyVerifyHierarchyRequest)

	if err != nil {
		return err
	}

	*o = ViewingKeyVerifyHierarchyRequest(varViewingKeyVerifyHierarchyRequest)

	return err
}

type NullableViewingKeyVerifyHierarchyRequest struct {
	value *ViewingKeyVerifyHierarchyRequest
	isSet bool
}

func (v NullableViewingKeyVerifyHierarchyRequest) Get() *ViewingKeyVerifyHierarchyRequest {
	return v.value
}

func (v *NullableViewingKeyVerifyHierarchyRequest) Set(val *ViewingKeyVerifyHierarchyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableViewingKeyVerifyHierarchyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableViewingKeyVerifyHierarchyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableViewingKeyVerifyHierarchyRequest(val *ViewingKeyVerifyHierarchyRequest) *NullableViewingKeyVerifyHierarchyRequest {
	return &NullableViewingKeyVerifyHierarchyRequest{value: val, isSet: true}
}

func (v NullableViewingKeyVerifyHierarchyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableViewingKeyVerifyHierarchyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


