/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
)

// checks if the BackendsCompare200ResponseDataRecommendation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BackendsCompare200ResponseDataRecommendation{}

// BackendsCompare200ResponseDataRecommendation struct for BackendsCompare200ResponseDataRecommendation
type BackendsCompare200ResponseDataRecommendation struct {
	BestOverall *string `json:"best_overall,omitempty"`
	BestValue *string `json:"best_value,omitempty"`
	Fastest *string `json:"fastest,omitempty"`
	MostPrivate *string `json:"most_private,omitempty"`
	Reasoning *string `json:"reasoning,omitempty"`
}

// NewBackendsCompare200ResponseDataRecommendation instantiates a new BackendsCompare200ResponseDataRecommendation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBackendsCompare200ResponseDataRecommendation() *BackendsCompare200ResponseDataRecommendation {
	this := BackendsCompare200ResponseDataRecommendation{}
	return &this
}

// NewBackendsCompare200ResponseDataRecommendationWithDefaults instantiates a new BackendsCompare200ResponseDataRecommendation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBackendsCompare200ResponseDataRecommendationWithDefaults() *BackendsCompare200ResponseDataRecommendation {
	this := BackendsCompare200ResponseDataRecommendation{}
	return &this
}

// GetBestOverall returns the BestOverall field value if set, zero value otherwise.
func (o *BackendsCompare200ResponseDataRecommendation) GetBestOverall() string {
	if o == nil || IsNil(o.BestOverall) {
		var ret string
		return ret
	}
	return *o.BestOverall
}

// GetBestOverallOk returns a tuple with the BestOverall field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackendsCompare200ResponseDataRecommendation) GetBestOverallOk() (*string, bool) {
	if o == nil || IsNil(o.BestOverall) {
		return nil, false
	}
	return o.BestOverall, true
}

// HasBestOverall returns a boolean if a field has been set.
func (o *BackendsCompare200ResponseDataRecommendation) HasBestOverall() bool {
	if o != nil && !IsNil(o.BestOverall) {
		return true
	}

	return false
}

// SetBestOverall gets a reference to the given string and assigns it to the BestOverall field.
func (o *BackendsCompare200ResponseDataRecommendation) SetBestOverall(v string) {
	o.BestOverall = &v
}

// GetBestValue returns the BestValue field value if set, zero value otherwise.
func (o *BackendsCompare200ResponseDataRecommendation) GetBestValue() string {
	if o == nil || IsNil(o.BestValue) {
		var ret string
		return ret
	}
	return *o.BestValue
}

// GetBestValueOk returns a tuple with the BestValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackendsCompare200ResponseDataRecommendation) GetBestValueOk() (*string, bool) {
	if o == nil || IsNil(o.BestValue) {
		return nil, false
	}
	return o.BestValue, true
}

// HasBestValue returns a boolean if a field has been set.
func (o *BackendsCompare200ResponseDataRecommendation) HasBestValue() bool {
	if o != nil && !IsNil(o.BestValue) {
		return true
	}

	return false
}

// SetBestValue gets a reference to the given string and assigns it to the BestValue field.
func (o *BackendsCompare200ResponseDataRecommendation) SetBestValue(v string) {
	o.BestValue = &v
}

// GetFastest returns the Fastest field value if set, zero value otherwise.
func (o *BackendsCompare200ResponseDataRecommendation) GetFastest() string {
	if o == nil || IsNil(o.Fastest) {
		var ret string
		return ret
	}
	return *o.Fastest
}

// GetFastestOk returns a tuple with the Fastest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackendsCompare200ResponseDataRecommendation) GetFastestOk() (*string, bool) {
	if o == nil || IsNil(o.Fastest) {
		return nil, false
	}
	return o.Fastest, true
}

// HasFastest returns a boolean if a field has been set.
func (o *BackendsCompare200ResponseDataRecommendation) HasFastest() bool {
	if o != nil && !IsNil(o.Fastest) {
		return true
	}

	return false
}

// SetFastest gets a reference to the given string and assigns it to the Fastest field.
func (o *BackendsCompare200ResponseDataRecommendation) SetFastest(v string) {
	o.Fastest = &v
}

// GetMostPrivate returns the MostPrivate field value if set, zero value otherwise.
func (o *BackendsCompare200ResponseDataRecommendation) GetMostPrivate() string {
	if o == nil || IsNil(o.MostPrivate) {
		var ret string
		return ret
	}
	return *o.MostPrivate
}

// GetMostPrivateOk returns a tuple with the MostPrivate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackendsCompare200ResponseDataRecommendation) GetMostPrivateOk() (*string, bool) {
	if o == nil || IsNil(o.MostPrivate) {
		return nil, false
	}
	return o.MostPrivate, true
}

// HasMostPrivate returns a boolean if a field has been set.
func (o *BackendsCompare200ResponseDataRecommendation) HasMostPrivate() bool {
	if o != nil && !IsNil(o.MostPrivate) {
		return true
	}

	return false
}

// SetMostPrivate gets a reference to the given string and assigns it to the MostPrivate field.
func (o *BackendsCompare200ResponseDataRecommendation) SetMostPrivate(v string) {
	o.MostPrivate = &v
}

// GetReasoning returns the Reasoning field value if set, zero value otherwise.
func (o *BackendsCompare200ResponseDataRecommendation) GetReasoning() string {
	if o == nil || IsNil(o.Reasoning) {
		var ret string
		return ret
	}
	return *o.Reasoning
}

// GetReasoningOk returns a tuple with the Reasoning field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackendsCompare200ResponseDataRecommendation) GetReasoningOk() (*string, bool) {
	if o == nil || IsNil(o.Reasoning) {
		return nil, false
	}
	return o.Reasoning, true
}

// HasReasoning returns a boolean if a field has been set.
func (o *BackendsCompare200ResponseDataRecommendation) HasReasoning() bool {
	if o != nil && !IsNil(o.Reasoning) {
		return true
	}

	return false
}

// SetReasoning gets a reference to the given string and assigns it to the Reasoning field.
func (o *BackendsCompare200ResponseDataRecommendation) SetReasoning(v string) {
	o.Reasoning = &v
}

func (o BackendsCompare200ResponseDataRecommendation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BackendsCompare200ResponseDataRecommendation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BestOverall) {
		toSerialize["best_overall"] = o.BestOverall
	}
	if !IsNil(o.BestValue) {
		toSerialize["best_value"] = o.BestValue
	}
	if !IsNil(o.Fastest) {
		toSerialize["fastest"] = o.Fastest
	}
	if !IsNil(o.MostPrivate) {
		toSerialize["most_private"] = o.MostPrivate
	}
	if !IsNil(o.Reasoning) {
		toSerialize["reasoning"] = o.Reasoning
	}
	return toSerialize, nil
}

type NullableBackendsCompare200ResponseDataRecommendation struct {
	value *BackendsCompare200ResponseDataRecommendation
	isSet bool
}

func (v NullableBackendsCompare200ResponseDataRecommendation) Get() *BackendsCompare200ResponseDataRecommendation {
	return v.value
}

func (v *NullableBackendsCompare200ResponseDataRecommendation) Set(val *BackendsCompare200ResponseDataRecommendation) {
	v.value = val
	v.isSet = true
}

func (v NullableBackendsCompare200ResponseDataRecommendation) IsSet() bool {
	return v.isSet
}

func (v *NullableBackendsCompare200ResponseDataRecommendation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBackendsCompare200ResponseDataRecommendation(val *BackendsCompare200ResponseDataRecommendation) *NullableBackendsCompare200ResponseDataRecommendation {
	return &NullableBackendsCompare200ResponseDataRecommendation{value: val, isSet: true}
}

func (v NullableBackendsCompare200ResponseDataRecommendation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBackendsCompare200ResponseDataRecommendation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


