/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
	"time"
)

// checks if the GetHealth200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetHealth200ResponseData{}

// GetHealth200ResponseData struct for GetHealth200ResponseData
type GetHealth200ResponseData struct {
	Status *string `json:"status,omitempty"`
	Version *string `json:"version,omitempty"`
	Timestamp *time.Time `json:"timestamp,omitempty"`
	// Uptime in seconds
	Uptime *int32 `json:"uptime,omitempty"`
	Solana *GetHealth200ResponseDataSolana `json:"solana,omitempty"`
	Memory *GetHealth200ResponseDataMemory `json:"memory,omitempty"`
	Endpoints *int32 `json:"endpoints,omitempty"`
}

// NewGetHealth200ResponseData instantiates a new GetHealth200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetHealth200ResponseData() *GetHealth200ResponseData {
	this := GetHealth200ResponseData{}
	return &this
}

// NewGetHealth200ResponseDataWithDefaults instantiates a new GetHealth200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetHealth200ResponseDataWithDefaults() *GetHealth200ResponseData {
	this := GetHealth200ResponseData{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetHealth200ResponseData) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetHealth200ResponseData) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetHealth200ResponseData) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetHealth200ResponseData) SetStatus(v string) {
	o.Status = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *GetHealth200ResponseData) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetHealth200ResponseData) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *GetHealth200ResponseData) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *GetHealth200ResponseData) SetVersion(v string) {
	o.Version = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *GetHealth200ResponseData) GetTimestamp() time.Time {
	if o == nil || IsNil(o.Timestamp) {
		var ret time.Time
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetHealth200ResponseData) GetTimestampOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *GetHealth200ResponseData) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given time.Time and assigns it to the Timestamp field.
func (o *GetHealth200ResponseData) SetTimestamp(v time.Time) {
	o.Timestamp = &v
}

// GetUptime returns the Uptime field value if set, zero value otherwise.
func (o *GetHealth200ResponseData) GetUptime() int32 {
	if o == nil || IsNil(o.Uptime) {
		var ret int32
		return ret
	}
	return *o.Uptime
}

// GetUptimeOk returns a tuple with the Uptime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetHealth200ResponseData) GetUptimeOk() (*int32, bool) {
	if o == nil || IsNil(o.Uptime) {
		return nil, false
	}
	return o.Uptime, true
}

// HasUptime returns a boolean if a field has been set.
func (o *GetHealth200ResponseData) HasUptime() bool {
	if o != nil && !IsNil(o.Uptime) {
		return true
	}

	return false
}

// SetUptime gets a reference to the given int32 and assigns it to the Uptime field.
func (o *GetHealth200ResponseData) SetUptime(v int32) {
	o.Uptime = &v
}

// GetSolana returns the Solana field value if set, zero value otherwise.
func (o *GetHealth200ResponseData) GetSolana() GetHealth200ResponseDataSolana {
	if o == nil || IsNil(o.Solana) {
		var ret GetHealth200ResponseDataSolana
		return ret
	}
	return *o.Solana
}

// GetSolanaOk returns a tuple with the Solana field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetHealth200ResponseData) GetSolanaOk() (*GetHealth200ResponseDataSolana, bool) {
	if o == nil || IsNil(o.Solana) {
		return nil, false
	}
	return o.Solana, true
}

// HasSolana returns a boolean if a field has been set.
func (o *GetHealth200ResponseData) HasSolana() bool {
	if o != nil && !IsNil(o.Solana) {
		return true
	}

	return false
}

// SetSolana gets a reference to the given GetHealth200ResponseDataSolana and assigns it to the Solana field.
func (o *GetHealth200ResponseData) SetSolana(v GetHealth200ResponseDataSolana) {
	o.Solana = &v
}

// GetMemory returns the Memory field value if set, zero value otherwise.
func (o *GetHealth200ResponseData) GetMemory() GetHealth200ResponseDataMemory {
	if o == nil || IsNil(o.Memory) {
		var ret GetHealth200ResponseDataMemory
		return ret
	}
	return *o.Memory
}

// GetMemoryOk returns a tuple with the Memory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetHealth200ResponseData) GetMemoryOk() (*GetHealth200ResponseDataMemory, bool) {
	if o == nil || IsNil(o.Memory) {
		return nil, false
	}
	return o.Memory, true
}

// HasMemory returns a boolean if a field has been set.
func (o *GetHealth200ResponseData) HasMemory() bool {
	if o != nil && !IsNil(o.Memory) {
		return true
	}

	return false
}

// SetMemory gets a reference to the given GetHealth200ResponseDataMemory and assigns it to the Memory field.
func (o *GetHealth200ResponseData) SetMemory(v GetHealth200ResponseDataMemory) {
	o.Memory = &v
}

// GetEndpoints returns the Endpoints field value if set, zero value otherwise.
func (o *GetHealth200ResponseData) GetEndpoints() int32 {
	if o == nil || IsNil(o.Endpoints) {
		var ret int32
		return ret
	}
	return *o.Endpoints
}

// GetEndpointsOk returns a tuple with the Endpoints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetHealth200ResponseData) GetEndpointsOk() (*int32, bool) {
	if o == nil || IsNil(o.Endpoints) {
		return nil, false
	}
	return o.Endpoints, true
}

// HasEndpoints returns a boolean if a field has been set.
func (o *GetHealth200ResponseData) HasEndpoints() bool {
	if o != nil && !IsNil(o.Endpoints) {
		return true
	}

	return false
}

// SetEndpoints gets a reference to the given int32 and assigns it to the Endpoints field.
func (o *GetHealth200ResponseData) SetEndpoints(v int32) {
	o.Endpoints = &v
}

func (o GetHealth200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetHealth200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	if !IsNil(o.Uptime) {
		toSerialize["uptime"] = o.Uptime
	}
	if !IsNil(o.Solana) {
		toSerialize["solana"] = o.Solana
	}
	if !IsNil(o.Memory) {
		toSerialize["memory"] = o.Memory
	}
	if !IsNil(o.Endpoints) {
		toSerialize["endpoints"] = o.Endpoints
	}
	return toSerialize, nil
}

type NullableGetHealth200ResponseData struct {
	value *GetHealth200ResponseData
	isSet bool
}

func (v NullableGetHealth200ResponseData) Get() *GetHealth200ResponseData {
	return v.value
}

func (v *NullableGetHealth200ResponseData) Set(val *GetHealth200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetHealth200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetHealth200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetHealth200ResponseData(val *GetHealth200ResponseData) *NullableGetHealth200ResponseData {
	return &NullableGetHealth200ResponseData{value: val, isSet: true}
}

func (v NullableGetHealth200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetHealth200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


