/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
)

// checks if the StealthGenerateBatch200ResponseDataSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StealthGenerateBatch200ResponseDataSummary{}

// StealthGenerateBatch200ResponseDataSummary struct for StealthGenerateBatch200ResponseDataSummary
type StealthGenerateBatch200ResponseDataSummary struct {
	Total *int32 `json:"total,omitempty"`
	Succeeded *int32 `json:"succeeded,omitempty"`
	Failed *int32 `json:"failed,omitempty"`
}

// NewStealthGenerateBatch200ResponseDataSummary instantiates a new StealthGenerateBatch200ResponseDataSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStealthGenerateBatch200ResponseDataSummary() *StealthGenerateBatch200ResponseDataSummary {
	this := StealthGenerateBatch200ResponseDataSummary{}
	return &this
}

// NewStealthGenerateBatch200ResponseDataSummaryWithDefaults instantiates a new StealthGenerateBatch200ResponseDataSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStealthGenerateBatch200ResponseDataSummaryWithDefaults() *StealthGenerateBatch200ResponseDataSummary {
	this := StealthGenerateBatch200ResponseDataSummary{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *StealthGenerateBatch200ResponseDataSummary) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StealthGenerateBatch200ResponseDataSummary) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *StealthGenerateBatch200ResponseDataSummary) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *StealthGenerateBatch200ResponseDataSummary) SetTotal(v int32) {
	o.Total = &v
}

// GetSucceeded returns the Succeeded field value if set, zero value otherwise.
func (o *StealthGenerateBatch200ResponseDataSummary) GetSucceeded() int32 {
	if o == nil || IsNil(o.Succeeded) {
		var ret int32
		return ret
	}
	return *o.Succeeded
}

// GetSucceededOk returns a tuple with the Succeeded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StealthGenerateBatch200ResponseDataSummary) GetSucceededOk() (*int32, bool) {
	if o == nil || IsNil(o.Succeeded) {
		return nil, false
	}
	return o.Succeeded, true
}

// HasSucceeded returns a boolean if a field has been set.
func (o *StealthGenerateBatch200ResponseDataSummary) HasSucceeded() bool {
	if o != nil && !IsNil(o.Succeeded) {
		return true
	}

	return false
}

// SetSucceeded gets a reference to the given int32 and assigns it to the Succeeded field.
func (o *StealthGenerateBatch200ResponseDataSummary) SetSucceeded(v int32) {
	o.Succeeded = &v
}

// GetFailed returns the Failed field value if set, zero value otherwise.
func (o *StealthGenerateBatch200ResponseDataSummary) GetFailed() int32 {
	if o == nil || IsNil(o.Failed) {
		var ret int32
		return ret
	}
	return *o.Failed
}

// GetFailedOk returns a tuple with the Failed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StealthGenerateBatch200ResponseDataSummary) GetFailedOk() (*int32, bool) {
	if o == nil || IsNil(o.Failed) {
		return nil, false
	}
	return o.Failed, true
}

// HasFailed returns a boolean if a field has been set.
func (o *StealthGenerateBatch200ResponseDataSummary) HasFailed() bool {
	if o != nil && !IsNil(o.Failed) {
		return true
	}

	return false
}

// SetFailed gets a reference to the given int32 and assigns it to the Failed field.
func (o *StealthGenerateBatch200ResponseDataSummary) SetFailed(v int32) {
	o.Failed = &v
}

func (o StealthGenerateBatch200ResponseDataSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StealthGenerateBatch200ResponseDataSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.Succeeded) {
		toSerialize["succeeded"] = o.Succeeded
	}
	if !IsNil(o.Failed) {
		toSerialize["failed"] = o.Failed
	}
	return toSerialize, nil
}

type NullableStealthGenerateBatch200ResponseDataSummary struct {
	value *StealthGenerateBatch200ResponseDataSummary
	isSet bool
}

func (v NullableStealthGenerateBatch200ResponseDataSummary) Get() *StealthGenerateBatch200ResponseDataSummary {
	return v.value
}

func (v *NullableStealthGenerateBatch200ResponseDataSummary) Set(val *StealthGenerateBatch200ResponseDataSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableStealthGenerateBatch200ResponseDataSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableStealthGenerateBatch200ResponseDataSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStealthGenerateBatch200ResponseDataSummary(val *StealthGenerateBatch200ResponseDataSummary) *NullableStealthGenerateBatch200ResponseDataSummary {
	return &NullableStealthGenerateBatch200ResponseDataSummary{value: val, isSet: true}
}

func (v NullableStealthGenerateBatch200ResponseDataSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStealthGenerateBatch200ResponseDataSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


