/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TransferClaimRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransferClaimRequest{}

// TransferClaimRequest struct for TransferClaimRequest
type TransferClaimRequest struct {
	// Base58-encoded Solana public key
	StealthAddress string `json:"stealthAddress"`
	// Base58-encoded Solana public key
	EphemeralPublicKey string `json:"ephemeralPublicKey"`
	// 0x-prefixed 32-byte hex string
	SpendingPrivateKey string `json:"spendingPrivateKey" validate:"regexp=^0x[0-9a-fA-F]{64}$"`
	// 0x-prefixed 32-byte hex string
	ViewingPrivateKey string `json:"viewingPrivateKey" validate:"regexp=^0x[0-9a-fA-F]{64}$"`
	// Base58-encoded Solana public key
	DestinationAddress string `json:"destinationAddress"`
	// Base58-encoded Solana public key
	Mint string `json:"mint"`
}

type _TransferClaimRequest TransferClaimRequest

// NewTransferClaimRequest instantiates a new TransferClaimRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransferClaimRequest(stealthAddress string, ephemeralPublicKey string, spendingPrivateKey string, viewingPrivateKey string, destinationAddress string, mint string) *TransferClaimRequest {
	this := TransferClaimRequest{}
	this.StealthAddress = stealthAddress
	this.EphemeralPublicKey = ephemeralPublicKey
	this.SpendingPrivateKey = spendingPrivateKey
	this.ViewingPrivateKey = viewingPrivateKey
	this.DestinationAddress = destinationAddress
	this.Mint = mint
	return &this
}

// NewTransferClaimRequestWithDefaults instantiates a new TransferClaimRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransferClaimRequestWithDefaults() *TransferClaimRequest {
	this := TransferClaimRequest{}
	return &this
}

// GetStealthAddress returns the StealthAddress field value
func (o *TransferClaimRequest) GetStealthAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StealthAddress
}

// GetStealthAddressOk returns a tuple with the StealthAddress field value
// and a boolean to check if the value has been set.
func (o *TransferClaimRequest) GetStealthAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StealthAddress, true
}

// SetStealthAddress sets field value
func (o *TransferClaimRequest) SetStealthAddress(v string) {
	o.StealthAddress = v
}

// GetEphemeralPublicKey returns the EphemeralPublicKey field value
func (o *TransferClaimRequest) GetEphemeralPublicKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EphemeralPublicKey
}

// GetEphemeralPublicKeyOk returns a tuple with the EphemeralPublicKey field value
// and a boolean to check if the value has been set.
func (o *TransferClaimRequest) GetEphemeralPublicKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EphemeralPublicKey, true
}

// SetEphemeralPublicKey sets field value
func (o *TransferClaimRequest) SetEphemeralPublicKey(v string) {
	o.EphemeralPublicKey = v
}

// GetSpendingPrivateKey returns the SpendingPrivateKey field value
func (o *TransferClaimRequest) GetSpendingPrivateKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SpendingPrivateKey
}

// GetSpendingPrivateKeyOk returns a tuple with the SpendingPrivateKey field value
// and a boolean to check if the value has been set.
func (o *TransferClaimRequest) GetSpendingPrivateKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SpendingPrivateKey, true
}

// SetSpendingPrivateKey sets field value
func (o *TransferClaimRequest) SetSpendingPrivateKey(v string) {
	o.SpendingPrivateKey = v
}

// GetViewingPrivateKey returns the ViewingPrivateKey field value
func (o *TransferClaimRequest) GetViewingPrivateKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ViewingPrivateKey
}

// GetViewingPrivateKeyOk returns a tuple with the ViewingPrivateKey field value
// and a boolean to check if the value has been set.
func (o *TransferClaimRequest) GetViewingPrivateKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ViewingPrivateKey, true
}

// SetViewingPrivateKey sets field value
func (o *TransferClaimRequest) SetViewingPrivateKey(v string) {
	o.ViewingPrivateKey = v
}

// GetDestinationAddress returns the DestinationAddress field value
func (o *TransferClaimRequest) GetDestinationAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DestinationAddress
}

// GetDestinationAddressOk returns a tuple with the DestinationAddress field value
// and a boolean to check if the value has been set.
func (o *TransferClaimRequest) GetDestinationAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DestinationAddress, true
}

// SetDestinationAddress sets field value
func (o *TransferClaimRequest) SetDestinationAddress(v string) {
	o.DestinationAddress = v
}

// GetMint returns the Mint field value
func (o *TransferClaimRequest) GetMint() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Mint
}

// GetMintOk returns a tuple with the Mint field value
// and a boolean to check if the value has been set.
func (o *TransferClaimRequest) GetMintOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mint, true
}

// SetMint sets field value
func (o *TransferClaimRequest) SetMint(v string) {
	o.Mint = v
}

func (o TransferClaimRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransferClaimRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["stealthAddress"] = o.StealthAddress
	toSerialize["ephemeralPublicKey"] = o.EphemeralPublicKey
	toSerialize["spendingPrivateKey"] = o.SpendingPrivateKey
	toSerialize["viewingPrivateKey"] = o.ViewingPrivateKey
	toSerialize["destinationAddress"] = o.DestinationAddress
	toSerialize["mint"] = o.Mint
	return toSerialize, nil
}

func (o *TransferClaimRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"stealthAddress",
		"ephemeralPublicKey",
		"spendingPrivateKey",
		"viewingPrivateKey",
		"destinationAddress",
		"mint",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTransferClaimRequest := _TransferClaimRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTransferClaimRequest)

	if err != nil {
		return err
	}

	*o = TransferClaimRequest(varTransferClaimRequest)

	return err
}

type NullableTransferClaimRequest struct {
	value *TransferClaimRequest
	isSet bool
}

func (v NullableTransferClaimRequest) Get() *TransferClaimRequest {
	return v.value
}

func (v *NullableTransferClaimRequest) Set(val *TransferClaimRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTransferClaimRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTransferClaimRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransferClaimRequest(val *TransferClaimRequest) *NullableTransferClaimRequest {
	return &NullableTransferClaimRequest{value: val, isSet: true}
}

func (v NullableTransferClaimRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransferClaimRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


