/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
)

// checks if the ScanPayments200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScanPayments200Response{}

// ScanPayments200Response struct for ScanPayments200Response
type ScanPayments200Response struct {
	Success *bool `json:"success,omitempty"`
	Data *ScanPayments200ResponseData `json:"data,omitempty"`
}

// NewScanPayments200Response instantiates a new ScanPayments200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScanPayments200Response() *ScanPayments200Response {
	this := ScanPayments200Response{}
	return &this
}

// NewScanPayments200ResponseWithDefaults instantiates a new ScanPayments200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScanPayments200ResponseWithDefaults() *ScanPayments200Response {
	this := ScanPayments200Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *ScanPayments200Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScanPayments200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *ScanPayments200Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *ScanPayments200Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ScanPayments200Response) GetData() ScanPayments200ResponseData {
	if o == nil || IsNil(o.Data) {
		var ret ScanPayments200ResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScanPayments200Response) GetDataOk() (*ScanPayments200ResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ScanPayments200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given ScanPayments200ResponseData and assigns it to the Data field.
func (o *ScanPayments200Response) SetData(v ScanPayments200ResponseData) {
	o.Data = &v
}

func (o ScanPayments200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScanPayments200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableScanPayments200Response struct {
	value *ScanPayments200Response
	isSet bool
}

func (v NullableScanPayments200Response) Get() *ScanPayments200Response {
	return v.value
}

func (v *NullableScanPayments200Response) Set(val *ScanPayments200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableScanPayments200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableScanPayments200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScanPayments200Response(val *ScanPayments200Response) *NullableScanPayments200Response {
	return &NullableScanPayments200Response{value: val, isSet: true}
}

func (v NullableScanPayments200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScanPayments200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


