/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ViewingKey type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ViewingKey{}

// ViewingKey struct for ViewingKey
type ViewingKey struct {
	// 0x-prefixed 32-byte hex string
	Key string `json:"key" validate:"regexp=^0x[0-9a-fA-F]{64}$"`
	Path string `json:"path"`
	// 0x-prefixed 32-byte hex string
	Hash string `json:"hash" validate:"regexp=^0x[0-9a-fA-F]{64}$"`
}

type _ViewingKey ViewingKey

// NewViewingKey instantiates a new ViewingKey object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewViewingKey(key string, path string, hash string) *ViewingKey {
	this := ViewingKey{}
	this.Key = key
	this.Path = path
	this.Hash = hash
	return &this
}

// NewViewingKeyWithDefaults instantiates a new ViewingKey object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewViewingKeyWithDefaults() *ViewingKey {
	this := ViewingKey{}
	return &this
}

// GetKey returns the Key field value
func (o *ViewingKey) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *ViewingKey) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *ViewingKey) SetKey(v string) {
	o.Key = v
}

// GetPath returns the Path field value
func (o *ViewingKey) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *ViewingKey) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *ViewingKey) SetPath(v string) {
	o.Path = v
}

// GetHash returns the Hash field value
func (o *ViewingKey) GetHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Hash
}

// GetHashOk returns a tuple with the Hash field value
// and a boolean to check if the value has been set.
func (o *ViewingKey) GetHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Hash, true
}

// SetHash sets field value
func (o *ViewingKey) SetHash(v string) {
	o.Hash = v
}

func (o ViewingKey) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ViewingKey) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	toSerialize["path"] = o.Path
	toSerialize["hash"] = o.Hash
	return toSerialize, nil
}

func (o *ViewingKey) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
		"path",
		"hash",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varViewingKey := _ViewingKey{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varViewingKey)

	if err != nil {
		return err
	}

	*o = ViewingKey(varViewingKey)

	return err
}

type NullableViewingKey struct {
	value *ViewingKey
	isSet bool
}

func (v NullableViewingKey) Get() *ViewingKey {
	return v.value
}

func (v *NullableViewingKey) Set(val *ViewingKey) {
	v.value = val
	v.isSet = true
}

func (v NullableViewingKey) IsSet() bool {
	return v.isSet
}

func (v *NullableViewingKey) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableViewingKey(val *ViewingKey) *NullableViewingKey {
	return &NullableViewingKey{value: val, isSet: true}
}

func (v NullableViewingKey) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableViewingKey) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


