/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BackendsCompareRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BackendsCompareRequest{}

// BackendsCompareRequest struct for BackendsCompareRequest
type BackendsCompareRequest struct {
	// Type of privacy operation to compare backends for
	Operation string `json:"operation"`
	// Target blockchain (default: solana)
	Chain *string `json:"chain,omitempty"`
	// Transaction amount in smallest units
	Amount *string `json:"amount,omitempty" validate:"regexp=^[1-9]\\\\d*$"`
	// Factor to prioritize in scoring (adjusts weights to 60%)
	Prioritize *string `json:"prioritize,omitempty"`
}

type _BackendsCompareRequest BackendsCompareRequest

// NewBackendsCompareRequest instantiates a new BackendsCompareRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBackendsCompareRequest(operation string) *BackendsCompareRequest {
	this := BackendsCompareRequest{}
	this.Operation = operation
	return &this
}

// NewBackendsCompareRequestWithDefaults instantiates a new BackendsCompareRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBackendsCompareRequestWithDefaults() *BackendsCompareRequest {
	this := BackendsCompareRequest{}
	return &this
}

// GetOperation returns the Operation field value
func (o *BackendsCompareRequest) GetOperation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Operation
}

// GetOperationOk returns a tuple with the Operation field value
// and a boolean to check if the value has been set.
func (o *BackendsCompareRequest) GetOperationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Operation, true
}

// SetOperation sets field value
func (o *BackendsCompareRequest) SetOperation(v string) {
	o.Operation = v
}

// GetChain returns the Chain field value if set, zero value otherwise.
func (o *BackendsCompareRequest) GetChain() string {
	if o == nil || IsNil(o.Chain) {
		var ret string
		return ret
	}
	return *o.Chain
}

// GetChainOk returns a tuple with the Chain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackendsCompareRequest) GetChainOk() (*string, bool) {
	if o == nil || IsNil(o.Chain) {
		return nil, false
	}
	return o.Chain, true
}

// HasChain returns a boolean if a field has been set.
func (o *BackendsCompareRequest) HasChain() bool {
	if o != nil && !IsNil(o.Chain) {
		return true
	}

	return false
}

// SetChain gets a reference to the given string and assigns it to the Chain field.
func (o *BackendsCompareRequest) SetChain(v string) {
	o.Chain = &v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *BackendsCompareRequest) GetAmount() string {
	if o == nil || IsNil(o.Amount) {
		var ret string
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackendsCompareRequest) GetAmountOk() (*string, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *BackendsCompareRequest) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given string and assigns it to the Amount field.
func (o *BackendsCompareRequest) SetAmount(v string) {
	o.Amount = &v
}

// GetPrioritize returns the Prioritize field value if set, zero value otherwise.
func (o *BackendsCompareRequest) GetPrioritize() string {
	if o == nil || IsNil(o.Prioritize) {
		var ret string
		return ret
	}
	return *o.Prioritize
}

// GetPrioritizeOk returns a tuple with the Prioritize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackendsCompareRequest) GetPrioritizeOk() (*string, bool) {
	if o == nil || IsNil(o.Prioritize) {
		return nil, false
	}
	return o.Prioritize, true
}

// HasPrioritize returns a boolean if a field has been set.
func (o *BackendsCompareRequest) HasPrioritize() bool {
	if o != nil && !IsNil(o.Prioritize) {
		return true
	}

	return false
}

// SetPrioritize gets a reference to the given string and assigns it to the Prioritize field.
func (o *BackendsCompareRequest) SetPrioritize(v string) {
	o.Prioritize = &v
}

func (o BackendsCompareRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BackendsCompareRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["operation"] = o.Operation
	if !IsNil(o.Chain) {
		toSerialize["chain"] = o.Chain
	}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.Prioritize) {
		toSerialize["prioritize"] = o.Prioritize
	}
	return toSerialize, nil
}

func (o *BackendsCompareRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"operation",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBackendsCompareRequest := _BackendsCompareRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBackendsCompareRequest)

	if err != nil {
		return err
	}

	*o = BackendsCompareRequest(varBackendsCompareRequest)

	return err
}

type NullableBackendsCompareRequest struct {
	value *BackendsCompareRequest
	isSet bool
}

func (v NullableBackendsCompareRequest) Get() *BackendsCompareRequest {
	return v.value
}

func (v *NullableBackendsCompareRequest) Set(val *BackendsCompareRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBackendsCompareRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBackendsCompareRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBackendsCompareRequest(val *BackendsCompareRequest) *NullableBackendsCompareRequest {
	return &NullableBackendsCompareRequest{value: val, isSet: true}
}

func (v NullableBackendsCompareRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBackendsCompareRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


