/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StealthAddress type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StealthAddress{}

// StealthAddress struct for StealthAddress
type StealthAddress struct {
	// 0x-prefixed 32-byte hex string
	Address string `json:"address" validate:"regexp=^0x[0-9a-fA-F]{64}$"`
	// 0x-prefixed 32-byte hex string
	EphemeralPublicKey string `json:"ephemeralPublicKey" validate:"regexp=^0x[0-9a-fA-F]{64}$"`
	ViewTag int32 `json:"viewTag"`
}

type _StealthAddress StealthAddress

// NewStealthAddress instantiates a new StealthAddress object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStealthAddress(address string, ephemeralPublicKey string, viewTag int32) *StealthAddress {
	this := StealthAddress{}
	this.Address = address
	this.EphemeralPublicKey = ephemeralPublicKey
	this.ViewTag = viewTag
	return &this
}

// NewStealthAddressWithDefaults instantiates a new StealthAddress object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStealthAddressWithDefaults() *StealthAddress {
	this := StealthAddress{}
	return &this
}

// GetAddress returns the Address field value
func (o *StealthAddress) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *StealthAddress) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *StealthAddress) SetAddress(v string) {
	o.Address = v
}

// GetEphemeralPublicKey returns the EphemeralPublicKey field value
func (o *StealthAddress) GetEphemeralPublicKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EphemeralPublicKey
}

// GetEphemeralPublicKeyOk returns a tuple with the EphemeralPublicKey field value
// and a boolean to check if the value has been set.
func (o *StealthAddress) GetEphemeralPublicKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EphemeralPublicKey, true
}

// SetEphemeralPublicKey sets field value
func (o *StealthAddress) SetEphemeralPublicKey(v string) {
	o.EphemeralPublicKey = v
}

// GetViewTag returns the ViewTag field value
func (o *StealthAddress) GetViewTag() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ViewTag
}

// GetViewTagOk returns a tuple with the ViewTag field value
// and a boolean to check if the value has been set.
func (o *StealthAddress) GetViewTagOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ViewTag, true
}

// SetViewTag sets field value
func (o *StealthAddress) SetViewTag(v int32) {
	o.ViewTag = v
}

func (o StealthAddress) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StealthAddress) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address
	toSerialize["ephemeralPublicKey"] = o.EphemeralPublicKey
	toSerialize["viewTag"] = o.ViewTag
	return toSerialize, nil
}

func (o *StealthAddress) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"address",
		"ephemeralPublicKey",
		"viewTag",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStealthAddress := _StealthAddress{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStealthAddress)

	if err != nil {
		return err
	}

	*o = StealthAddress(varStealthAddress)

	return err
}

type NullableStealthAddress struct {
	value *StealthAddress
	isSet bool
}

func (v NullableStealthAddress) Get() *StealthAddress {
	return v.value
}

func (v *NullableStealthAddress) Set(val *StealthAddress) {
	v.value = val
	v.isSet = true
}

func (v NullableStealthAddress) IsSet() bool {
	return v.isSet
}

func (v *NullableStealthAddress) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStealthAddress(val *StealthAddress) *NullableStealthAddress {
	return &NullableStealthAddress{value: val, isSet: true}
}

func (v NullableStealthAddress) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStealthAddress) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


