/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
)

// checks if the StealthCheck200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StealthCheck200ResponseData{}

// StealthCheck200ResponseData struct for StealthCheck200ResponseData
type StealthCheck200ResponseData struct {
	IsOwner *bool `json:"isOwner,omitempty"`
}

// NewStealthCheck200ResponseData instantiates a new StealthCheck200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStealthCheck200ResponseData() *StealthCheck200ResponseData {
	this := StealthCheck200ResponseData{}
	return &this
}

// NewStealthCheck200ResponseDataWithDefaults instantiates a new StealthCheck200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStealthCheck200ResponseDataWithDefaults() *StealthCheck200ResponseData {
	this := StealthCheck200ResponseData{}
	return &this
}

// GetIsOwner returns the IsOwner field value if set, zero value otherwise.
func (o *StealthCheck200ResponseData) GetIsOwner() bool {
	if o == nil || IsNil(o.IsOwner) {
		var ret bool
		return ret
	}
	return *o.IsOwner
}

// GetIsOwnerOk returns a tuple with the IsOwner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StealthCheck200ResponseData) GetIsOwnerOk() (*bool, bool) {
	if o == nil || IsNil(o.IsOwner) {
		return nil, false
	}
	return o.IsOwner, true
}

// HasIsOwner returns a boolean if a field has been set.
func (o *StealthCheck200ResponseData) HasIsOwner() bool {
	if o != nil && !IsNil(o.IsOwner) {
		return true
	}

	return false
}

// SetIsOwner gets a reference to the given bool and assigns it to the IsOwner field.
func (o *StealthCheck200ResponseData) SetIsOwner(v bool) {
	o.IsOwner = &v
}

func (o StealthCheck200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StealthCheck200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IsOwner) {
		toSerialize["isOwner"] = o.IsOwner
	}
	return toSerialize, nil
}

type NullableStealthCheck200ResponseData struct {
	value *StealthCheck200ResponseData
	isSet bool
}

func (v NullableStealthCheck200ResponseData) Get() *StealthCheck200ResponseData {
	return v.value
}

func (v *NullableStealthCheck200ResponseData) Set(val *StealthCheck200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableStealthCheck200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableStealthCheck200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStealthCheck200ResponseData(val *StealthCheck200ResponseData) *NullableStealthCheck200ResponseData {
	return &NullableStealthCheck200ResponseData{value: val, isSet: true}
}

func (v NullableStealthCheck200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStealthCheck200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


