/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EncryptIncoValueRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EncryptIncoValueRequest{}

// EncryptIncoValueRequest struct for EncryptIncoValueRequest
type EncryptIncoValueRequest struct {
	Plaintext EncryptIncoValueRequestPlaintext `json:"plaintext"`
	// FHE scheme to use
	Scheme string `json:"scheme"`
	// Optional label for the encryption
	Label *string `json:"label,omitempty"`
}

type _EncryptIncoValueRequest EncryptIncoValueRequest

// NewEncryptIncoValueRequest instantiates a new EncryptIncoValueRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEncryptIncoValueRequest(plaintext EncryptIncoValueRequestPlaintext, scheme string) *EncryptIncoValueRequest {
	this := EncryptIncoValueRequest{}
	this.Plaintext = plaintext
	this.Scheme = scheme
	return &this
}

// NewEncryptIncoValueRequestWithDefaults instantiates a new EncryptIncoValueRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEncryptIncoValueRequestWithDefaults() *EncryptIncoValueRequest {
	this := EncryptIncoValueRequest{}
	return &this
}

// GetPlaintext returns the Plaintext field value
func (o *EncryptIncoValueRequest) GetPlaintext() EncryptIncoValueRequestPlaintext {
	if o == nil {
		var ret EncryptIncoValueRequestPlaintext
		return ret
	}

	return o.Plaintext
}

// GetPlaintextOk returns a tuple with the Plaintext field value
// and a boolean to check if the value has been set.
func (o *EncryptIncoValueRequest) GetPlaintextOk() (*EncryptIncoValueRequestPlaintext, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Plaintext, true
}

// SetPlaintext sets field value
func (o *EncryptIncoValueRequest) SetPlaintext(v EncryptIncoValueRequestPlaintext) {
	o.Plaintext = v
}

// GetScheme returns the Scheme field value
func (o *EncryptIncoValueRequest) GetScheme() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Scheme
}

// GetSchemeOk returns a tuple with the Scheme field value
// and a boolean to check if the value has been set.
func (o *EncryptIncoValueRequest) GetSchemeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Scheme, true
}

// SetScheme sets field value
func (o *EncryptIncoValueRequest) SetScheme(v string) {
	o.Scheme = v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *EncryptIncoValueRequest) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EncryptIncoValueRequest) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *EncryptIncoValueRequest) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *EncryptIncoValueRequest) SetLabel(v string) {
	o.Label = &v
}

func (o EncryptIncoValueRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EncryptIncoValueRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["plaintext"] = o.Plaintext
	toSerialize["scheme"] = o.Scheme
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	return toSerialize, nil
}

func (o *EncryptIncoValueRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"plaintext",
		"scheme",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEncryptIncoValueRequest := _EncryptIncoValueRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEncryptIncoValueRequest)

	if err != nil {
		return err
	}

	*o = EncryptIncoValueRequest(varEncryptIncoValueRequest)

	return err
}

type NullableEncryptIncoValueRequest struct {
	value *EncryptIncoValueRequest
	isSet bool
}

func (v NullableEncryptIncoValueRequest) Get() *EncryptIncoValueRequest {
	return v.value
}

func (v *NullableEncryptIncoValueRequest) Set(val *EncryptIncoValueRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEncryptIncoValueRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEncryptIncoValueRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEncryptIncoValueRequest(val *EncryptIncoValueRequest) *NullableEncryptIncoValueRequest {
	return &NullableEncryptIncoValueRequest{value: val, isSet: true}
}

func (v NullableEncryptIncoValueRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEncryptIncoValueRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


