/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
)

// checks if the BackendsHealth200ResponseDataMetrics type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BackendsHealth200ResponseDataMetrics{}

// BackendsHealth200ResponseDataMetrics struct for BackendsHealth200ResponseDataMetrics
type BackendsHealth200ResponseDataMetrics struct {
	TotalRequests *int32 `json:"totalRequests,omitempty"`
	SuccessfulRequests *int32 `json:"successfulRequests,omitempty"`
	FailedRequests *int32 `json:"failedRequests,omitempty"`
	AverageLatencyMs *float32 `json:"averageLatencyMs,omitempty"`
}

// NewBackendsHealth200ResponseDataMetrics instantiates a new BackendsHealth200ResponseDataMetrics object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBackendsHealth200ResponseDataMetrics() *BackendsHealth200ResponseDataMetrics {
	this := BackendsHealth200ResponseDataMetrics{}
	return &this
}

// NewBackendsHealth200ResponseDataMetricsWithDefaults instantiates a new BackendsHealth200ResponseDataMetrics object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBackendsHealth200ResponseDataMetricsWithDefaults() *BackendsHealth200ResponseDataMetrics {
	this := BackendsHealth200ResponseDataMetrics{}
	return &this
}

// GetTotalRequests returns the TotalRequests field value if set, zero value otherwise.
func (o *BackendsHealth200ResponseDataMetrics) GetTotalRequests() int32 {
	if o == nil || IsNil(o.TotalRequests) {
		var ret int32
		return ret
	}
	return *o.TotalRequests
}

// GetTotalRequestsOk returns a tuple with the TotalRequests field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackendsHealth200ResponseDataMetrics) GetTotalRequestsOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalRequests) {
		return nil, false
	}
	return o.TotalRequests, true
}

// HasTotalRequests returns a boolean if a field has been set.
func (o *BackendsHealth200ResponseDataMetrics) HasTotalRequests() bool {
	if o != nil && !IsNil(o.TotalRequests) {
		return true
	}

	return false
}

// SetTotalRequests gets a reference to the given int32 and assigns it to the TotalRequests field.
func (o *BackendsHealth200ResponseDataMetrics) SetTotalRequests(v int32) {
	o.TotalRequests = &v
}

// GetSuccessfulRequests returns the SuccessfulRequests field value if set, zero value otherwise.
func (o *BackendsHealth200ResponseDataMetrics) GetSuccessfulRequests() int32 {
	if o == nil || IsNil(o.SuccessfulRequests) {
		var ret int32
		return ret
	}
	return *o.SuccessfulRequests
}

// GetSuccessfulRequestsOk returns a tuple with the SuccessfulRequests field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackendsHealth200ResponseDataMetrics) GetSuccessfulRequestsOk() (*int32, bool) {
	if o == nil || IsNil(o.SuccessfulRequests) {
		return nil, false
	}
	return o.SuccessfulRequests, true
}

// HasSuccessfulRequests returns a boolean if a field has been set.
func (o *BackendsHealth200ResponseDataMetrics) HasSuccessfulRequests() bool {
	if o != nil && !IsNil(o.SuccessfulRequests) {
		return true
	}

	return false
}

// SetSuccessfulRequests gets a reference to the given int32 and assigns it to the SuccessfulRequests field.
func (o *BackendsHealth200ResponseDataMetrics) SetSuccessfulRequests(v int32) {
	o.SuccessfulRequests = &v
}

// GetFailedRequests returns the FailedRequests field value if set, zero value otherwise.
func (o *BackendsHealth200ResponseDataMetrics) GetFailedRequests() int32 {
	if o == nil || IsNil(o.FailedRequests) {
		var ret int32
		return ret
	}
	return *o.FailedRequests
}

// GetFailedRequestsOk returns a tuple with the FailedRequests field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackendsHealth200ResponseDataMetrics) GetFailedRequestsOk() (*int32, bool) {
	if o == nil || IsNil(o.FailedRequests) {
		return nil, false
	}
	return o.FailedRequests, true
}

// HasFailedRequests returns a boolean if a field has been set.
func (o *BackendsHealth200ResponseDataMetrics) HasFailedRequests() bool {
	if o != nil && !IsNil(o.FailedRequests) {
		return true
	}

	return false
}

// SetFailedRequests gets a reference to the given int32 and assigns it to the FailedRequests field.
func (o *BackendsHealth200ResponseDataMetrics) SetFailedRequests(v int32) {
	o.FailedRequests = &v
}

// GetAverageLatencyMs returns the AverageLatencyMs field value if set, zero value otherwise.
func (o *BackendsHealth200ResponseDataMetrics) GetAverageLatencyMs() float32 {
	if o == nil || IsNil(o.AverageLatencyMs) {
		var ret float32
		return ret
	}
	return *o.AverageLatencyMs
}

// GetAverageLatencyMsOk returns a tuple with the AverageLatencyMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackendsHealth200ResponseDataMetrics) GetAverageLatencyMsOk() (*float32, bool) {
	if o == nil || IsNil(o.AverageLatencyMs) {
		return nil, false
	}
	return o.AverageLatencyMs, true
}

// HasAverageLatencyMs returns a boolean if a field has been set.
func (o *BackendsHealth200ResponseDataMetrics) HasAverageLatencyMs() bool {
	if o != nil && !IsNil(o.AverageLatencyMs) {
		return true
	}

	return false
}

// SetAverageLatencyMs gets a reference to the given float32 and assigns it to the AverageLatencyMs field.
func (o *BackendsHealth200ResponseDataMetrics) SetAverageLatencyMs(v float32) {
	o.AverageLatencyMs = &v
}

func (o BackendsHealth200ResponseDataMetrics) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BackendsHealth200ResponseDataMetrics) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TotalRequests) {
		toSerialize["totalRequests"] = o.TotalRequests
	}
	if !IsNil(o.SuccessfulRequests) {
		toSerialize["successfulRequests"] = o.SuccessfulRequests
	}
	if !IsNil(o.FailedRequests) {
		toSerialize["failedRequests"] = o.FailedRequests
	}
	if !IsNil(o.AverageLatencyMs) {
		toSerialize["averageLatencyMs"] = o.AverageLatencyMs
	}
	return toSerialize, nil
}

type NullableBackendsHealth200ResponseDataMetrics struct {
	value *BackendsHealth200ResponseDataMetrics
	isSet bool
}

func (v NullableBackendsHealth200ResponseDataMetrics) Get() *BackendsHealth200ResponseDataMetrics {
	return v.value
}

func (v *NullableBackendsHealth200ResponseDataMetrics) Set(val *BackendsHealth200ResponseDataMetrics) {
	v.value = val
	v.isSet = true
}

func (v NullableBackendsHealth200ResponseDataMetrics) IsSet() bool {
	return v.isSet
}

func (v *NullableBackendsHealth200ResponseDataMetrics) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBackendsHealth200ResponseDataMetrics(val *BackendsHealth200ResponseDataMetrics) *NullableBackendsHealth200ResponseDataMetrics {
	return &NullableBackendsHealth200ResponseDataMetrics{value: val, isSet: true}
}

func (v NullableBackendsHealth200ResponseDataMetrics) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBackendsHealth200ResponseDataMetrics) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


