/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
)

// checks if the ViewingKeyGenerateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ViewingKeyGenerateRequest{}

// ViewingKeyGenerateRequest struct for ViewingKeyGenerateRequest
type ViewingKeyGenerateRequest struct {
	// Derivation path
	Path *string `json:"path,omitempty"`
	Label *string `json:"label,omitempty"`
}

// NewViewingKeyGenerateRequest instantiates a new ViewingKeyGenerateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewViewingKeyGenerateRequest() *ViewingKeyGenerateRequest {
	this := ViewingKeyGenerateRequest{}
	var path string = "m/0"
	this.Path = &path
	return &this
}

// NewViewingKeyGenerateRequestWithDefaults instantiates a new ViewingKeyGenerateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewViewingKeyGenerateRequestWithDefaults() *ViewingKeyGenerateRequest {
	this := ViewingKeyGenerateRequest{}
	var path string = "m/0"
	this.Path = &path
	return &this
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *ViewingKeyGenerateRequest) GetPath() string {
	if o == nil || IsNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewingKeyGenerateRequest) GetPathOk() (*string, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *ViewingKeyGenerateRequest) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *ViewingKeyGenerateRequest) SetPath(v string) {
	o.Path = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *ViewingKeyGenerateRequest) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewingKeyGenerateRequest) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *ViewingKeyGenerateRequest) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *ViewingKeyGenerateRequest) SetLabel(v string) {
	o.Label = &v
}

func (o ViewingKeyGenerateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ViewingKeyGenerateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	return toSerialize, nil
}

type NullableViewingKeyGenerateRequest struct {
	value *ViewingKeyGenerateRequest
	isSet bool
}

func (v NullableViewingKeyGenerateRequest) Get() *ViewingKeyGenerateRequest {
	return v.value
}

func (v *NullableViewingKeyGenerateRequest) Set(val *ViewingKeyGenerateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableViewingKeyGenerateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableViewingKeyGenerateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableViewingKeyGenerateRequest(val *ViewingKeyGenerateRequest) *NullableViewingKeyGenerateRequest {
	return &NullableViewingKeyGenerateRequest{value: val, isSet: true}
}

func (v NullableViewingKeyGenerateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableViewingKeyGenerateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


