/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
)

// checks if the ComplianceReport200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComplianceReport200ResponseData{}

// ComplianceReport200ResponseData struct for ComplianceReport200ResponseData
type ComplianceReport200ResponseData struct {
	ReportId *string `json:"reportId,omitempty" validate:"regexp=^rpt_[0-9a-fA-F]{64}$"`
	Status *string `json:"status,omitempty"`
	GeneratedAt *int32 `json:"generatedAt,omitempty"`
	ExpiresAt *int32 `json:"expiresAt,omitempty"`
	Summary *ComplianceReport200ResponseDataSummary `json:"summary,omitempty"`
	EncryptedReport *string `json:"encryptedReport,omitempty"`
	ReportHash *string `json:"reportHash,omitempty"`
}

// NewComplianceReport200ResponseData instantiates a new ComplianceReport200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComplianceReport200ResponseData() *ComplianceReport200ResponseData {
	this := ComplianceReport200ResponseData{}
	return &this
}

// NewComplianceReport200ResponseDataWithDefaults instantiates a new ComplianceReport200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComplianceReport200ResponseDataWithDefaults() *ComplianceReport200ResponseData {
	this := ComplianceReport200ResponseData{}
	return &this
}

// GetReportId returns the ReportId field value if set, zero value otherwise.
func (o *ComplianceReport200ResponseData) GetReportId() string {
	if o == nil || IsNil(o.ReportId) {
		var ret string
		return ret
	}
	return *o.ReportId
}

// GetReportIdOk returns a tuple with the ReportId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComplianceReport200ResponseData) GetReportIdOk() (*string, bool) {
	if o == nil || IsNil(o.ReportId) {
		return nil, false
	}
	return o.ReportId, true
}

// HasReportId returns a boolean if a field has been set.
func (o *ComplianceReport200ResponseData) HasReportId() bool {
	if o != nil && !IsNil(o.ReportId) {
		return true
	}

	return false
}

// SetReportId gets a reference to the given string and assigns it to the ReportId field.
func (o *ComplianceReport200ResponseData) SetReportId(v string) {
	o.ReportId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ComplianceReport200ResponseData) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComplianceReport200ResponseData) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ComplianceReport200ResponseData) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ComplianceReport200ResponseData) SetStatus(v string) {
	o.Status = &v
}

// GetGeneratedAt returns the GeneratedAt field value if set, zero value otherwise.
func (o *ComplianceReport200ResponseData) GetGeneratedAt() int32 {
	if o == nil || IsNil(o.GeneratedAt) {
		var ret int32
		return ret
	}
	return *o.GeneratedAt
}

// GetGeneratedAtOk returns a tuple with the GeneratedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComplianceReport200ResponseData) GetGeneratedAtOk() (*int32, bool) {
	if o == nil || IsNil(o.GeneratedAt) {
		return nil, false
	}
	return o.GeneratedAt, true
}

// HasGeneratedAt returns a boolean if a field has been set.
func (o *ComplianceReport200ResponseData) HasGeneratedAt() bool {
	if o != nil && !IsNil(o.GeneratedAt) {
		return true
	}

	return false
}

// SetGeneratedAt gets a reference to the given int32 and assigns it to the GeneratedAt field.
func (o *ComplianceReport200ResponseData) SetGeneratedAt(v int32) {
	o.GeneratedAt = &v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *ComplianceReport200ResponseData) GetExpiresAt() int32 {
	if o == nil || IsNil(o.ExpiresAt) {
		var ret int32
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComplianceReport200ResponseData) GetExpiresAtOk() (*int32, bool) {
	if o == nil || IsNil(o.ExpiresAt) {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *ComplianceReport200ResponseData) HasExpiresAt() bool {
	if o != nil && !IsNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given int32 and assigns it to the ExpiresAt field.
func (o *ComplianceReport200ResponseData) SetExpiresAt(v int32) {
	o.ExpiresAt = &v
}

// GetSummary returns the Summary field value if set, zero value otherwise.
func (o *ComplianceReport200ResponseData) GetSummary() ComplianceReport200ResponseDataSummary {
	if o == nil || IsNil(o.Summary) {
		var ret ComplianceReport200ResponseDataSummary
		return ret
	}
	return *o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComplianceReport200ResponseData) GetSummaryOk() (*ComplianceReport200ResponseDataSummary, bool) {
	if o == nil || IsNil(o.Summary) {
		return nil, false
	}
	return o.Summary, true
}

// HasSummary returns a boolean if a field has been set.
func (o *ComplianceReport200ResponseData) HasSummary() bool {
	if o != nil && !IsNil(o.Summary) {
		return true
	}

	return false
}

// SetSummary gets a reference to the given ComplianceReport200ResponseDataSummary and assigns it to the Summary field.
func (o *ComplianceReport200ResponseData) SetSummary(v ComplianceReport200ResponseDataSummary) {
	o.Summary = &v
}

// GetEncryptedReport returns the EncryptedReport field value if set, zero value otherwise.
func (o *ComplianceReport200ResponseData) GetEncryptedReport() string {
	if o == nil || IsNil(o.EncryptedReport) {
		var ret string
		return ret
	}
	return *o.EncryptedReport
}

// GetEncryptedReportOk returns a tuple with the EncryptedReport field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComplianceReport200ResponseData) GetEncryptedReportOk() (*string, bool) {
	if o == nil || IsNil(o.EncryptedReport) {
		return nil, false
	}
	return o.EncryptedReport, true
}

// HasEncryptedReport returns a boolean if a field has been set.
func (o *ComplianceReport200ResponseData) HasEncryptedReport() bool {
	if o != nil && !IsNil(o.EncryptedReport) {
		return true
	}

	return false
}

// SetEncryptedReport gets a reference to the given string and assigns it to the EncryptedReport field.
func (o *ComplianceReport200ResponseData) SetEncryptedReport(v string) {
	o.EncryptedReport = &v
}

// GetReportHash returns the ReportHash field value if set, zero value otherwise.
func (o *ComplianceReport200ResponseData) GetReportHash() string {
	if o == nil || IsNil(o.ReportHash) {
		var ret string
		return ret
	}
	return *o.ReportHash
}

// GetReportHashOk returns a tuple with the ReportHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComplianceReport200ResponseData) GetReportHashOk() (*string, bool) {
	if o == nil || IsNil(o.ReportHash) {
		return nil, false
	}
	return o.ReportHash, true
}

// HasReportHash returns a boolean if a field has been set.
func (o *ComplianceReport200ResponseData) HasReportHash() bool {
	if o != nil && !IsNil(o.ReportHash) {
		return true
	}

	return false
}

// SetReportHash gets a reference to the given string and assigns it to the ReportHash field.
func (o *ComplianceReport200ResponseData) SetReportHash(v string) {
	o.ReportHash = &v
}

func (o ComplianceReport200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComplianceReport200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ReportId) {
		toSerialize["reportId"] = o.ReportId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.GeneratedAt) {
		toSerialize["generatedAt"] = o.GeneratedAt
	}
	if !IsNil(o.ExpiresAt) {
		toSerialize["expiresAt"] = o.ExpiresAt
	}
	if !IsNil(o.Summary) {
		toSerialize["summary"] = o.Summary
	}
	if !IsNil(o.EncryptedReport) {
		toSerialize["encryptedReport"] = o.EncryptedReport
	}
	if !IsNil(o.ReportHash) {
		toSerialize["reportHash"] = o.ReportHash
	}
	return toSerialize, nil
}

type NullableComplianceReport200ResponseData struct {
	value *ComplianceReport200ResponseData
	isSet bool
}

func (v NullableComplianceReport200ResponseData) Get() *ComplianceReport200ResponseData {
	return v.value
}

func (v *NullableComplianceReport200ResponseData) Set(val *ComplianceReport200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableComplianceReport200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableComplianceReport200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComplianceReport200ResponseData(val *ComplianceReport200ResponseData) *NullableComplianceReport200ResponseData {
	return &NullableComplianceReport200ResponseData{value: val, isSet: true}
}

func (v NullableComplianceReport200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComplianceReport200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


