/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
)

// checks if the CommitmentCreateBatch200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommitmentCreateBatch200ResponseData{}

// CommitmentCreateBatch200ResponseData struct for CommitmentCreateBatch200ResponseData
type CommitmentCreateBatch200ResponseData struct {
	Results []CommitmentCreateBatch200ResponseDataResultsInner `json:"results,omitempty"`
	Summary *StealthGenerateBatch200ResponseDataSummary `json:"summary,omitempty"`
}

// NewCommitmentCreateBatch200ResponseData instantiates a new CommitmentCreateBatch200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommitmentCreateBatch200ResponseData() *CommitmentCreateBatch200ResponseData {
	this := CommitmentCreateBatch200ResponseData{}
	return &this
}

// NewCommitmentCreateBatch200ResponseDataWithDefaults instantiates a new CommitmentCreateBatch200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommitmentCreateBatch200ResponseDataWithDefaults() *CommitmentCreateBatch200ResponseData {
	this := CommitmentCreateBatch200ResponseData{}
	return &this
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *CommitmentCreateBatch200ResponseData) GetResults() []CommitmentCreateBatch200ResponseDataResultsInner {
	if o == nil || IsNil(o.Results) {
		var ret []CommitmentCreateBatch200ResponseDataResultsInner
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommitmentCreateBatch200ResponseData) GetResultsOk() ([]CommitmentCreateBatch200ResponseDataResultsInner, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *CommitmentCreateBatch200ResponseData) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []CommitmentCreateBatch200ResponseDataResultsInner and assigns it to the Results field.
func (o *CommitmentCreateBatch200ResponseData) SetResults(v []CommitmentCreateBatch200ResponseDataResultsInner) {
	o.Results = v
}

// GetSummary returns the Summary field value if set, zero value otherwise.
func (o *CommitmentCreateBatch200ResponseData) GetSummary() StealthGenerateBatch200ResponseDataSummary {
	if o == nil || IsNil(o.Summary) {
		var ret StealthGenerateBatch200ResponseDataSummary
		return ret
	}
	return *o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommitmentCreateBatch200ResponseData) GetSummaryOk() (*StealthGenerateBatch200ResponseDataSummary, bool) {
	if o == nil || IsNil(o.Summary) {
		return nil, false
	}
	return o.Summary, true
}

// HasSummary returns a boolean if a field has been set.
func (o *CommitmentCreateBatch200ResponseData) HasSummary() bool {
	if o != nil && !IsNil(o.Summary) {
		return true
	}

	return false
}

// SetSummary gets a reference to the given StealthGenerateBatch200ResponseDataSummary and assigns it to the Summary field.
func (o *CommitmentCreateBatch200ResponseData) SetSummary(v StealthGenerateBatch200ResponseDataSummary) {
	o.Summary = &v
}

func (o CommitmentCreateBatch200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommitmentCreateBatch200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	if !IsNil(o.Summary) {
		toSerialize["summary"] = o.Summary
	}
	return toSerialize, nil
}

type NullableCommitmentCreateBatch200ResponseData struct {
	value *CommitmentCreateBatch200ResponseData
	isSet bool
}

func (v NullableCommitmentCreateBatch200ResponseData) Get() *CommitmentCreateBatch200ResponseData {
	return v.value
}

func (v *NullableCommitmentCreateBatch200ResponseData) Set(val *CommitmentCreateBatch200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableCommitmentCreateBatch200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableCommitmentCreateBatch200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommitmentCreateBatch200ResponseData(val *CommitmentCreateBatch200ResponseData) *NullableCommitmentCreateBatch200ResponseData {
	return &NullableCommitmentCreateBatch200ResponseData{value: val, isSet: true}
}

func (v NullableCommitmentCreateBatch200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommitmentCreateBatch200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


