/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ViewingKeyDeriveRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ViewingKeyDeriveRequest{}

// ViewingKeyDeriveRequest struct for ViewingKeyDeriveRequest
type ViewingKeyDeriveRequest struct {
	MasterKey ViewingKey `json:"masterKey"`
	// Derivation path segment (e.g., \"audit\", \"2026/Q1\")
	ChildPath string `json:"childPath"`
}

type _ViewingKeyDeriveRequest ViewingKeyDeriveRequest

// NewViewingKeyDeriveRequest instantiates a new ViewingKeyDeriveRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewViewingKeyDeriveRequest(masterKey ViewingKey, childPath string) *ViewingKeyDeriveRequest {
	this := ViewingKeyDeriveRequest{}
	this.MasterKey = masterKey
	this.ChildPath = childPath
	return &this
}

// NewViewingKeyDeriveRequestWithDefaults instantiates a new ViewingKeyDeriveRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewViewingKeyDeriveRequestWithDefaults() *ViewingKeyDeriveRequest {
	this := ViewingKeyDeriveRequest{}
	return &this
}

// GetMasterKey returns the MasterKey field value
func (o *ViewingKeyDeriveRequest) GetMasterKey() ViewingKey {
	if o == nil {
		var ret ViewingKey
		return ret
	}

	return o.MasterKey
}

// GetMasterKeyOk returns a tuple with the MasterKey field value
// and a boolean to check if the value has been set.
func (o *ViewingKeyDeriveRequest) GetMasterKeyOk() (*ViewingKey, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MasterKey, true
}

// SetMasterKey sets field value
func (o *ViewingKeyDeriveRequest) SetMasterKey(v ViewingKey) {
	o.MasterKey = v
}

// GetChildPath returns the ChildPath field value
func (o *ViewingKeyDeriveRequest) GetChildPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChildPath
}

// GetChildPathOk returns a tuple with the ChildPath field value
// and a boolean to check if the value has been set.
func (o *ViewingKeyDeriveRequest) GetChildPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChildPath, true
}

// SetChildPath sets field value
func (o *ViewingKeyDeriveRequest) SetChildPath(v string) {
	o.ChildPath = v
}

func (o ViewingKeyDeriveRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ViewingKeyDeriveRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["masterKey"] = o.MasterKey
	toSerialize["childPath"] = o.ChildPath
	return toSerialize, nil
}

func (o *ViewingKeyDeriveRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"masterKey",
		"childPath",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varViewingKeyDeriveRequest := _ViewingKeyDeriveRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varViewingKeyDeriveRequest)

	if err != nil {
		return err
	}

	*o = ViewingKeyDeriveRequest(varViewingKeyDeriveRequest)

	return err
}

type NullableViewingKeyDeriveRequest struct {
	value *ViewingKeyDeriveRequest
	isSet bool
}

func (v NullableViewingKeyDeriveRequest) Get() *ViewingKeyDeriveRequest {
	return v.value
}

func (v *NullableViewingKeyDeriveRequest) Set(val *ViewingKeyDeriveRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableViewingKeyDeriveRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableViewingKeyDeriveRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableViewingKeyDeriveRequest(val *ViewingKeyDeriveRequest) *NullableViewingKeyDeriveRequest {
	return &NullableViewingKeyDeriveRequest{value: val, isSet: true}
}

func (v NullableViewingKeyDeriveRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableViewingKeyDeriveRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


