/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
)

// checks if the CsplTransfer200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CsplTransfer200ResponseData{}

// CsplTransfer200ResponseData struct for CsplTransfer200ResponseData
type CsplTransfer200ResponseData struct {
	// Transaction signature
	Signature *string `json:"signature,omitempty"`
	// Updated sender encrypted balance
	NewSenderBalance *string `json:"newSenderBalance,omitempty" validate:"regexp=^0x[0-9a-fA-F]+$"`
	// Whether recipient pending balance was updated
	RecipientPendingUpdated *bool `json:"recipientPendingUpdated,omitempty"`
}

// NewCsplTransfer200ResponseData instantiates a new CsplTransfer200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCsplTransfer200ResponseData() *CsplTransfer200ResponseData {
	this := CsplTransfer200ResponseData{}
	return &this
}

// NewCsplTransfer200ResponseDataWithDefaults instantiates a new CsplTransfer200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCsplTransfer200ResponseDataWithDefaults() *CsplTransfer200ResponseData {
	this := CsplTransfer200ResponseData{}
	return &this
}

// GetSignature returns the Signature field value if set, zero value otherwise.
func (o *CsplTransfer200ResponseData) GetSignature() string {
	if o == nil || IsNil(o.Signature) {
		var ret string
		return ret
	}
	return *o.Signature
}

// GetSignatureOk returns a tuple with the Signature field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CsplTransfer200ResponseData) GetSignatureOk() (*string, bool) {
	if o == nil || IsNil(o.Signature) {
		return nil, false
	}
	return o.Signature, true
}

// HasSignature returns a boolean if a field has been set.
func (o *CsplTransfer200ResponseData) HasSignature() bool {
	if o != nil && !IsNil(o.Signature) {
		return true
	}

	return false
}

// SetSignature gets a reference to the given string and assigns it to the Signature field.
func (o *CsplTransfer200ResponseData) SetSignature(v string) {
	o.Signature = &v
}

// GetNewSenderBalance returns the NewSenderBalance field value if set, zero value otherwise.
func (o *CsplTransfer200ResponseData) GetNewSenderBalance() string {
	if o == nil || IsNil(o.NewSenderBalance) {
		var ret string
		return ret
	}
	return *o.NewSenderBalance
}

// GetNewSenderBalanceOk returns a tuple with the NewSenderBalance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CsplTransfer200ResponseData) GetNewSenderBalanceOk() (*string, bool) {
	if o == nil || IsNil(o.NewSenderBalance) {
		return nil, false
	}
	return o.NewSenderBalance, true
}

// HasNewSenderBalance returns a boolean if a field has been set.
func (o *CsplTransfer200ResponseData) HasNewSenderBalance() bool {
	if o != nil && !IsNil(o.NewSenderBalance) {
		return true
	}

	return false
}

// SetNewSenderBalance gets a reference to the given string and assigns it to the NewSenderBalance field.
func (o *CsplTransfer200ResponseData) SetNewSenderBalance(v string) {
	o.NewSenderBalance = &v
}

// GetRecipientPendingUpdated returns the RecipientPendingUpdated field value if set, zero value otherwise.
func (o *CsplTransfer200ResponseData) GetRecipientPendingUpdated() bool {
	if o == nil || IsNil(o.RecipientPendingUpdated) {
		var ret bool
		return ret
	}
	return *o.RecipientPendingUpdated
}

// GetRecipientPendingUpdatedOk returns a tuple with the RecipientPendingUpdated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CsplTransfer200ResponseData) GetRecipientPendingUpdatedOk() (*bool, bool) {
	if o == nil || IsNil(o.RecipientPendingUpdated) {
		return nil, false
	}
	return o.RecipientPendingUpdated, true
}

// HasRecipientPendingUpdated returns a boolean if a field has been set.
func (o *CsplTransfer200ResponseData) HasRecipientPendingUpdated() bool {
	if o != nil && !IsNil(o.RecipientPendingUpdated) {
		return true
	}

	return false
}

// SetRecipientPendingUpdated gets a reference to the given bool and assigns it to the RecipientPendingUpdated field.
func (o *CsplTransfer200ResponseData) SetRecipientPendingUpdated(v bool) {
	o.RecipientPendingUpdated = &v
}

func (o CsplTransfer200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CsplTransfer200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Signature) {
		toSerialize["signature"] = o.Signature
	}
	if !IsNil(o.NewSenderBalance) {
		toSerialize["newSenderBalance"] = o.NewSenderBalance
	}
	if !IsNil(o.RecipientPendingUpdated) {
		toSerialize["recipientPendingUpdated"] = o.RecipientPendingUpdated
	}
	return toSerialize, nil
}

type NullableCsplTransfer200ResponseData struct {
	value *CsplTransfer200ResponseData
	isSet bool
}

func (v NullableCsplTransfer200ResponseData) Get() *CsplTransfer200ResponseData {
	return v.value
}

func (v *NullableCsplTransfer200ResponseData) Set(val *CsplTransfer200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableCsplTransfer200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableCsplTransfer200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCsplTransfer200ResponseData(val *CsplTransfer200ResponseData) *NullableCsplTransfer200ResponseData {
	return &NullableCsplTransfer200ResponseData{value: val, isSet: true}
}

func (v NullableCsplTransfer200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCsplTransfer200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


