/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
)

// checks if the GetErrors200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetErrors200ResponseData{}

// GetErrors200ResponseData struct for GetErrors200ResponseData
type GetErrors200ResponseData struct {
	TotalCodes *int32 `json:"totalCodes,omitempty"`
	Errors []GetErrors200ResponseDataErrorsInner `json:"errors,omitempty"`
}

// NewGetErrors200ResponseData instantiates a new GetErrors200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetErrors200ResponseData() *GetErrors200ResponseData {
	this := GetErrors200ResponseData{}
	return &this
}

// NewGetErrors200ResponseDataWithDefaults instantiates a new GetErrors200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetErrors200ResponseDataWithDefaults() *GetErrors200ResponseData {
	this := GetErrors200ResponseData{}
	return &this
}

// GetTotalCodes returns the TotalCodes field value if set, zero value otherwise.
func (o *GetErrors200ResponseData) GetTotalCodes() int32 {
	if o == nil || IsNil(o.TotalCodes) {
		var ret int32
		return ret
	}
	return *o.TotalCodes
}

// GetTotalCodesOk returns a tuple with the TotalCodes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetErrors200ResponseData) GetTotalCodesOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalCodes) {
		return nil, false
	}
	return o.TotalCodes, true
}

// HasTotalCodes returns a boolean if a field has been set.
func (o *GetErrors200ResponseData) HasTotalCodes() bool {
	if o != nil && !IsNil(o.TotalCodes) {
		return true
	}

	return false
}

// SetTotalCodes gets a reference to the given int32 and assigns it to the TotalCodes field.
func (o *GetErrors200ResponseData) SetTotalCodes(v int32) {
	o.TotalCodes = &v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *GetErrors200ResponseData) GetErrors() []GetErrors200ResponseDataErrorsInner {
	if o == nil || IsNil(o.Errors) {
		var ret []GetErrors200ResponseDataErrorsInner
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetErrors200ResponseData) GetErrorsOk() ([]GetErrors200ResponseDataErrorsInner, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *GetErrors200ResponseData) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []GetErrors200ResponseDataErrorsInner and assigns it to the Errors field.
func (o *GetErrors200ResponseData) SetErrors(v []GetErrors200ResponseDataErrorsInner) {
	o.Errors = v
}

func (o GetErrors200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetErrors200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TotalCodes) {
		toSerialize["totalCodes"] = o.TotalCodes
	}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	return toSerialize, nil
}

type NullableGetErrors200ResponseData struct {
	value *GetErrors200ResponseData
	isSet bool
}

func (v NullableGetErrors200ResponseData) Get() *GetErrors200ResponseData {
	return v.value
}

func (v *NullableGetErrors200ResponseData) Set(val *GetErrors200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetErrors200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetErrors200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetErrors200ResponseData(val *GetErrors200ResponseData) *NullableGetErrors200ResponseData {
	return &NullableGetErrors200ResponseData{value: val, isSet: true}
}

func (v NullableGetErrors200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetErrors200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


