/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PrivacyScoreRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PrivacyScoreRequest{}

// PrivacyScoreRequest struct for PrivacyScoreRequest
type PrivacyScoreRequest struct {
	// Base58-encoded Solana public key
	Address string `json:"address"`
	// Number of recent transactions to analyze
	Limit *int32 `json:"limit,omitempty"`
}

type _PrivacyScoreRequest PrivacyScoreRequest

// NewPrivacyScoreRequest instantiates a new PrivacyScoreRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrivacyScoreRequest(address string) *PrivacyScoreRequest {
	this := PrivacyScoreRequest{}
	this.Address = address
	var limit int32 = 100
	this.Limit = &limit
	return &this
}

// NewPrivacyScoreRequestWithDefaults instantiates a new PrivacyScoreRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrivacyScoreRequestWithDefaults() *PrivacyScoreRequest {
	this := PrivacyScoreRequest{}
	var limit int32 = 100
	this.Limit = &limit
	return &this
}

// GetAddress returns the Address field value
func (o *PrivacyScoreRequest) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *PrivacyScoreRequest) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *PrivacyScoreRequest) SetAddress(v string) {
	o.Address = v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *PrivacyScoreRequest) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrivacyScoreRequest) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *PrivacyScoreRequest) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *PrivacyScoreRequest) SetLimit(v int32) {
	o.Limit = &v
}

func (o PrivacyScoreRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PrivacyScoreRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	return toSerialize, nil
}

func (o *PrivacyScoreRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"address",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPrivacyScoreRequest := _PrivacyScoreRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPrivacyScoreRequest)

	if err != nil {
		return err
	}

	*o = PrivacyScoreRequest(varPrivacyScoreRequest)

	return err
}

type NullablePrivacyScoreRequest struct {
	value *PrivacyScoreRequest
	isSet bool
}

func (v NullablePrivacyScoreRequest) Get() *PrivacyScoreRequest {
	return v.value
}

func (v *NullablePrivacyScoreRequest) Set(val *PrivacyScoreRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePrivacyScoreRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePrivacyScoreRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrivacyScoreRequest(val *PrivacyScoreRequest) *NullablePrivacyScoreRequest {
	return &NullablePrivacyScoreRequest{value: val, isSet: true}
}

func (v NullablePrivacyScoreRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrivacyScoreRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


