/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
)

// checks if the GetArciumComputationStatus200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetArciumComputationStatus200ResponseData{}

// GetArciumComputationStatus200ResponseData struct for GetArciumComputationStatus200ResponseData
type GetArciumComputationStatus200ResponseData struct {
	ComputationId *string `json:"computationId,omitempty"`
	CircuitId *string `json:"circuitId,omitempty"`
	Chain *string `json:"chain,omitempty"`
	Status *string `json:"status,omitempty"`
	Progress *int32 `json:"progress,omitempty"`
	// Only present when status is completed
	Output *string `json:"output,omitempty"`
	// Only present when status is completed
	Proof *string `json:"proof,omitempty"`
}

// NewGetArciumComputationStatus200ResponseData instantiates a new GetArciumComputationStatus200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetArciumComputationStatus200ResponseData() *GetArciumComputationStatus200ResponseData {
	this := GetArciumComputationStatus200ResponseData{}
	return &this
}

// NewGetArciumComputationStatus200ResponseDataWithDefaults instantiates a new GetArciumComputationStatus200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetArciumComputationStatus200ResponseDataWithDefaults() *GetArciumComputationStatus200ResponseData {
	this := GetArciumComputationStatus200ResponseData{}
	return &this
}

// GetComputationId returns the ComputationId field value if set, zero value otherwise.
func (o *GetArciumComputationStatus200ResponseData) GetComputationId() string {
	if o == nil || IsNil(o.ComputationId) {
		var ret string
		return ret
	}
	return *o.ComputationId
}

// GetComputationIdOk returns a tuple with the ComputationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetArciumComputationStatus200ResponseData) GetComputationIdOk() (*string, bool) {
	if o == nil || IsNil(o.ComputationId) {
		return nil, false
	}
	return o.ComputationId, true
}

// HasComputationId returns a boolean if a field has been set.
func (o *GetArciumComputationStatus200ResponseData) HasComputationId() bool {
	if o != nil && !IsNil(o.ComputationId) {
		return true
	}

	return false
}

// SetComputationId gets a reference to the given string and assigns it to the ComputationId field.
func (o *GetArciumComputationStatus200ResponseData) SetComputationId(v string) {
	o.ComputationId = &v
}

// GetCircuitId returns the CircuitId field value if set, zero value otherwise.
func (o *GetArciumComputationStatus200ResponseData) GetCircuitId() string {
	if o == nil || IsNil(o.CircuitId) {
		var ret string
		return ret
	}
	return *o.CircuitId
}

// GetCircuitIdOk returns a tuple with the CircuitId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetArciumComputationStatus200ResponseData) GetCircuitIdOk() (*string, bool) {
	if o == nil || IsNil(o.CircuitId) {
		return nil, false
	}
	return o.CircuitId, true
}

// HasCircuitId returns a boolean if a field has been set.
func (o *GetArciumComputationStatus200ResponseData) HasCircuitId() bool {
	if o != nil && !IsNil(o.CircuitId) {
		return true
	}

	return false
}

// SetCircuitId gets a reference to the given string and assigns it to the CircuitId field.
func (o *GetArciumComputationStatus200ResponseData) SetCircuitId(v string) {
	o.CircuitId = &v
}

// GetChain returns the Chain field value if set, zero value otherwise.
func (o *GetArciumComputationStatus200ResponseData) GetChain() string {
	if o == nil || IsNil(o.Chain) {
		var ret string
		return ret
	}
	return *o.Chain
}

// GetChainOk returns a tuple with the Chain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetArciumComputationStatus200ResponseData) GetChainOk() (*string, bool) {
	if o == nil || IsNil(o.Chain) {
		return nil, false
	}
	return o.Chain, true
}

// HasChain returns a boolean if a field has been set.
func (o *GetArciumComputationStatus200ResponseData) HasChain() bool {
	if o != nil && !IsNil(o.Chain) {
		return true
	}

	return false
}

// SetChain gets a reference to the given string and assigns it to the Chain field.
func (o *GetArciumComputationStatus200ResponseData) SetChain(v string) {
	o.Chain = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetArciumComputationStatus200ResponseData) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetArciumComputationStatus200ResponseData) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetArciumComputationStatus200ResponseData) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetArciumComputationStatus200ResponseData) SetStatus(v string) {
	o.Status = &v
}

// GetProgress returns the Progress field value if set, zero value otherwise.
func (o *GetArciumComputationStatus200ResponseData) GetProgress() int32 {
	if o == nil || IsNil(o.Progress) {
		var ret int32
		return ret
	}
	return *o.Progress
}

// GetProgressOk returns a tuple with the Progress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetArciumComputationStatus200ResponseData) GetProgressOk() (*int32, bool) {
	if o == nil || IsNil(o.Progress) {
		return nil, false
	}
	return o.Progress, true
}

// HasProgress returns a boolean if a field has been set.
func (o *GetArciumComputationStatus200ResponseData) HasProgress() bool {
	if o != nil && !IsNil(o.Progress) {
		return true
	}

	return false
}

// SetProgress gets a reference to the given int32 and assigns it to the Progress field.
func (o *GetArciumComputationStatus200ResponseData) SetProgress(v int32) {
	o.Progress = &v
}

// GetOutput returns the Output field value if set, zero value otherwise.
func (o *GetArciumComputationStatus200ResponseData) GetOutput() string {
	if o == nil || IsNil(o.Output) {
		var ret string
		return ret
	}
	return *o.Output
}

// GetOutputOk returns a tuple with the Output field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetArciumComputationStatus200ResponseData) GetOutputOk() (*string, bool) {
	if o == nil || IsNil(o.Output) {
		return nil, false
	}
	return o.Output, true
}

// HasOutput returns a boolean if a field has been set.
func (o *GetArciumComputationStatus200ResponseData) HasOutput() bool {
	if o != nil && !IsNil(o.Output) {
		return true
	}

	return false
}

// SetOutput gets a reference to the given string and assigns it to the Output field.
func (o *GetArciumComputationStatus200ResponseData) SetOutput(v string) {
	o.Output = &v
}

// GetProof returns the Proof field value if set, zero value otherwise.
func (o *GetArciumComputationStatus200ResponseData) GetProof() string {
	if o == nil || IsNil(o.Proof) {
		var ret string
		return ret
	}
	return *o.Proof
}

// GetProofOk returns a tuple with the Proof field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetArciumComputationStatus200ResponseData) GetProofOk() (*string, bool) {
	if o == nil || IsNil(o.Proof) {
		return nil, false
	}
	return o.Proof, true
}

// HasProof returns a boolean if a field has been set.
func (o *GetArciumComputationStatus200ResponseData) HasProof() bool {
	if o != nil && !IsNil(o.Proof) {
		return true
	}

	return false
}

// SetProof gets a reference to the given string and assigns it to the Proof field.
func (o *GetArciumComputationStatus200ResponseData) SetProof(v string) {
	o.Proof = &v
}

func (o GetArciumComputationStatus200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetArciumComputationStatus200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ComputationId) {
		toSerialize["computationId"] = o.ComputationId
	}
	if !IsNil(o.CircuitId) {
		toSerialize["circuitId"] = o.CircuitId
	}
	if !IsNil(o.Chain) {
		toSerialize["chain"] = o.Chain
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Progress) {
		toSerialize["progress"] = o.Progress
	}
	if !IsNil(o.Output) {
		toSerialize["output"] = o.Output
	}
	if !IsNil(o.Proof) {
		toSerialize["proof"] = o.Proof
	}
	return toSerialize, nil
}

type NullableGetArciumComputationStatus200ResponseData struct {
	value *GetArciumComputationStatus200ResponseData
	isSet bool
}

func (v NullableGetArciumComputationStatus200ResponseData) Get() *GetArciumComputationStatus200ResponseData {
	return v.value
}

func (v *NullableGetArciumComputationStatus200ResponseData) Set(val *GetArciumComputationStatus200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetArciumComputationStatus200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetArciumComputationStatus200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetArciumComputationStatus200ResponseData(val *GetArciumComputationStatus200ResponseData) *NullableGetArciumComputationStatus200ResponseData {
	return &NullableGetArciumComputationStatus200ResponseData{value: val, isSet: true}
}

func (v NullableGetArciumComputationStatus200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetArciumComputationStatus200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


