/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
)

// checks if the BackendsCompare200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BackendsCompare200Response{}

// BackendsCompare200Response struct for BackendsCompare200Response
type BackendsCompare200Response struct {
	Success *bool `json:"success,omitempty"`
	Data *BackendsCompare200ResponseData `json:"data,omitempty"`
}

// NewBackendsCompare200Response instantiates a new BackendsCompare200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBackendsCompare200Response() *BackendsCompare200Response {
	this := BackendsCompare200Response{}
	return &this
}

// NewBackendsCompare200ResponseWithDefaults instantiates a new BackendsCompare200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBackendsCompare200ResponseWithDefaults() *BackendsCompare200Response {
	this := BackendsCompare200Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *BackendsCompare200Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackendsCompare200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *BackendsCompare200Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *BackendsCompare200Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *BackendsCompare200Response) GetData() BackendsCompare200ResponseData {
	if o == nil || IsNil(o.Data) {
		var ret BackendsCompare200ResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackendsCompare200Response) GetDataOk() (*BackendsCompare200ResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *BackendsCompare200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given BackendsCompare200ResponseData and assigns it to the Data field.
func (o *BackendsCompare200Response) SetData(v BackendsCompare200ResponseData) {
	o.Data = &v
}

func (o BackendsCompare200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BackendsCompare200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableBackendsCompare200Response struct {
	value *BackendsCompare200Response
	isSet bool
}

func (v NullableBackendsCompare200Response) Get() *BackendsCompare200Response {
	return v.value
}

func (v *NullableBackendsCompare200Response) Set(val *BackendsCompare200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableBackendsCompare200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableBackendsCompare200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBackendsCompare200Response(val *BackendsCompare200Response) *NullableBackendsCompare200Response {
	return &NullableBackendsCompare200Response{value: val, isSet: true}
}

func (v NullableBackendsCompare200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBackendsCompare200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


