/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CsplWrapRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CsplWrapRequest{}

// CsplWrapRequest struct for CsplWrapRequest
type CsplWrapRequest struct {
	// SPL token mint address
	Mint string `json:"mint"`
	// Positive integer as string (no leading zeros)
	Amount string `json:"amount" validate:"regexp=^[1-9]\\\\d*$"`
	// Base58-encoded Solana public key
	Owner string `json:"owner"`
	// Create C-SPL account if missing
	CreateAccount *bool `json:"createAccount,omitempty"`
}

type _CsplWrapRequest CsplWrapRequest

// NewCsplWrapRequest instantiates a new CsplWrapRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCsplWrapRequest(mint string, amount string, owner string) *CsplWrapRequest {
	this := CsplWrapRequest{}
	this.Mint = mint
	this.Amount = amount
	this.Owner = owner
	var createAccount bool = true
	this.CreateAccount = &createAccount
	return &this
}

// NewCsplWrapRequestWithDefaults instantiates a new CsplWrapRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCsplWrapRequestWithDefaults() *CsplWrapRequest {
	this := CsplWrapRequest{}
	var createAccount bool = true
	this.CreateAccount = &createAccount
	return &this
}

// GetMint returns the Mint field value
func (o *CsplWrapRequest) GetMint() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Mint
}

// GetMintOk returns a tuple with the Mint field value
// and a boolean to check if the value has been set.
func (o *CsplWrapRequest) GetMintOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mint, true
}

// SetMint sets field value
func (o *CsplWrapRequest) SetMint(v string) {
	o.Mint = v
}

// GetAmount returns the Amount field value
func (o *CsplWrapRequest) GetAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *CsplWrapRequest) GetAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *CsplWrapRequest) SetAmount(v string) {
	o.Amount = v
}

// GetOwner returns the Owner field value
func (o *CsplWrapRequest) GetOwner() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value
// and a boolean to check if the value has been set.
func (o *CsplWrapRequest) GetOwnerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Owner, true
}

// SetOwner sets field value
func (o *CsplWrapRequest) SetOwner(v string) {
	o.Owner = v
}

// GetCreateAccount returns the CreateAccount field value if set, zero value otherwise.
func (o *CsplWrapRequest) GetCreateAccount() bool {
	if o == nil || IsNil(o.CreateAccount) {
		var ret bool
		return ret
	}
	return *o.CreateAccount
}

// GetCreateAccountOk returns a tuple with the CreateAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CsplWrapRequest) GetCreateAccountOk() (*bool, bool) {
	if o == nil || IsNil(o.CreateAccount) {
		return nil, false
	}
	return o.CreateAccount, true
}

// HasCreateAccount returns a boolean if a field has been set.
func (o *CsplWrapRequest) HasCreateAccount() bool {
	if o != nil && !IsNil(o.CreateAccount) {
		return true
	}

	return false
}

// SetCreateAccount gets a reference to the given bool and assigns it to the CreateAccount field.
func (o *CsplWrapRequest) SetCreateAccount(v bool) {
	o.CreateAccount = &v
}

func (o CsplWrapRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CsplWrapRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["mint"] = o.Mint
	toSerialize["amount"] = o.Amount
	toSerialize["owner"] = o.Owner
	if !IsNil(o.CreateAccount) {
		toSerialize["createAccount"] = o.CreateAccount
	}
	return toSerialize, nil
}

func (o *CsplWrapRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"mint",
		"amount",
		"owner",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCsplWrapRequest := _CsplWrapRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCsplWrapRequest)

	if err != nil {
		return err
	}

	*o = CsplWrapRequest(varCsplWrapRequest)

	return err
}

type NullableCsplWrapRequest struct {
	value *CsplWrapRequest
	isSet bool
}

func (v NullableCsplWrapRequest) Get() *CsplWrapRequest {
	return v.value
}

func (v *NullableCsplWrapRequest) Set(val *CsplWrapRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCsplWrapRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCsplWrapRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCsplWrapRequest(val *CsplWrapRequest) *NullableCsplWrapRequest {
	return &NullableCsplWrapRequest{value: val, isSet: true}
}

func (v NullableCsplWrapRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCsplWrapRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


