/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
)

// checks if the BackendsHealth200ResponseDataHealth type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BackendsHealth200ResponseDataHealth{}

// BackendsHealth200ResponseDataHealth struct for BackendsHealth200ResponseDataHealth
type BackendsHealth200ResponseDataHealth struct {
	CircuitState *string `json:"circuitState,omitempty"`
	IsHealthy *bool `json:"isHealthy,omitempty"`
	ConsecutiveFailures *int32 `json:"consecutiveFailures,omitempty"`
	ConsecutiveSuccesses *int32 `json:"consecutiveSuccesses,omitempty"`
	LastChecked *int32 `json:"lastChecked,omitempty"`
	LastFailureReason *string `json:"lastFailureReason,omitempty"`
}

// NewBackendsHealth200ResponseDataHealth instantiates a new BackendsHealth200ResponseDataHealth object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBackendsHealth200ResponseDataHealth() *BackendsHealth200ResponseDataHealth {
	this := BackendsHealth200ResponseDataHealth{}
	return &this
}

// NewBackendsHealth200ResponseDataHealthWithDefaults instantiates a new BackendsHealth200ResponseDataHealth object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBackendsHealth200ResponseDataHealthWithDefaults() *BackendsHealth200ResponseDataHealth {
	this := BackendsHealth200ResponseDataHealth{}
	return &this
}

// GetCircuitState returns the CircuitState field value if set, zero value otherwise.
func (o *BackendsHealth200ResponseDataHealth) GetCircuitState() string {
	if o == nil || IsNil(o.CircuitState) {
		var ret string
		return ret
	}
	return *o.CircuitState
}

// GetCircuitStateOk returns a tuple with the CircuitState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackendsHealth200ResponseDataHealth) GetCircuitStateOk() (*string, bool) {
	if o == nil || IsNil(o.CircuitState) {
		return nil, false
	}
	return o.CircuitState, true
}

// HasCircuitState returns a boolean if a field has been set.
func (o *BackendsHealth200ResponseDataHealth) HasCircuitState() bool {
	if o != nil && !IsNil(o.CircuitState) {
		return true
	}

	return false
}

// SetCircuitState gets a reference to the given string and assigns it to the CircuitState field.
func (o *BackendsHealth200ResponseDataHealth) SetCircuitState(v string) {
	o.CircuitState = &v
}

// GetIsHealthy returns the IsHealthy field value if set, zero value otherwise.
func (o *BackendsHealth200ResponseDataHealth) GetIsHealthy() bool {
	if o == nil || IsNil(o.IsHealthy) {
		var ret bool
		return ret
	}
	return *o.IsHealthy
}

// GetIsHealthyOk returns a tuple with the IsHealthy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackendsHealth200ResponseDataHealth) GetIsHealthyOk() (*bool, bool) {
	if o == nil || IsNil(o.IsHealthy) {
		return nil, false
	}
	return o.IsHealthy, true
}

// HasIsHealthy returns a boolean if a field has been set.
func (o *BackendsHealth200ResponseDataHealth) HasIsHealthy() bool {
	if o != nil && !IsNil(o.IsHealthy) {
		return true
	}

	return false
}

// SetIsHealthy gets a reference to the given bool and assigns it to the IsHealthy field.
func (o *BackendsHealth200ResponseDataHealth) SetIsHealthy(v bool) {
	o.IsHealthy = &v
}

// GetConsecutiveFailures returns the ConsecutiveFailures field value if set, zero value otherwise.
func (o *BackendsHealth200ResponseDataHealth) GetConsecutiveFailures() int32 {
	if o == nil || IsNil(o.ConsecutiveFailures) {
		var ret int32
		return ret
	}
	return *o.ConsecutiveFailures
}

// GetConsecutiveFailuresOk returns a tuple with the ConsecutiveFailures field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackendsHealth200ResponseDataHealth) GetConsecutiveFailuresOk() (*int32, bool) {
	if o == nil || IsNil(o.ConsecutiveFailures) {
		return nil, false
	}
	return o.ConsecutiveFailures, true
}

// HasConsecutiveFailures returns a boolean if a field has been set.
func (o *BackendsHealth200ResponseDataHealth) HasConsecutiveFailures() bool {
	if o != nil && !IsNil(o.ConsecutiveFailures) {
		return true
	}

	return false
}

// SetConsecutiveFailures gets a reference to the given int32 and assigns it to the ConsecutiveFailures field.
func (o *BackendsHealth200ResponseDataHealth) SetConsecutiveFailures(v int32) {
	o.ConsecutiveFailures = &v
}

// GetConsecutiveSuccesses returns the ConsecutiveSuccesses field value if set, zero value otherwise.
func (o *BackendsHealth200ResponseDataHealth) GetConsecutiveSuccesses() int32 {
	if o == nil || IsNil(o.ConsecutiveSuccesses) {
		var ret int32
		return ret
	}
	return *o.ConsecutiveSuccesses
}

// GetConsecutiveSuccessesOk returns a tuple with the ConsecutiveSuccesses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackendsHealth200ResponseDataHealth) GetConsecutiveSuccessesOk() (*int32, bool) {
	if o == nil || IsNil(o.ConsecutiveSuccesses) {
		return nil, false
	}
	return o.ConsecutiveSuccesses, true
}

// HasConsecutiveSuccesses returns a boolean if a field has been set.
func (o *BackendsHealth200ResponseDataHealth) HasConsecutiveSuccesses() bool {
	if o != nil && !IsNil(o.ConsecutiveSuccesses) {
		return true
	}

	return false
}

// SetConsecutiveSuccesses gets a reference to the given int32 and assigns it to the ConsecutiveSuccesses field.
func (o *BackendsHealth200ResponseDataHealth) SetConsecutiveSuccesses(v int32) {
	o.ConsecutiveSuccesses = &v
}

// GetLastChecked returns the LastChecked field value if set, zero value otherwise.
func (o *BackendsHealth200ResponseDataHealth) GetLastChecked() int32 {
	if o == nil || IsNil(o.LastChecked) {
		var ret int32
		return ret
	}
	return *o.LastChecked
}

// GetLastCheckedOk returns a tuple with the LastChecked field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackendsHealth200ResponseDataHealth) GetLastCheckedOk() (*int32, bool) {
	if o == nil || IsNil(o.LastChecked) {
		return nil, false
	}
	return o.LastChecked, true
}

// HasLastChecked returns a boolean if a field has been set.
func (o *BackendsHealth200ResponseDataHealth) HasLastChecked() bool {
	if o != nil && !IsNil(o.LastChecked) {
		return true
	}

	return false
}

// SetLastChecked gets a reference to the given int32 and assigns it to the LastChecked field.
func (o *BackendsHealth200ResponseDataHealth) SetLastChecked(v int32) {
	o.LastChecked = &v
}

// GetLastFailureReason returns the LastFailureReason field value if set, zero value otherwise.
func (o *BackendsHealth200ResponseDataHealth) GetLastFailureReason() string {
	if o == nil || IsNil(o.LastFailureReason) {
		var ret string
		return ret
	}
	return *o.LastFailureReason
}

// GetLastFailureReasonOk returns a tuple with the LastFailureReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackendsHealth200ResponseDataHealth) GetLastFailureReasonOk() (*string, bool) {
	if o == nil || IsNil(o.LastFailureReason) {
		return nil, false
	}
	return o.LastFailureReason, true
}

// HasLastFailureReason returns a boolean if a field has been set.
func (o *BackendsHealth200ResponseDataHealth) HasLastFailureReason() bool {
	if o != nil && !IsNil(o.LastFailureReason) {
		return true
	}

	return false
}

// SetLastFailureReason gets a reference to the given string and assigns it to the LastFailureReason field.
func (o *BackendsHealth200ResponseDataHealth) SetLastFailureReason(v string) {
	o.LastFailureReason = &v
}

func (o BackendsHealth200ResponseDataHealth) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BackendsHealth200ResponseDataHealth) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CircuitState) {
		toSerialize["circuitState"] = o.CircuitState
	}
	if !IsNil(o.IsHealthy) {
		toSerialize["isHealthy"] = o.IsHealthy
	}
	if !IsNil(o.ConsecutiveFailures) {
		toSerialize["consecutiveFailures"] = o.ConsecutiveFailures
	}
	if !IsNil(o.ConsecutiveSuccesses) {
		toSerialize["consecutiveSuccesses"] = o.ConsecutiveSuccesses
	}
	if !IsNil(o.LastChecked) {
		toSerialize["lastChecked"] = o.LastChecked
	}
	if !IsNil(o.LastFailureReason) {
		toSerialize["lastFailureReason"] = o.LastFailureReason
	}
	return toSerialize, nil
}

type NullableBackendsHealth200ResponseDataHealth struct {
	value *BackendsHealth200ResponseDataHealth
	isSet bool
}

func (v NullableBackendsHealth200ResponseDataHealth) Get() *BackendsHealth200ResponseDataHealth {
	return v.value
}

func (v *NullableBackendsHealth200ResponseDataHealth) Set(val *BackendsHealth200ResponseDataHealth) {
	v.value = val
	v.isSet = true
}

func (v NullableBackendsHealth200ResponseDataHealth) IsSet() bool {
	return v.isSet
}

func (v *NullableBackendsHealth200ResponseDataHealth) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBackendsHealth200ResponseDataHealth(val *BackendsHealth200ResponseDataHealth) *NullableBackendsHealth200ResponseDataHealth {
	return &NullableBackendsHealth200ResponseDataHealth{value: val, isSet: true}
}

func (v NullableBackendsHealth200ResponseDataHealth) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBackendsHealth200ResponseDataHealth) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


