/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StealthMetaAddress type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StealthMetaAddress{}

// StealthMetaAddress struct for StealthMetaAddress
type StealthMetaAddress struct {
	// 0x-prefixed 32-byte hex string
	SpendingKey string `json:"spendingKey" validate:"regexp=^0x[0-9a-fA-F]{64}$"`
	// 0x-prefixed 32-byte hex string
	ViewingKey string `json:"viewingKey" validate:"regexp=^0x[0-9a-fA-F]{64}$"`
	Chain string `json:"chain"`
	Label *string `json:"label,omitempty"`
}

type _StealthMetaAddress StealthMetaAddress

// NewStealthMetaAddress instantiates a new StealthMetaAddress object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStealthMetaAddress(spendingKey string, viewingKey string, chain string) *StealthMetaAddress {
	this := StealthMetaAddress{}
	this.SpendingKey = spendingKey
	this.ViewingKey = viewingKey
	this.Chain = chain
	return &this
}

// NewStealthMetaAddressWithDefaults instantiates a new StealthMetaAddress object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStealthMetaAddressWithDefaults() *StealthMetaAddress {
	this := StealthMetaAddress{}
	return &this
}

// GetSpendingKey returns the SpendingKey field value
func (o *StealthMetaAddress) GetSpendingKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SpendingKey
}

// GetSpendingKeyOk returns a tuple with the SpendingKey field value
// and a boolean to check if the value has been set.
func (o *StealthMetaAddress) GetSpendingKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SpendingKey, true
}

// SetSpendingKey sets field value
func (o *StealthMetaAddress) SetSpendingKey(v string) {
	o.SpendingKey = v
}

// GetViewingKey returns the ViewingKey field value
func (o *StealthMetaAddress) GetViewingKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ViewingKey
}

// GetViewingKeyOk returns a tuple with the ViewingKey field value
// and a boolean to check if the value has been set.
func (o *StealthMetaAddress) GetViewingKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ViewingKey, true
}

// SetViewingKey sets field value
func (o *StealthMetaAddress) SetViewingKey(v string) {
	o.ViewingKey = v
}

// GetChain returns the Chain field value
func (o *StealthMetaAddress) GetChain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Chain
}

// GetChainOk returns a tuple with the Chain field value
// and a boolean to check if the value has been set.
func (o *StealthMetaAddress) GetChainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Chain, true
}

// SetChain sets field value
func (o *StealthMetaAddress) SetChain(v string) {
	o.Chain = v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *StealthMetaAddress) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StealthMetaAddress) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *StealthMetaAddress) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *StealthMetaAddress) SetLabel(v string) {
	o.Label = &v
}

func (o StealthMetaAddress) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StealthMetaAddress) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["spendingKey"] = o.SpendingKey
	toSerialize["viewingKey"] = o.ViewingKey
	toSerialize["chain"] = o.Chain
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	return toSerialize, nil
}

func (o *StealthMetaAddress) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"spendingKey",
		"viewingKey",
		"chain",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStealthMetaAddress := _StealthMetaAddress{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStealthMetaAddress)

	if err != nil {
		return err
	}

	*o = StealthMetaAddress(varStealthMetaAddress)

	return err
}

type NullableStealthMetaAddress struct {
	value *StealthMetaAddress
	isSet bool
}

func (v NullableStealthMetaAddress) Get() *StealthMetaAddress {
	return v.value
}

func (v *NullableStealthMetaAddress) Set(val *StealthMetaAddress) {
	v.value = val
	v.isSet = true
}

func (v NullableStealthMetaAddress) IsSet() bool {
	return v.isSet
}

func (v *NullableStealthMetaAddress) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStealthMetaAddress(val *StealthMetaAddress) *NullableStealthMetaAddress {
	return &NullableStealthMetaAddress{value: val, isSet: true}
}

func (v NullableStealthMetaAddress) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStealthMetaAddress) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


